In [1]:
import pandas as pd
import numpy as np

In [2]:
employee_master = pd.read_excel(r"D:\veena.sharma\My Documents\PROJECTS\PREDICTIVE_ANALYSIS\PSIPL Input Data\Employee Master PSIPL.xls")

print("Shape:", employee_master.shape)
print("Columns:", employee_master.columns.tolist())

Shape: (20486, 92)
Columns: ['Group', 'Company Name', 'Employee Code', 'Title', 'First Name', 'Middle Name', 'Last Name', 'Employee Name', 'Gender', 'Nationality', 'Official Email Address', 'Personal Email Address', 'Resident Type', 'Marital Status', 'City Name', 'State Name', 'Branch', 'Site Branch', 'Division', 'Designation', 'Department', 'Sub Department', 'Cost Center', 'Site Cost Center', 'Site Name', 'Grade', 'Band', 'Reason for Requirement', 'Employee Category', 'Employee Status', 'Reporting Manager Code', 'Reporting Manager Name', 'Skip Level Manager Code', 'Skip Level Manager', 'Actual Join Date', 'Group Join Date', 'Resignation Date', 'Year Of Service (Current DOJ)', 'Year of Service (Group DOJ)', 'Physical Disability', 'Point of Hire', 'Point of Repatriation', 'ESIC Flag', 'ESIC Number', 'PF Applicable', 'PF Type', 'PF Number', 'UAN Number', 'FNF Settlement Date', 'Probation Status', 'Confirmation Date', 'Source of Hire', 'Preferred Name', 'Dual Nationality', 'Religion', 'Agreement type', 'Effective Start Date', 'Effective End Date', 'Employee Air Ticket', 'Air Ticket Class', 'Air Ticket frequency', 'Blood Group', 'Group Medical Insurance', 'Confidential Profile Flag', 'Confidential Profile', 'Conf. Date (Period Master)', '2nd Nationality', 'Employer Notice Period', 'Bank Name', 'Movement Type', 'PAN Number', 'Aadhar Card No', 'Account Number', 'IFSC Code', 'Personal Mobile Number', 'Emergency Contact Number', 'Father Name', 'Birth Date', 'Last Payable Days', 'Last Working Date', 'Cost Code', 'Profit Code', 'Client Vertical', 'Permanent Address', 'Current Address', 'Correspondence Address', 'Leave Status', 'Resident', 'Wage Type', 'TAX Regime', 'Uniform Deduction', 'Process Name']

In [53]:
print("employee_master columns:")
print(employee_master.columns.tolist())

employee_master columns:
['Group', 'Company Name', 'Employee Code', 'Title', 'First Name', 'Middle Name', 'Last Name', 'Employee Name', 'Gender', 'Nationality', 'Official Email Address', 'Personal Email Address', 'Resident Type', 'Marital Status', 'City Name', 'State Name', 'Branch', 'Site Branch', 'Division', 'Designation', 'Department', 'Sub Department', 'Cost Center', 'Site Cost Center', 'Site Name', 'Grade', 'Band', 'Reason for Requirement', 'Employee Category', 'Employee Status', 'Reporting Manager Code', 'Reporting Manager Name', 'Skip Level Manager Code', 'Skip Level Manager', 'Actual Join Date', 'Group Join Date', 'Resignation Date', 'Year Of Service (Current DOJ)', 'Year of Service (Group DOJ)', 'Physical Disability', 'Point of Hire', 'Point of Repatriation', 'ESIC Flag', 'ESIC Number', 'PF Applicable', 'PF Type', 'PF Number', 'UAN Number', 'FNF Settlement Date', 'Probation Status', 'Confirmation Date', 'Source of Hire', 'Preferred Name', 'Dual Nationality', 'Religion', 'Agreement type', 'Effective Start Date', 'Effective End Date', 'Employee Air Ticket', 'Air Ticket Class', 'Air Ticket frequency', 'Blood Group', 'Group Medical Insurance', 'Confidential Profile Flag', 'Confidential Profile', 'Conf. Date (Period Master)', '2nd Nationality', 'Employer Notice Period', 'Bank Name', 'Movement Type', 'PAN Number', 'Aadhar Card No', 'Account Number', 'IFSC Code', 'Personal Mobile Number', 'Emergency Contact Number', 'Father Name', 'Birth Date', 'Last Payable Days', 'Last Working Date', 'Cost Code', 'Profit Code', 'Client Vertical', 'Permanent Address', 'Current Address', 'Correspondence Address', 'Leave Status', 'Resident', 'Wage Type', 'TAX Regime', 'Uniform Deduction', 'Process Name', 'Employee_Code_Clean', '_emp_code']

In [54]:
print(employee_master.head())

                              Group                      Company Name  \
0  Property Solutions India Pvt Ltd  Property Solutions India Pvt Ltd
1  Property Solutions India Pvt Ltd  Property Solutions India Pvt Ltd
2  Property Solutions India Pvt Ltd  Property Solutions India Pvt Ltd
3  Property Solutions India Pvt Ltd  Property Solutions India Pvt Ltd
4  Property Solutions India Pvt Ltd  Property Solutions India Pvt Ltd

  Employee Code Title First Name Middle Name  Last Name  \
0       '566137   Mr.   Kaustubh    Dattaram      Patil
1       '534669   Mr.    Dibakar         NaN  Pattanaik
2       '560618   Mr.       Anil      Tanaji     Dubole
3        '48681   Mr.   Sudhakar       Anand    Hankare
4        '62969   Mr.    Shriram    Seetaram     Kanoje

             Employee Name Gender Nationality  ... Current Address  \
0  Kaustubh Dattaram Patil   Male       India  ...
1        Dibakar Pattanaik   Male       India  ...
2       Anil Tanaji Dubole   Male       India  ...
3   Sudhakar Anand Hankare   Male       India  ...
4  Shriram Seetaram Kanoje   Male       India  ...

  Correspondence Address Leave Status        Resident Wage Type    TAX Regime  \
0                                 NaN   Site Contract   Monthly  New Tax Slab
1                                 NaN   Site Contract   Monthly  New Tax Slab
2                                 NaN   Site Contract   Monthly  New Tax Slab
3                                 NaN  Site Permanent   Monthly  New Tax Slab
4                                 NaN   Site Contract   Monthly  New Tax Slab

  Uniform Deduction Process Name Employee_Code_Clean _emp_code
0                NO          NaN              566137    566137
1                NO          NaN              534669    534669
2                NO          NaN              560618    560618
3                NO          NaN               48681     48681
4                NO          NaN               62969     62969

[5 rows x 94 columns]

In [3]:
resignation_data = pd.read_csv(r"D:\veena.sharma\My Documents\PROJECTS\PREDICTIVE_ANALYSIS\PSIPL Input Data\Resignation Report_20260807081605117.csv")

print("Shape:", resignation_data.shape)
print("Columns:", resignation_data.columns.tolist())

Shape: (7778, 43)
Columns: ['Company Name', 'Employee Code', 'Employee First Name', 'Employee Middle Name', 'Employee Last Name', 'Employee Name', 'Branch', 'Department', 'Division', 'Grade', 'Band', 'Designation', 'Reporting Manager', 'Reporting Partner', 'Reporting Md', 'Date Of Joining', 'City Name', 'Cost Center', 'State Name', 'Resignation Id', 'Resignation Code', 'Resignation Date', 'Resignation Submit Type', 'Lwd As Per Notice Period', 'Requested Relieving Date', 'Agreed Lwd', 'Eligibility To Rehire', 'Eligiblity Reason', 'Resignation Type', 'Resignation Reason', 'Employee Category', 'Contact No', 'Address', 'Personal Email Id', 'Official Email Id', 'Due Clearance Date', 'Execution Handover', 'Resignation Status', 'Resignation Level', 'Submitted By', 'Submitted Date', 'Approved By', 'Approved Date']

In [4]:
overtime_data1 = pd.read_csv(r"D:\veena.sharma\My Documents\PROJECTS\PREDICTIVE_ANALYSIS\PSIPL Input Data\Overtime Upload Report_20260807084943902.csv")
print("Shape:", overtime_data1.shape)
print("Columns:", overtime_data1.columns.tolist())

Shape: (3228, 109)
Columns: ['EMP CODE', 'EMP NAME', 'BRANCH NAME', 'CITY NAME', 'JOIN DATE', 'LAST WORKING DATE', 'DESIGNATION', 'EMPLOYEE CATEGORY', 'COST CENTRE CODE', 'COST CENTRE NAME', 'SITE CODE', 'SITE NAME', 'PAY CYCLE', '26-JUN-26_CH', '26-JUN-26_NCH', '26-JUN-26_TOT', '27-JUN-26_CH', '27-JUN-26_NCH', '27-JUN-26_TOT', '28-JUN-26_CH', '28-JUN-26_NCH', '28-JUN-26_TOT', '29-JUN-26_CH', '29-JUN-26_NCH', '29-JUN-26_TOT', '30-JUN-26_CH', '30-JUN-26_NCH', '30-JUN-26_TOT', '01-JUL-26_CH', '01-JUL-26_NCH', '01-JUL-26_TOT', '02-JUL-26_CH', '02-JUL-26_NCH', '02-JUL-26_TOT', '03-JUL-26_CH', '03-JUL-26_NCH', '03-JUL-26_TOT', '04-JUL-26_CH', '04-JUL-26_NCH', '04-JUL-26_TOT', '05-JUL-26_CH', '05-JUL-26_NCH', '05-JUL-26_TOT', '06-JUL-26_CH', '06-JUL-26_NCH', '06-JUL-26_TOT', '07-JUL-26_CH', '07-JUL-26_NCH', '07-JUL-26_TOT', '08-JUL-26_CH', '08-JUL-26_NCH', '08-JUL-26_TOT', '09-JUL-26_CH', '09-JUL-26_NCH', '09-JUL-26_TOT', '10-JUL-26_CH', '10-JUL-26_NCH', '10-JUL-26_TOT', '11-JUL-26_CH', '11-JUL-26_NCH', '11-JUL-26_TOT', '12-JUL-26_CH', '12-JUL-26_NCH', '12-JUL-26_TOT', '13-JUL-26_CH', '13-JUL-26_NCH', '13-JUL-26_TOT', '14-JUL-26_CH', '14-JUL-26_NCH', '14-JUL-26_TOT', '15-JUL-26_CH', '15-JUL-26_NCH', '15-JUL-26_TOT', '16-JUL-26_CH', '16-JUL-26_NCH', '16-JUL-26_TOT', '17-JUL-26_CH', '17-JUL-26_NCH', '17-JUL-26_TOT', '18-JUL-26_CH', '18-JUL-26_NCH', '18-JUL-26_TOT', '19-JUL-26_CH', '19-JUL-26_NCH', '19-JUL-26_TOT', '20-JUL-26_CH', '20-JUL-26_NCH', '20-JUL-26_TOT', '21-JUL-26_CH', '21-JUL-26_NCH', '21-JUL-26_TOT', '22-JUL-26_CH', '22-JUL-26_NCH', '22-JUL-26_TOT', '23-JUL-26_CH', '23-JUL-26_NCH', '23-JUL-26_TOT', '24-JUL-26_CH', '24-JUL-26_NCH', '24-JUL-26_TOT', '25-JUL-26_CH', '25-JUL-26_NCH', '25-JUL-26_TOT', 'CHARGEABLE TOTAL', 'NON CHARGEABLE TOTAL', 'TOTAL', ' PF CALCULATION TYPE', ' CHARGEBLEOT FORMULA ', ' NONCHARGEBLE OT FORMULA']

In [5]:
overtime_data2 = pd.read_csv(r"d:\veena.sharma\My Documents\PROJECTS\PREDICTIVE_ANALYSIS\PSIPL Input Data\Overtime Upload Report_20260807085253305.csv")
print("Shape:", overtime_data2.shape)
print("Columns:", overtime_data2.columns.tolist())

Shape: (3228, 19)
Columns: ['EMP CODE', 'EMP NAME', 'BRANCH NAME', 'CITY NAME', 'JOIN DATE', 'LAST WORKING DATE', 'DESIGNATION', 'EMPLOYEE CATEGORY', 'COST CENTRE CODE', 'COST CENTRE NAME', 'SITE CODE', 'SITE NAME', 'PAY CYCLE', 'CHARGEABLE TOTAL', 'NON CHARGEABLE TOTAL', 'TOTAL', ' PF CALCULATION TYPE', ' CHARGEBLEOT FORMULA ', ' NONCHARGEBLE OT FORMULA']

In [6]:
overtime_data3 = pd.read_csv(r"D:\veena.sharma\My Documents\PROJECTS\PREDICTIVE_ANALYSIS\PSIPL Input Data\Overtime Upload Report_20260807085310437.csv")
print("Shape:", overtime_data3.shape)
print("Columns:", overtime_data3.columns.tolist())

Shape: (4783, 19)
Columns: ['EMP CODE', 'EMP NAME', 'BRANCH NAME', 'CITY NAME', 'JOIN DATE', 'LAST WORKING DATE', 'DESIGNATION', 'EMPLOYEE CATEGORY', 'COST CENTRE CODE', 'COST CENTRE NAME', 'SITE CODE', 'SITE NAME', 'PAY CYCLE', 'CHARGEABLE TOTAL', 'NON CHARGEABLE TOTAL', 'TOTAL', ' PF CALCULATION TYPE', ' CHARGEBLEOT FORMULA ', ' NONCHARGEBLE OT FORMULA']

In [7]:
overtime_data4 = pd.read_csv(r"D:\veena.sharma\My Documents\PROJECTS\PREDICTIVE_ANALYSIS\PSIPL Input Data\Overtime Upload Report_20260807085324157.csv")
print("Shape:", overtime_data4.shape)
print("Columns:", overtime_data4.columns.tolist())

Shape: (4783, 112)
Columns: ['EMP CODE', 'EMP NAME', 'BRANCH NAME', 'CITY NAME', 'JOIN DATE', 'LAST WORKING DATE', 'DESIGNATION', 'EMPLOYEE CATEGORY', 'COST CENTRE CODE', 'COST CENTRE NAME', 'SITE CODE', 'SITE NAME', 'PAY CYCLE', '01-JUL-26_CH', '01-JUL-26_NCH', '01-JUL-26_TOT', '02-JUL-26_CH', '02-JUL-26_NCH', '02-JUL-26_TOT', '03-JUL-26_CH', '03-JUL-26_NCH', '03-JUL-26_TOT', '04-JUL-26_CH', '04-JUL-26_NCH', '04-JUL-26_TOT', '05-JUL-26_CH', '05-JUL-26_NCH', '05-JUL-26_TOT', '06-JUL-26_CH', '06-JUL-26_NCH', '06-JUL-26_TOT', '07-JUL-26_CH', '07-JUL-26_NCH', '07-JUL-26_TOT', '08-JUL-26_CH', '08-JUL-26_NCH', '08-JUL-26_TOT', '09-JUL-26_CH', '09-JUL-26_NCH', '09-JUL-26_TOT', '10-JUL-26_CH', '10-JUL-26_NCH', '10-JUL-26_TOT', '11-JUL-26_CH', '11-JUL-26_NCH', '11-JUL-26_TOT', '12-JUL-26_CH', '12-JUL-26_NCH', '12-JUL-26_TOT', '13-JUL-26_CH', '13-JUL-26_NCH', '13-JUL-26_TOT', '14-JUL-26_CH', '14-JUL-26_NCH', '14-JUL-26_TOT', '15-JUL-26_CH', '15-JUL-26_NCH', '15-JUL-26_TOT', '16-JUL-26_CH', '16-JUL-26_NCH', '16-JUL-26_TOT', '17-JUL-26_CH', '17-JUL-26_NCH', '17-JUL-26_TOT', '18-JUL-26_CH', '18-JUL-26_NCH', '18-JUL-26_TOT', '19-JUL-26_CH', '19-JUL-26_NCH', '19-JUL-26_TOT', '20-JUL-26_CH', '20-JUL-26_NCH', '20-JUL-26_TOT', '21-JUL-26_CH', '21-JUL-26_NCH', '21-JUL-26_TOT', '22-JUL-26_CH', '22-JUL-26_NCH', '22-JUL-26_TOT', '23-JUL-26_CH', '23-JUL-26_NCH', '23-JUL-26_TOT', '24-JUL-26_CH', '24-JUL-26_NCH', '24-JUL-26_TOT', '25-JUL-26_CH', '25-JUL-26_NCH', '25-JUL-26_TOT', '26-JUL-26_CH', '26-JUL-26_NCH', '26-JUL-26_TOT', '27-JUL-26_CH', '27-JUL-26_NCH', '27-JUL-26_TOT', '28-JUL-26_CH', '28-JUL-26_NCH', '28-JUL-26_TOT', '29-JUL-26_CH', '29-JUL-26_NCH', '29-JUL-26_TOT', '30-JUL-26_CH', '30-JUL-26_NCH', '30-JUL-26_TOT', '31-JUL-26_CH', '31-JUL-26_NCH', '31-JUL-26_TOT', 'CHARGEABLE TOTAL', 'NON CHARGEABLE TOTAL', 'TOTAL', ' PF CALCULATION TYPE', ' CHARGEBLEOT FORMULA ', ' NONCHARGEBLE OT FORMULA']

In [8]:
leave_data = pd.read_csv(r"D:\veena.sharma\My Documents\PROJECTS\PREDICTIVE_ANALYSIS\PSIPL Input Data\Yearly Leave Balance Report_20260806113614204.csv")
print("Shape:", leave_data.shape)
print("Columns:", leave_data.columns.tolist())

Shape: (31523, 28)
Columns: ['Group', 'Entity Name', 'Employee Code', 'Employee Name', 'Date of joining', 'Department', 'Grade', 'Designation', 'Leave Type', 'Reporting Manager', 'City Name', 'Branch', 'State Name', 'Cost Center', 'Employee Status', 'Opening Balance (A)', 'Accrued Till Date (B)', 'Consumed Till Date (C)', 'Availed Adjustment (D)', 'Lapse (E)', 'Balance Till Date (F) = A+B-C+D-E', 'Future Dated Approved Leave (G)', 'Balance Including Future Dated Approved Leave H (F-G)', 'Leave Encashment(I)', 'Carry Forward To Next Year J= (H-I)', 'Leave Year Start Date', 'Leave Year End Date', 'Accounting Year']

In [9]:
form_data = pd.read_csv(r"D:\veena.sharma\My Documents\PROJECTS\PREDICTIVE_ANALYSIS\PSIPL Input Data\FORM ONE F Report_20260807081614022.csv")
print("Shape:", form_data.shape)
print("Columns:", form_data.columns.tolist())

Shape: (9762, 197)
Columns: ['Employee Status', 'Soft Joining ID', 'Employee Verify Type', 'Onboarding Date', 'Employee Code', 'Employee Name', 'Date Of Joined', 'Date Of Birth', 'Designation', 'Cost Center', 'Gender', 'Marital Status', 'Contact No', 'Emergency No', 'Location', 'Region Name', 'Present Address', 'Permanent Address', 'Site Name', 'Operation Manager', 'Client Verticle', 'Onboarding User', 'PAN Number', 'AADHAR Number', 'ESIC No', 'UAN Number', 'Account No', 'Bank Name', 'IFSC Code', 'Religion', 'Blood Group', 'Nominee Name', 'Relation', 'Fathers Name / Husband Name', 'Higher Education', 'Created Date', 'ABRY BENEFIT', 'ACCOR MEAL VOUCHER', 'ADMIN COST TRAINING & CONTINGENCY COST', 'ANNUAL BONUS', 'ATTENDANCE ALLOWANCE', 'ATTENDANCE INCENTIVE', 'ATTIRE REIMBURSEMENT', 'BASIC', 'BONUS', 'BOOKS AND PERIODICALS', 'CANTEEN DEDUCTION', 'CAR REIMBURSEMENT', 'CASH ALLOWANCE', 'CHILD ALLOWANCE', 'CITY COMPENSATORY ALLOW', 'CO CNTR TO EDLI ADMN CHARGE', 'CO CNTR TO EDLI CHARGES', 'CO CNTR TO PF ADMN CHARGES', 'COMMUNICATION ALLOWANCE', 'CONVEYANCE ALLOWANCE', 'CONVEYANCE ALLOWANCE OLD', 'CREDIT SOC RECOVERY', 'CUSTOMISED POOL', 'CUSTOMIZED POOL', 'DAILY BASIC', 'DAILY BONUS', 'DAILY CITY COMP ALLW', 'DAILY CONVEYANCE', 'DAILY CUSTOMIZED POOL', 'DAILY DEARNESS ALLOW', 'DAILY EDUCATION ALW', 'DAILY FOOD ALLOWANE', 'DAILY HRA', 'DAILY LEAVE ENCASHMENT', 'DAILY LUNCH', 'DAILY MEDICAL ALLOWANCE', 'DAILY OTHER ALW', 'DAILY PERSONAL ALLOWANCE', 'DAILY SITE ALLOWANCE', 'DAILY SPECIAL ALLWN', 'DAILY TRANSPORT ALLOW', 'DAILY WASHING', 'DEARNESS ALLOWANCE', 'DISABLED DEPENDANT ALLOWANCE', 'DLSTIPEND', 'DRIVER', 'EDUCATION ALLOWANCE', 'EDUCATION LOAN DEDUCTION', 'EMPLOYEE OF THE MONTH', 'EMPLOYEE REFERRAL', 'EMPLOYER CONTRI TO NPS', 'EMPLOYER CONTRI TO PF', 'EMPLOYER CONTRIBUT PENSION', 'ENTERTAINMENT ALLOWANCE', 'ESIC', 'ESIC EMPLOYER CONTRI', 'EXECUTIVE ALLOWANCE', 'EXGRATIA', 'EXGRATIA A', 'Esic', 'FESTIVAL ADVANCE', 'FESTIVAL GIFT', 'FLEXY PAY', 'FOOD ALLOWANCE', 'FOOD COUPON', 'GRATUITY', 'HEAD INSURANCE ADMIN', 'HOME LEAVE ALLOWANCE', 'HOUSE RENT ALLOWANCE', 'INCENTIVE ONE', 'INCOME TAX', 'INSURANCE', 'INSURANCE FUND', 'INTEREST LOAN', 'JOINING BONUS', 'L T EXPENSE TAXABLE OLD', 'L T EXPENSE TAXFREE', 'LABOUR WELFARE FUND', 'LEAVE', 'LEAVE ENCASHMENT', 'LEAVE ENCASHMENT TAXABLE', 'LEAVE PAYMENT', 'LEAVE TRAVEL ALLOWANCE', 'LEAVEPAY', 'LIC DEDUCATION', 'LOAN DEDUCTION', 'LONG', 'LONG SERVICE AWARD', 'LOYALITY BONUS', 'LWF(Employer)', 'MANDATORY PROVIDENT FUND EES OLD', 'MEAL DEDUCTION', 'MEAL VOUCHER', 'MEDICAL', 'MEDICAL ALLOWANCE', 'MEDICAL REIMBURSEMENT', 'MOBILE ALLOWANCE', 'MOBILE DEDUCTION', 'MOBILE DEVICE REIMBURSEMENT', 'NFH', 'NOTICE PAY', 'NOTICE PAY PAYMENT', 'NOTICE PAY RECOVERY', 'NPS DEDUCTION', 'NPS EMPLOYER CONTRIBUTION', 'OTHER ALLOWANCE', 'OTHER DEDUCTION', 'OTHER EARNING', 'OTHER PAYMENT', 'OTHER RECOVERY', 'OVERTIME', 'OVERTIME OLD', 'PCC DEDUCTION', 'PD CARD', 'PERFORMANCE BASED BONUS', 'PERFORMANCE BONUS', 'PERFORMANCE LINKED PAY', 'PERSONAL LOAN', 'PERSONAL PAY', 'PF ADMIN', 'PF LOAN', 'PRINCIPLE LOAN', 'PROF PURSUIT REIMBURSEMENT', 'PROFESSIONAL ALLOWANCE', 'PROFESSIONAL TAX', 'PUBLIC HOLIDAY', 'Patrocard', 'Provident Fund', 'REFERRAL INCENTIVE', 'RELOCATION ALLOWANCE', 'RENT DEDUCTION', 'RETENTION BONUS', 'RETIREMENT PLAN DED', 'RETRECHMENT ALLLOWANCE', 'SALARY ADVANCE', 'SINGLE PARENT ALLOWANCE', 'SITE ALLOWANCE', 'SITE HOLIDAY', 'SODEXO GIFT VOUCHER', 'SPECIAL ALLOWANCE', 'STAFF LOAN', 'STATUTORY BONUS', 'STATUTORY P F', 'STIPEND', 'STIPEND OLD', 'SUPERVISORY ALLOWANCE', 'TELEPHONE REIMBURSEMENT', 'TRANSPORT ALLOWANCE', 'TRANSPORT DEDUCTION', 'UNIFORM AND SHOES', 'UNIFORM DEPOSITE REFUND', 'UTILITY ALLOWANCE', 'VEHICAL ALLOWANCE', 'VEHICLE ALLOWANCE', 'VERD', 'VOLUNTARY PF', 'WASHING ALLOWANCE', 'WPC', 'WPC INCENTIVE', 'YLY LEAVE ENCASHMENT TAXABLE', 'Monthly Gross Salary']

C:\Users\veena.sharma\AppData\Local\Temp\ipykernel_3824\826296093.py:1: DtypeWarning: Columns (0: Religion, 1: Blood Group) have mixed types. Specify dtype option on import or set low_memory=False.
  form_data = pd.read_csv(r"D:\veena.sharma\My Documents\PROJECTS\PREDICTIVE_ANALYSIS\PSIPL Input Data\FORM ONE F Report_20260807081614022.csv")

In [10]:
print("Employee Master unique employees:", employee_master["Employee Code"].nunique())
print("Resignation unique employees:",resignation_data["Employee Code"].nunique())
print("OT1 unique employees:", overtime_data1["EMP CODE"].nunique())
print("OT2 unique employees:", overtime_data2["EMP CODE"].nunique())
print("OT3 unique employees:", overtime_data3["EMP CODE"].nunique())
print("OT4 unique employees:", overtime_data4["EMP CODE"].nunique())
print("Leave unique employees:", leave_data["Employee Code"].nunique())
print("FORM ONE F unique employees:", form_data["Employee Code"].nunique())

Employee Master unique employees: 20468
Resignation unique employees: 7547
OT1 unique employees: 3218
OT2 unique employees: 3218
OT3 unique employees: 4781
OT4 unique employees: 4781
Leave unique employees: 25952
FORM ONE F unique employees: 7890

In [11]:
print("\nEmployee Master:")
print(employee_master["Employee Code"].dtype)
print(employee_master["Employee Code"].head(10).tolist())

print("\nFORM ONE F:")
print(form_data["Employee Code"].dtype)
print(form_data["Employee Code"].head(10).tolist())

print("\nOT1:")
print(overtime_data1["EMP CODE"].dtype)
print(overtime_data1["EMP CODE"].head(10).tolist())

Employee Master:
str
["'566137", "'534669", "'560618", "'48681", "'62969", "'62053", "'522934", "'550389", "'558924", "'541817"]

FORM ONE F:
str
["'", "'PSIPL500001", "'", "'", "'", "'577375", "'", "'576918", "'576894", "'576884"]

OT1:
int64
[11168, 11603, 11625, 14000, 16145, 16166, 17288, 17366, 17485, 18658]

In [12]:
def normalize_emp_code(series):
    return (
        series.astype("string")
        .str.strip()
        .str.replace("'", "", regex=False)
        .str.replace(r"\.0$", "", regex=True)
        .replace({"": pd.NA, "nan": pd.NA, "None": pd.NA})
    )


employee_codes = normalize_emp_code(employee_master["Employee Code"])
resignation_codes = normalize_emp_code(resignation_data["Employee Code"])
ot1_codes = normalize_emp_code(overtime_data1["EMP CODE"])
ot2_codes = normalize_emp_code(overtime_data2["EMP CODE"])
ot3_codes = normalize_emp_code(overtime_data3["EMP CODE"])
ot4_codes = normalize_emp_code(overtime_data4["EMP CODE"])
leave_codes = normalize_emp_code(leave_data["Employee Code"])
form_codes = normalize_emp_code(form_data["Employee Code"])


print("Employee Master codes:", employee_codes.nunique())
print("Resignation codes:", resignation_codes.nunique())
print("OT1 codes:", ot1_codes.nunique())
print("OT2 codes:", ot2_codes.nunique())
print("OT3 codes:", ot3_codes.nunique())
print("OT4 codes:", ot4_codes.nunique())
print("Leave codes:", leave_codes.nunique())
print("FORM ONE F codes:", form_codes.nunique())


print("\n--- Overlap with Employee Master ---")

employee_set = set(employee_codes.dropna())

for name, codes in [
    ("Resignation", resignation_codes),
    ("OT1", ot1_codes),
    ("OT2", ot2_codes),
    ("OT3", ot3_codes),
    ("OT4", ot4_codes),
    ("Leave", leave_codes),
    ("FORM ONE F", form_codes),
]:
    code_set = set(codes.dropna())
    overlap = employee_set.intersection(code_set)

    print(f"{name}: {len(overlap)} matching employees")

Employee Master codes: 20468
Resignation codes: 7547
OT1 codes: 3218
OT2 codes: 3218
OT3 codes: 4781
OT4 codes: 4781
Leave codes: 25952
FORM ONE F codes: 7889

--- Overlap with Employee Master ---
Resignation: 223 matching employees
OT1: 3206 matching employees
OT2: 3206 matching employees
OT3: 4766 matching employees
OT4: 4761 matching employees
Leave: 18332 matching employees
FORM ONE F: 6645 matching employees

In [13]:

# Normalize the Employee Code columns
employee_master["Employee_Code_Clean"] = normalize_emp_code(
    employee_master["Employee Code"]
)

resignation_data["Employee_Code_Clean"] = normalize_emp_code(
    resignation_data["Employee Code"]
)

# Find resignation records that DO match Employee Master
resignation_matches = resignation_data[
    resignation_data["Employee_Code_Clean"].isin(
        set(employee_master["Employee_Code_Clean"].dropna())
    )
].copy()

print("Matching resignation rows:", len(resignation_matches))
print(
    "Unique matching resigned employees:",
    resignation_matches["Employee_Code_Clean"].nunique()
)

print("\nSample matching resignation records:")
print(
    resignation_matches[
        [
            "Employee Code",
            "Employee Name",
            "Resignation Date",
            "Resignation Status",
            "Resignation Reason"
        ]
    ].head(10)
)

Matching resignation rows: 237
Unique matching resigned employees: 223

Sample matching resignation records:
    Employee Code             Employee Name Resignation Date  \
13        '516654           Suhas Balu Pote      13-APR-2026
33        '536646                 Monu Jena      22-MAY-2026
48        '565262         Jatin Kallu Patil      13-FEB-2026
59         '89543               Chetan  Das      22-MAY-2026
69        '533424       Satish Ramesh Harad      17-JUN-2026
87        '553546  Vikas Balkrishna Sarjine      09-MAY-2026
123       '539085                 Bhashasab      19-JUL-2026
144       '555583             G Janakiraman      06-MAY-2026
185       '560210                Uttam Das       01-JUN-2026
199       '555566                   Subash       09-MAY-2026

                Resignation Status          Resignation Reason
13     Reject by Reporting Manager   Better Career Opportunity
33                    Auto Approve  Pursuing Further Education
48     Reject by Reporting Manager   Better Career Opportunity
59                    Auto Approve  Pursuing Further Education
69                          Submit   Better Compensation Offer
87   Approve by Skip Level Manager          Career Advancement
123       Approve By Site Managers          Disciplinary issue
144                         Submit   Better Compensation Offer
185                   Auto Approve  Pursuing Further Education
199                         Submit   Better Compensation Offer

In [14]:
print("Resignation Status distribution:")
print(
    resignation_data["Resignation Status"]
    .astype("string")
    .str.strip()
    .value_counts(dropna=False)
)

Resignation Status distribution:
Resignation Status
Auto Approve                           5342
Approve by Skip Level Manager          1797
Approve By Site Managers                291
Submit                                  157
Approve by Reporting Manager            153
Reject by Reporting Manager              13
Reject by Skip Level Manager              9
Revoke Approve by Reporting Manager       6
Approve by Reporting Partner              4
Approve By Operation Manager              2
Reject By Site Managers                   2
Approve By Reporting Manager              1
Approve by RM RP Sys Admin                1
Name: count, dtype: Int64

In [15]:
print("\nResignation Type distribution:")
print(
    resignation_data["Resignation Type"]
    .astype("string")
    .str.strip()
    .value_counts(dropna=False)
)

Resignation Type distribution:
Resignation Type
Voluntary separation          7503
In-voluntary separation        211
Mutually agreed separation      61
Death                            3
Name: count, dtype: Int64

In [16]:
print("\nEmployee Master status distribution:")
print(
    employee_master["Employee Status"]
    .astype("string")
    .str.strip()
    .value_counts(dropna=False)
)

Employee Master status distribution:
Employee Status
Live         20339
On-Notice      147
Name: count, dtype: Int64

In [17]:
print("Resignation records with Last Working Date:")
print(
    resignation_data["Agreed Lwd"]
    .notna()
    .value_counts()
)

print("\nResignation records with Resignation Date:")
print(
    resignation_data["Resignation Date"]
    .notna()
    .value_counts()
)

print("\nResignation date range:")
print(
    pd.to_datetime(
        resignation_data["Resignation Date"],
        errors="coerce"
    ).agg(["min", "max"])
)

print("\nAgreed LWD date range:")
print(
    pd.to_datetime(
        resignation_data["Agreed Lwd"],
        errors="coerce"
    ).agg(["min", "max"])
)

Resignation records with Last Working Date:
Agreed Lwd
True    7778
Name: count, dtype: int64

Resignation records with Resignation Date:
Resignation Date
True    7778
Name: count, dtype: int64

Resignation date range:
min   2026-01-01
max   2026-08-07
Name: Resignation Date, dtype: datetime64[us]

Agreed LWD date range:
min   2025-09-15
max   2026-08-26
Name: Agreed Lwd, dtype: datetime64[us]

C:\Users\veena.sharma\AppData\Local\Temp\ipykernel_3824\2068638415.py:17: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(
C:\Users\veena.sharma\AppData\Local\Temp\ipykernel_3824\2068638415.py:25: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(

In [18]:
print("\nResignation status + LWD availability:")

status_lwd = (
    resignation_data.assign(
        Has_LWD=resignation_data["Agreed Lwd"].notna()
    )
    .groupby("Resignation Status")["Has_LWD"]
    .agg(["count", "sum"])
    .sort_values("count", ascending=False)
)

print(status_lwd)

Resignation status + LWD availability:
                                     count   sum
Resignation Status
Auto Approve                          5342  5342
Approve by Skip Level Manager         1797  1797
Approve By Site Managers               291   291
Submit                                 157   157
Approve by Reporting Manager           153   153
Reject by Reporting Manager             13    13
Reject by Skip Level Manager             9     9
Revoke Approve by Reporting Manager      6     6
Approve by Reporting Partner             4     4
Approve By Operation Manager             2     2
Reject By Site Managers                  2     2
Approve by RM RP Sys Admin               1     1
Approve By Reporting Manager             1     1

In [19]:
# Convert Agreed LWD to datetime
resignation_data["Agreed_Lwd_Date"] = pd.to_datetime(
    resignation_data["Agreed Lwd"],
    errors="coerce"
)

cutoff_date = pd.Timestamp("2026-07-31")

print("Agreed LWD before/on 31-Jul-2026:")
print(
    (resignation_data["Agreed_Lwd_Date"] <= cutoff_date).sum()
)

print("\nAgreed LWD after 31-Jul-2026:")
print(
    (resignation_data["Agreed_Lwd_Date"] > cutoff_date).sum()
)

print("\nAgreed LWD by month:")
print(
    resignation_data["Agreed_Lwd_Date"]
    .dt.to_period("M")
    .value_counts()
    .sort_index()
)

Agreed LWD before/on 31-Jul-2026:
7761

Agreed LWD after 31-Jul-2026:
17

Agreed LWD by month:
Agreed_Lwd_Date
2025-09       1
2025-10       3
2025-11       3
2025-12      21
2026-01     217
2026-02     453
2026-03     937
2026-04     554
2026-05    4411
2026-06    1057
2026-07     104
2026-08      17
Freq: M, Name: count, dtype: int64

C:\Users\veena.sharma\AppData\Local\Temp\ipykernel_3824\225262593.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  resignation_data["Agreed_Lwd_Date"] = pd.to_datetime(

In [20]:
# Normalize resignation employee codes
resignation_codes_clean = normalize_emp_code(
    resignation_data["Employee Code"]
)

# Unique resignation employee codes
resignation_set = set(resignation_codes_clean.dropna())

print("Unique resignation employees:", len(resignation_set))

print("\n--- Resignation employee overlap with feature datasets ---")

for name, codes in [
    ("Employee Master", employee_codes),
    ("OT1", ot1_codes),
    ("OT2", ot2_codes),
    ("OT3", ot3_codes),
    ("OT4", ot4_codes),
    ("Leave", leave_codes),
    ("FORM ONE F", form_codes),
]:
    dataset_set = set(codes.dropna())
    overlap = resignation_set.intersection(dataset_set)

    print(f"{name}: {len(overlap)} matching resigned employees")

Unique resignation employees: 7547

--- Resignation employee overlap with feature datasets ---
Employee Master: 223 matching resigned employees
OT1: 26 matching resigned employees
OT2: 26 matching resigned employees
OT3: 79 matching resigned employees
OT4: 79 matching resigned employees
Leave: 6043 matching resigned employees
FORM ONE F: 1173 matching resigned employees

In [21]:
print("========== RESIGNATION ==========")

print("Resignation Date:")
print(
    pd.to_datetime(
        resignation_data["Resignation Date"],
        errors="coerce"
    ).agg(["min", "max"])
)

print("\nAgreed LWD:")
print(
    pd.to_datetime(
        resignation_data["Agreed Lwd"],
        errors="coerce"
    ).agg(["min", "max"])
)


print("\n========== LEAVE ==========")

print("Leave Year Start:")
print(
    pd.to_datetime(
        leave_data["Leave Year Start Date"],
        errors="coerce"
    ).agg(["min", "max"])
)

print("\nLeave Year End:")
print(
    pd.to_datetime(
        leave_data["Leave Year End Date"],
        errors="coerce"
    ).agg(["min", "max"])
)


print("\n========== FORM ONE F ==========")

print("Date Of Joined:")
print(
    pd.to_datetime(
        form_data["Date Of Joined"],
        errors="coerce"
    ).agg(["min", "max"])
)

print("\nCreated Date:")
print(
    pd.to_datetime(
        form_data["Created Date"],
        errors="coerce"
    ).agg(["min", "max"])
)

========== RESIGNATION ==========
Resignation Date:
min   2026-01-01
max   2026-08-07
Name: Resignation Date, dtype: datetime64[us]

Agreed LWD:
min   2025-09-15
max   2026-08-26
Name: Agreed Lwd, dtype: datetime64[us]

========== LEAVE ==========
Leave Year Start:
min   2026-04-01
max   2026-04-01
Name: Leave Year Start Date, dtype: datetime64[us]

Leave Year End:
min   2027-03-31
max   2027-03-31
Name: Leave Year End Date, dtype: datetime64[us]

========== FORM ONE F ==========
Date Of Joined:
min   2025-12-22
max   2026-08-31
Name: Date Of Joined, dtype: datetime64[us]

Created Date:
min   2026-01-12
max   2026-08-07
Name: Created Date, dtype: datetime64[us]

C:\Users\veena.sharma\AppData\Local\Temp\ipykernel_3824\1110154944.py:5: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(
C:\Users\veena.sharma\AppData\Local\Temp\ipykernel_3824\1110154944.py:13: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(
C:\Users\veena.sharma\AppData\Local\Temp\ipykernel_3824\1110154944.py:43: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(
C:\Users\veena.sharma\AppData\Local\Temp\ipykernel_3824\1110154944.py:51: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(

In [22]:
employee_codes = normalize_emp_code(employee_master["Employee Code"])
resignation_codes = normalize_emp_code(resignation_data["Employee Code"])

ot1_codes = normalize_emp_code(overtime_data1["EMP CODE"])
ot2_codes = normalize_emp_code(overtime_data2["EMP CODE"])
ot3_codes = normalize_emp_code(overtime_data3["EMP CODE"])
ot4_codes = normalize_emp_code(overtime_data4["EMP CODE"])

leave_codes = normalize_emp_code(leave_data["Employee Code"])
form_codes = normalize_emp_code(form_data["Employee Code"])

In [23]:

# ==========================================================
# STEP 1: CREATE ATTRITION TARGET
# ==========================================================

# Normalize employee codes
employee_master["_emp_code"] = normalize_emp_code(
    employee_master["Employee Code"]
)

resignation_data["_emp_code"] = normalize_emp_code(
    resignation_data["Employee Code"]
)

# Employee codes who have a resignation record
resigned_employee_codes = set(
    resignation_data["_emp_code"].dropna()
)

# Start with current Employee Master
model_base = employee_master.copy()

# Create target
model_base["Attrition"] = model_base["_emp_code"].isin(
    resigned_employee_codes
).astype(int)

print("Total employees in model base:", len(model_base))
print("\nAttrition distribution:")
print(model_base["Attrition"].value_counts())

print("\nAttrition percentage:")
print(model_base["Attrition"].mean() * 100)

print("\nUnique employee codes:")
print(model_base["_emp_code"].nunique())

Total employees in model base: 20486

Attrition distribution:
Attrition
0    20245
1      241
Name: count, dtype: int64

Attrition percentage:
1.1764131602069705

Unique employee codes:
20468

In [24]:
# ==========================================================
# STEP 2: CHECK DUPLICATES AMONG ATTRITION EMPLOYEES
# ==========================================================

attrition_rows = model_base[model_base["Attrition"] == 1].copy()

print("Attrition rows:", len(attrition_rows))
print("Unique attrition employees:", attrition_rows["_emp_code"].nunique())

print("\nDuplicate employee codes among attrition employees:")

duplicate_attrition_codes = (
    attrition_rows["_emp_code"]
    .value_counts()
    .loc[lambda x: x > 1]
)

print(duplicate_attrition_codes)

print("\nNumber of duplicated attrition employee codes:",
    len(duplicate_attrition_codes))

Attrition rows: 241
Unique attrition employees: 223

Duplicate employee codes among attrition employees:
_emp_code
OS7221    3
49400     2
OS5964    2
OS0319    2
62428     2
518582    2
OS4171    2
511149    2
OS8611    2
OS8249    2
OS9200    2
517265    2
543502    2
OS5521    2
579526    2
OS7035    2
OS5520    2
Name: count, dtype: Int64

Number of duplicated attrition employee codes: 17

In [25]:
# ==========================================================
# STEP 3: INSPECT DUPLICATE EMPLOYEE MASTER RECORDS
# ==========================================================

duplicate_codes = (
    model_base.loc[
        model_base["Attrition"] == 1, "_emp_code"
    ]
    .value_counts()
)

duplicate_codes = duplicate_codes[
    duplicate_codes > 1
].index.tolist()

duplicate_records = model_base[
    model_base["_emp_code"].isin(duplicate_codes)
].copy()

# Show important fields for the duplicate employees
duplicate_check = duplicate_records[
    [
        "_emp_code",
        "Employee Code",
        "Employee Name",
        "Employee Status",
        "Actual Join Date",
        "Group Join Date",
        "Resignation Date",
        "Designation",
        "Department",
        "Branch",
        "Employee Category"
    ]
].sort_values("_emp_code")

print("Duplicate employee records:")
display(duplicate_check)

print("\nTotal duplicate rows:", len(duplicate_check))
print("Unique duplicated employees:", duplicate_check["_emp_code"].nunique())

Duplicate employee records:

,_emp_code,Employee Code,Employee Name,Employee Status,Actual Join Date,Group Join Date,Resignation Date,Designation,Department,Branch,Employee Category
1181,49400,'49400,Nalini Muraleedharan,On-Notice,2014-06-01,2014-06-01,2026-04-25,Chambermaid,Operations,CHENNAI,Permanent
19043,49400,'49400,Nalini Muraleedharan,On-Notice,2014-06-01,2014-06-01,2026-08-07,Chambermaid,Operations,CHENNAI,Permanent
6118,511149,'511149,Dayana Mary,On-Notice,2020-03-11,2020-03-11,2026-04-12,Chambermaid,Operations,CHENNAI,Permanent
6119,511149,'511149,Dayana Mary,On-Notice,2020-03-11,2020-03-11,2026-08-07,Chambermaid,Operations,CHENNAI,Permanent
18450,517265,'517265,Rajesh Hauslaprasad Yadav,Live,2021-01-20,2021-01-20,2026-07-24,Stp Operator,Operations,Mumbai Vikroli,Permanent
8344,517265,'517265,Rajesh Hauslaprasad Yadav,Live,2021-01-20,2021-01-20,2026-08-01,Stp Operator,Operations,Mumbai Vikroli,Permanent
18905,518582,'518582,Remadevi Raman,On-Notice,2021-04-01,2021-04-01,2026-08-07,Chambermaid,Operations,CHENNAI,Permanent
3662,518582,'518582,Remadevi Raman,On-Notice,2021-04-01,2021-04-01,2026-05-21,Chambermaid,Operations,CHENNAI,Permanent
18875,543502,'543502,Sameena Sarfaraz Patel,Live,2023-08-10,2023-08-10,2026-08-01,Chambermaid,Operations,Mumbai Vikroli,Permanent
8805,543502,'543502,Sameena Sarfaraz Patel,Live,2023-08-10,2023-08-10,2026-07-16,Chambermaid,Operations,Mumbai Vikroli,Permanent
17097,579526,'579526,Bittu Francis,On-Notice,2026-03-12,2026-03-12,2026-08-07,Electrician,Operations,CHENNAI,Contract
14571,579526,'579526,Bittu Francis,On-Notice,2026-03-12,2026-03-12,2026-04-20,Electrician,Operations,CHENNAI,Contract
3658,62428,'62428,Prajakta Prakash Chalke,Live,2016-04-01,2016-04-01,2026-05-30,Chambermaid,Operations,Mumbai HO Andheri,Permanent
16272,62428,'62428,Prajakta Prakash Chalke,Live,2016-04-01,2016-04-01,2026-06-06,Chambermaid,Operations,Mumbai HO Andheri,Permanent
12564,OS0319,'OS0319,Manoj Pandey,On-Notice,2026-05-11,2026-05-11,2026-07-16,Executive - Operations,Operations,CHENNAI,Permanent
2402,OS0319,'OS0319,Manoj Pandey,On-Notice,2026-05-11,2026-05-11,2026-07-17,Executive - Operations,Operations,CHENNAI,Permanent
10005,OS4171,'OS4171,Hrishikesh Marballi,On-Notice,2026-05-11,2026-05-11,2026-07-16,Executive - Operations,Operations,CHENNAI,Permanent
4887,OS4171,'OS4171,Hrishikesh Marballi,On-Notice,2026-05-11,2026-05-11,2026-07-17,Executive - Operations,Operations,CHENNAI,Permanent
14886,OS5520,'OS5520,Darshan Parab,On-Notice,2026-05-11,2026-05-11,2026-07-17,Executive - Operations,Operations,CHENNAI,Permanent
14887,OS5520,'OS5520,Darshan Parab,On-Notice,2026-05-11,2026-05-11,2026-07-16,Executive - Operations,Operations,CHENNAI,Permanent
9920,OS5521,'OS5521,Poonam Prabhu,On-Notice,2026-05-11,2026-05-11,2026-07-16,Executive - Operations,Operations,CHENNAI,Permanent
14885,OS5521,'OS5521,Poonam Prabhu,On-Notice,2026-05-11,2026-05-11,2026-07-17,Executive - Operations,Operations,CHENNAI,Permanent
2227,OS5964,'OS5964,SACHIN KADAM,On-Notice,2026-04-29,2026-04-29,2026-07-16,Executive - Finance & Accounts,Finance & Accounts,Mumbai HO Andheri,Permanent
7365,OS5964,'OS5964,SACHIN KADAM,On-Notice,2026-04-29,2026-04-29,2026-07-17,Executive - Finance & Accounts,Finance & Accounts,Mumbai HO Andheri,Permanent
20089,OS7035,'OS7035,PRAVIIN NAIK,On-Notice,2026-04-27,2026-04-27,2026-07-16,Senior Executive - Finance & Accounts,Finance & Accounts,CHENNAI,Permanent
14883,OS7035,'OS7035,PRAVIIN NAIK,On-Notice,2026-04-27,2026-04-27,2026-07-17,Senior Executive - Finance & Accounts,Finance & Accounts,CHENNAI,Permanent
20280,OS7221,'OS7221,Aditya Kishor Jagadale,Live,2026-05-11,2026-05-11,2026-07-17,Executive - Operations,Operations,CHENNAI,Permanent
7566,OS7221,'OS7221,Aditya Kishor Jagadale,Live,2026-05-11,2026-05-11,2026-07-16,Executive - Operations,Operations,CHENNAI,Permanent
17679,OS7221,'OS7221,Aditya Kishor Jagadale,Live,2026-05-11,2026-05-11,2026-07-18,Executive - Operations,Operations,CHENNAI,Permanent
17462,OS8249,'OS8249,NAMRATA RANE,On-Notice,2026-05-11,2026-05-11,2026-07-17,Executive - Operations,Operations,Mumbai HO Andheri,Permanent
7367,OS8249,'OS8249,NAMRATA RANE,On-Notice,2026-05-11,2026-05-11,2026-07-16,Executive - Operations,Operations,Mumbai HO Andheri,Permanent
20090,OS8611,'OS8611,Kunal Patil,On-Notice,2026-05-11,2026-05-11,2026-07-17,Executive - Operations,Operations,CHENNAI,Permanent
7366,OS8611,'OS8611,Kunal Patil,On-Notice,2026-05-11,2026-05-11,2026-07-16,Executive - Operations,Operations,CHENNAI,Permanent
7398,OS9200,'OS9200,Prasanna Rasal,On-Notice,2026-04-27,2026-04-27,2026-07-17,Senior Executive - Finance & Accounts,Finance & Accounts,CHENNAI,Permanent
20123,OS9200,'OS9200,Prasanna Rasal,On-Notice,2026-04-27,2026-04-27,2026-07-16,Senior Executive - Finance & Accounts,Finance & Accounts,CHENNAI,Permanent

Total duplicate rows: 35
Unique duplicated employees: 17

In [26]:
# ==========================================================
# STEP 4: CREATE ONE ROW PER EMPLOYEE
# ==========================================================

# Check whether Created Date is available
print("Created Date exists:",
    "Created Date" in model_base.columns)

# Check duplicate employee codes
print(
    "Rows before deduplication:",
    len(model_base)
)

print(
    "Unique employee codes before deduplication:",
    model_base["_emp_code"].nunique()
)

# ----------------------------------------------------------
# Keep the latest record for each employee
# ----------------------------------------------------------

if "Created Date" in model_base.columns:

    model_base["Created Date"] = pd.to_datetime(
        model_base["Created Date"],
        errors="coerce"
    )

    model_base = (
        model_base
        .sort_values("Created Date")
        .drop_duplicates(
            subset="_emp_code",
            keep="last"
        )
        .copy()
    )

else:

    # If Created Date is not available,
    # keep the last occurrence in Employee Master
    model_base = (
        model_base
        .drop_duplicates(
            subset="_emp_code",
            keep="last"
        )
        .copy()
    )


print("\nRows after deduplication:", len(model_base))

print(
    "Unique employee codes after deduplication:",
    model_base["_emp_code"].nunique()
)

print("\nAttrition distribution after deduplication:")
print(model_base["Attrition"].value_counts())

print("\nAttrition percentage after deduplication:")
print(
    round(model_base["Attrition"].mean() * 100, 2),
    "%"
)

Created Date exists: False
Rows before deduplication: 20486
Unique employee codes before deduplication: 20468

Rows after deduplication: 20468
Unique employee codes after deduplication: 20468

Attrition distribution after deduplication:
Attrition
0    20245
1      223
Name: count, dtype: int64

Attrition percentage after deduplication:
1.09 %

In [27]:
# ==========================================================
# STEP 5: CHECK FEATURE DATASETS BEFORE MERGING
# ==========================================================

datasets = {
    "OT1": overtime_data1,
    "OT2": overtime_data2,
    "OT3": overtime_data3,
    "OT4": overtime_data4,
    "Leave": leave_data,
    "FORM ONE F": form_data
}

for name, df in datasets.items():

    print("\n" + "=" * 60)
    print(name)
    print("=" * 60)

    print("Shape:", df.shape)

    print("Employee code column:")
    
    if "Employee Code" in df.columns:
        print("Employee Code")
        print("Unique:", df["Employee Code"].nunique())

    elif "EMP CODE" in df.columns:
        print("EMP CODE")
        print("Unique:", df["EMP CODE"].nunique())

    else:
        print("NOT FOUND")

    print("\nColumns:")
    print(df.columns.tolist())

============================================================
OT1
============================================================
Shape: (3228, 109)
Employee code column:
EMP CODE
Unique: 3218

Columns:
['EMP CODE', 'EMP NAME', 'BRANCH NAME', 'CITY NAME', 'JOIN DATE', 'LAST WORKING DATE', 'DESIGNATION', 'EMPLOYEE CATEGORY', 'COST CENTRE CODE', 'COST CENTRE NAME', 'SITE CODE', 'SITE NAME', 'PAY CYCLE', '26-JUN-26_CH', '26-JUN-26_NCH', '26-JUN-26_TOT', '27-JUN-26_CH', '27-JUN-26_NCH', '27-JUN-26_TOT', '28-JUN-26_CH', '28-JUN-26_NCH', '28-JUN-26_TOT', '29-JUN-26_CH', '29-JUN-26_NCH', '29-JUN-26_TOT', '30-JUN-26_CH', '30-JUN-26_NCH', '30-JUN-26_TOT', '01-JUL-26_CH', '01-JUL-26_NCH', '01-JUL-26_TOT', '02-JUL-26_CH', '02-JUL-26_NCH', '02-JUL-26_TOT', '03-JUL-26_CH', '03-JUL-26_NCH', '03-JUL-26_TOT', '04-JUL-26_CH', '04-JUL-26_NCH', '04-JUL-26_TOT', '05-JUL-26_CH', '05-JUL-26_NCH', '05-JUL-26_TOT', '06-JUL-26_CH', '06-JUL-26_NCH', '06-JUL-26_TOT', '07-JUL-26_CH', '07-JUL-26_NCH', '07-JUL-26_TOT', '08-JUL-26_CH', '08-JUL-26_NCH', '08-JUL-26_TOT', '09-JUL-26_CH', '09-JUL-26_NCH', '09-JUL-26_TOT', '10-JUL-26_CH', '10-JUL-26_NCH', '10-JUL-26_TOT', '11-JUL-26_CH', '11-JUL-26_NCH', '11-JUL-26_TOT', '12-JUL-26_CH', '12-JUL-26_NCH', '12-JUL-26_TOT', '13-JUL-26_CH', '13-JUL-26_NCH', '13-JUL-26_TOT', '14-JUL-26_CH', '14-JUL-26_NCH', '14-JUL-26_TOT', '15-JUL-26_CH', '15-JUL-26_NCH', '15-JUL-26_TOT', '16-JUL-26_CH', '16-JUL-26_NCH', '16-JUL-26_TOT', '17-JUL-26_CH', '17-JUL-26_NCH', '17-JUL-26_TOT', '18-JUL-26_CH', '18-JUL-26_NCH', '18-JUL-26_TOT', '19-JUL-26_CH', '19-JUL-26_NCH', '19-JUL-26_TOT', '20-JUL-26_CH', '20-JUL-26_NCH', '20-JUL-26_TOT', '21-JUL-26_CH', '21-JUL-26_NCH', '21-JUL-26_TOT', '22-JUL-26_CH', '22-JUL-26_NCH', '22-JUL-26_TOT', '23-JUL-26_CH', '23-JUL-26_NCH', '23-JUL-26_TOT', '24-JUL-26_CH', '24-JUL-26_NCH', '24-JUL-26_TOT', '25-JUL-26_CH', '25-JUL-26_NCH', '25-JUL-26_TOT', 'CHARGEABLE TOTAL', 'NON CHARGEABLE TOTAL', 'TOTAL', ' PF CALCULATION TYPE', ' CHARGEBLEOT FORMULA ', ' NONCHARGEBLE OT FORMULA']

============================================================
OT2
============================================================
Shape: (3228, 19)
Employee code column:
EMP CODE
Unique: 3218

Columns:
['EMP CODE', 'EMP NAME', 'BRANCH NAME', 'CITY NAME', 'JOIN DATE', 'LAST WORKING DATE', 'DESIGNATION', 'EMPLOYEE CATEGORY', 'COST CENTRE CODE', 'COST CENTRE NAME', 'SITE CODE', 'SITE NAME', 'PAY CYCLE', 'CHARGEABLE TOTAL', 'NON CHARGEABLE TOTAL', 'TOTAL', ' PF CALCULATION TYPE', ' CHARGEBLEOT FORMULA ', ' NONCHARGEBLE OT FORMULA']

============================================================
OT3
============================================================
Shape: (4783, 19)
Employee code column:
EMP CODE
Unique: 4781

Columns:
['EMP CODE', 'EMP NAME', 'BRANCH NAME', 'CITY NAME', 'JOIN DATE', 'LAST WORKING DATE', 'DESIGNATION', 'EMPLOYEE CATEGORY', 'COST CENTRE CODE', 'COST CENTRE NAME', 'SITE CODE', 'SITE NAME', 'PAY CYCLE', 'CHARGEABLE TOTAL', 'NON CHARGEABLE TOTAL', 'TOTAL', ' PF CALCULATION TYPE', ' CHARGEBLEOT FORMULA ', ' NONCHARGEBLE OT FORMULA']

============================================================
OT4
============================================================
Shape: (4783, 112)
Employee code column:
EMP CODE
Unique: 4781

Columns:
['EMP CODE', 'EMP NAME', 'BRANCH NAME', 'CITY NAME', 'JOIN DATE', 'LAST WORKING DATE', 'DESIGNATION', 'EMPLOYEE CATEGORY', 'COST CENTRE CODE', 'COST CENTRE NAME', 'SITE CODE', 'SITE NAME', 'PAY CYCLE', '01-JUL-26_CH', '01-JUL-26_NCH', '01-JUL-26_TOT', '02-JUL-26_CH', '02-JUL-26_NCH', '02-JUL-26_TOT', '03-JUL-26_CH', '03-JUL-26_NCH', '03-JUL-26_TOT', '04-JUL-26_CH', '04-JUL-26_NCH', '04-JUL-26_TOT', '05-JUL-26_CH', '05-JUL-26_NCH', '05-JUL-26_TOT', '06-JUL-26_CH', '06-JUL-26_NCH', '06-JUL-26_TOT', '07-JUL-26_CH', '07-JUL-26_NCH', '07-JUL-26_TOT', '08-JUL-26_CH', '08-JUL-26_NCH', '08-JUL-26_TOT', '09-JUL-26_CH', '09-JUL-26_NCH', '09-JUL-26_TOT', '10-JUL-26_CH', '10-JUL-26_NCH', '10-JUL-26_TOT', '11-JUL-26_CH', '11-JUL-26_NCH', '11-JUL-26_TOT', '12-JUL-26_CH', '12-JUL-26_NCH', '12-JUL-26_TOT', '13-JUL-26_CH', '13-JUL-26_NCH', '13-JUL-26_TOT', '14-JUL-26_CH', '14-JUL-26_NCH', '14-JUL-26_TOT', '15-JUL-26_CH', '15-JUL-26_NCH', '15-JUL-26_TOT', '16-JUL-26_CH', '16-JUL-26_NCH', '16-JUL-26_TOT', '17-JUL-26_CH', '17-JUL-26_NCH', '17-JUL-26_TOT', '18-JUL-26_CH', '18-JUL-26_NCH', '18-JUL-26_TOT', '19-JUL-26_CH', '19-JUL-26_NCH', '19-JUL-26_TOT', '20-JUL-26_CH', '20-JUL-26_NCH', '20-JUL-26_TOT', '21-JUL-26_CH', '21-JUL-26_NCH', '21-JUL-26_TOT', '22-JUL-26_CH', '22-JUL-26_NCH', '22-JUL-26_TOT', '23-JUL-26_CH', '23-JUL-26_NCH', '23-JUL-26_TOT', '24-JUL-26_CH', '24-JUL-26_NCH', '24-JUL-26_TOT', '25-JUL-26_CH', '25-JUL-26_NCH', '25-JUL-26_TOT', '26-JUL-26_CH', '26-JUL-26_NCH', '26-JUL-26_TOT', '27-JUL-26_CH', '27-JUL-26_NCH', '27-JUL-26_TOT', '28-JUL-26_CH', '28-JUL-26_NCH', '28-JUL-26_TOT', '29-JUL-26_CH', '29-JUL-26_NCH', '29-JUL-26_TOT', '30-JUL-26_CH', '30-JUL-26_NCH', '30-JUL-26_TOT', '31-JUL-26_CH', '31-JUL-26_NCH', '31-JUL-26_TOT', 'CHARGEABLE TOTAL', 'NON CHARGEABLE TOTAL', 'TOTAL', ' PF CALCULATION TYPE', ' CHARGEBLEOT FORMULA ', ' NONCHARGEBLE OT FORMULA']

============================================================
Leave
============================================================
Shape: (31523, 28)
Employee code column:
Employee Code
Unique: 25952

Columns:
['Group', 'Entity Name', 'Employee Code', 'Employee Name', 'Date of joining', 'Department', 'Grade', 'Designation', 'Leave Type', 'Reporting Manager', 'City Name', 'Branch', 'State Name', 'Cost Center', 'Employee Status', 'Opening Balance (A)', 'Accrued Till Date (B)', 'Consumed Till Date (C)', 'Availed Adjustment (D)', 'Lapse (E)', 'Balance Till Date (F) = A+B-C+D-E', 'Future Dated Approved Leave (G)', 'Balance Including Future Dated Approved Leave H (F-G)', 'Leave Encashment(I)', 'Carry Forward To Next Year J= (H-I)', 'Leave Year Start Date', 'Leave Year End Date', 'Accounting Year']

============================================================
FORM ONE F
============================================================
Shape: (9762, 197)
Employee code column:
Employee Code
Unique: 7890

Columns:
['Employee Status', 'Soft Joining ID', 'Employee Verify Type', 'Onboarding Date', 'Employee Code', 'Employee Name', 'Date Of Joined', 'Date Of Birth', 'Designation', 'Cost Center', 'Gender', 'Marital Status', 'Contact No', 'Emergency No', 'Location', 'Region Name', 'Present Address', 'Permanent Address', 'Site Name', 'Operation Manager', 'Client Verticle', 'Onboarding User', 'PAN Number', 'AADHAR Number', 'ESIC No', 'UAN Number', 'Account No', 'Bank Name', 'IFSC Code', 'Religion', 'Blood Group', 'Nominee Name', 'Relation', 'Fathers Name / Husband Name', 'Higher Education', 'Created Date', 'ABRY BENEFIT', 'ACCOR MEAL VOUCHER', 'ADMIN COST TRAINING & CONTINGENCY COST', 'ANNUAL BONUS', 'ATTENDANCE ALLOWANCE', 'ATTENDANCE INCENTIVE', 'ATTIRE REIMBURSEMENT', 'BASIC', 'BONUS', 'BOOKS AND PERIODICALS', 'CANTEEN DEDUCTION', 'CAR REIMBURSEMENT', 'CASH ALLOWANCE', 'CHILD ALLOWANCE', 'CITY COMPENSATORY ALLOW', 'CO CNTR TO EDLI ADMN CHARGE', 'CO CNTR TO EDLI CHARGES', 'CO CNTR TO PF ADMN CHARGES', 'COMMUNICATION ALLOWANCE', 'CONVEYANCE ALLOWANCE', 'CONVEYANCE ALLOWANCE OLD', 'CREDIT SOC RECOVERY', 'CUSTOMISED POOL', 'CUSTOMIZED POOL', 'DAILY BASIC', 'DAILY BONUS', 'DAILY CITY COMP ALLW', 'DAILY CONVEYANCE', 'DAILY CUSTOMIZED POOL', 'DAILY DEARNESS ALLOW', 'DAILY EDUCATION ALW', 'DAILY FOOD ALLOWANE', 'DAILY HRA', 'DAILY LEAVE ENCASHMENT', 'DAILY LUNCH', 'DAILY MEDICAL ALLOWANCE', 'DAILY OTHER ALW', 'DAILY PERSONAL ALLOWANCE', 'DAILY SITE ALLOWANCE', 'DAILY SPECIAL ALLWN', 'DAILY TRANSPORT ALLOW', 'DAILY WASHING', 'DEARNESS ALLOWANCE', 'DISABLED DEPENDANT ALLOWANCE', 'DLSTIPEND', 'DRIVER', 'EDUCATION ALLOWANCE', 'EDUCATION LOAN DEDUCTION', 'EMPLOYEE OF THE MONTH', 'EMPLOYEE REFERRAL', 'EMPLOYER CONTRI TO NPS', 'EMPLOYER CONTRI TO PF', 'EMPLOYER CONTRIBUT PENSION', 'ENTERTAINMENT ALLOWANCE', 'ESIC', 'ESIC EMPLOYER CONTRI', 'EXECUTIVE ALLOWANCE', 'EXGRATIA', 'EXGRATIA A', 'Esic', 'FESTIVAL ADVANCE', 'FESTIVAL GIFT', 'FLEXY PAY', 'FOOD ALLOWANCE', 'FOOD COUPON', 'GRATUITY', 'HEAD INSURANCE ADMIN', 'HOME LEAVE ALLOWANCE', 'HOUSE RENT ALLOWANCE', 'INCENTIVE ONE', 'INCOME TAX', 'INSURANCE', 'INSURANCE FUND', 'INTEREST LOAN', 'JOINING BONUS', 'L T EXPENSE TAXABLE OLD', 'L T EXPENSE TAXFREE', 'LABOUR WELFARE FUND', 'LEAVE', 'LEAVE ENCASHMENT', 'LEAVE ENCASHMENT TAXABLE', 'LEAVE PAYMENT', 'LEAVE TRAVEL ALLOWANCE', 'LEAVEPAY', 'LIC DEDUCATION', 'LOAN DEDUCTION', 'LONG', 'LONG SERVICE AWARD', 'LOYALITY BONUS', 'LWF(Employer)', 'MANDATORY PROVIDENT FUND EES OLD', 'MEAL DEDUCTION', 'MEAL VOUCHER', 'MEDICAL', 'MEDICAL ALLOWANCE', 'MEDICAL REIMBURSEMENT', 'MOBILE ALLOWANCE', 'MOBILE DEDUCTION', 'MOBILE DEVICE REIMBURSEMENT', 'NFH', 'NOTICE PAY', 'NOTICE PAY PAYMENT', 'NOTICE PAY RECOVERY', 'NPS DEDUCTION', 'NPS EMPLOYER CONTRIBUTION', 'OTHER ALLOWANCE', 'OTHER DEDUCTION', 'OTHER EARNING', 'OTHER PAYMENT', 'OTHER RECOVERY', 'OVERTIME', 'OVERTIME OLD', 'PCC DEDUCTION', 'PD CARD', 'PERFORMANCE BASED BONUS', 'PERFORMANCE BONUS', 'PERFORMANCE LINKED PAY', 'PERSONAL LOAN', 'PERSONAL PAY', 'PF ADMIN', 'PF LOAN', 'PRINCIPLE LOAN', 'PROF PURSUIT REIMBURSEMENT', 'PROFESSIONAL ALLOWANCE', 'PROFESSIONAL TAX', 'PUBLIC HOLIDAY', 'Patrocard', 'Provident Fund', 'REFERRAL INCENTIVE', 'RELOCATION ALLOWANCE', 'RENT DEDUCTION', 'RETENTION BONUS', 'RETIREMENT PLAN DED', 'RETRECHMENT ALLLOWANCE', 'SALARY ADVANCE', 'SINGLE PARENT ALLOWANCE', 'SITE ALLOWANCE', 'SITE HOLIDAY', 'SODEXO GIFT VOUCHER', 'SPECIAL ALLOWANCE', 'STAFF LOAN', 'STATUTORY BONUS', 'STATUTORY P F', 'STIPEND', 'STIPEND OLD', 'SUPERVISORY ALLOWANCE', 'TELEPHONE REIMBURSEMENT', 'TRANSPORT ALLOWANCE', 'TRANSPORT DEDUCTION', 'UNIFORM AND SHOES', 'UNIFORM DEPOSITE REFUND', 'UTILITY ALLOWANCE', 'VEHICAL ALLOWANCE', 'VEHICLE ALLOWANCE', 'VERD', 'VOLUNTARY PF', 'WASHING ALLOWANCE', 'WPC', 'WPC INCENTIVE', 'YLY LEAVE ENCASHMENT TAXABLE', 'Monthly Gross Salary']

In [28]:
# ==========================================================
# STEP 6: CREATE EMPLOYEE-LEVEL OT FEATURES
# ==========================================================

def create_ot_features(ot_df, prefix):
    
    df = ot_df.copy()

    # Normalize employee code
    df["_emp_code"] = normalize_emp_code(df["EMP CODE"])

    # Identify daily OT columns
    chargeable_cols = [
        col for col in df.columns
        if col.endswith("_CH")
    ]

    non_chargeable_cols = [
        col for col in df.columns
        if col.endswith("_NCH")
    ]

    total_cols = [
        col for col in df.columns
        if col.endswith("_TOT")
    ]

    # Convert OT columns to numeric
    for col in chargeable_cols + non_chargeable_cols + total_cols:
        df[col] = pd.to_numeric(df[col], errors="coerce").fillna(0)

    # Employee-level features
    features = pd.DataFrame({
        "_emp_code": df["_emp_code"],

        f"{prefix}_Chargeable_OT":
            df[chargeable_cols].sum(axis=1),

        f"{prefix}_NonChargeable_OT":
            df[non_chargeable_cols].sum(axis=1),

        f"{prefix}_Total_OT":
            df[total_cols].sum(axis=1),

        f"{prefix}_OT_Days":
            (df[total_cols] > 0).sum(axis=1),

        f"{prefix}_Avg_Daily_OT":
            df[total_cols].mean(axis=1),

        f"{prefix}_Max_Daily_OT":
            df[total_cols].max(axis=1)
    })

    # In case the source has multiple rows for the same employee
    features = (
        features
        .groupby("_emp_code", as_index=False)
        .agg({
            f"{prefix}_Chargeable_OT": "sum",
            f"{prefix}_NonChargeable_OT": "sum",
            f"{prefix}_Total_OT": "sum",
            f"{prefix}_OT_Days": "sum",
            f"{prefix}_Avg_Daily_OT": "mean",
            f"{prefix}_Max_Daily_OT": "max"
        })
    )

    return features


# ----------------------------------------------------------
# Create features from OT1
# ----------------------------------------------------------

ot1_features = create_ot_features(
    overtime_data1,
    "OT1"
)


# ----------------------------------------------------------
# Create features from OT4
# ----------------------------------------------------------

ot4_features = create_ot_features(
    overtime_data4,
    "OT4"
)



print("OT1 features shape:", ot1_features.shape)
print("OT4 features shape:", ot4_features.shape)

print("\nOT1 features:")
print(ot1_features.head())

print("\nOT4 features:")
print(ot4_features.head())

OT1 features shape: (3218, 7)
OT4 features shape: (4781, 7)

OT1 features:
  _emp_code  OT1_Chargeable_OT  OT1_NonChargeable_OT  OT1_Total_OT  \
0     11168                0.0                 104.0         104.0
1     11603                0.0                   0.0           0.0
2     11625              104.0                   0.0         104.0
3     14000                0.0                  56.0          56.0
4     16145                6.0                   0.0           6.0

   OT1_OT_Days  OT1_Avg_Daily_OT  OT1_Max_Daily_OT
0           13          3.466667               8.0
1            0          0.000000               0.0
2           13          3.466667               8.0
3            7          1.866667               8.0
4            2          0.200000               3.0

OT4 features:
  _emp_code  OT4_Chargeable_OT  OT4_NonChargeable_OT  OT4_Total_OT  \
0      1009                4.0                   0.0           4.0
1     13622               12.0                   0.0          12.0
2     13971                0.0                   0.0           0.0
3     15126               37.0                   0.0          37.0
4     16867                0.0                  10.0          10.0

   OT4_OT_Days  OT4_Avg_Daily_OT  OT4_Max_Daily_OT
0            1          0.129032               4.0
1            4          0.387097               4.0
2            0          0.000000               0.0
3            9          1.193548               8.0
4            1          0.322581              10.0

In [29]:
# ==========================================================
# STEP 7: CREATE EMPLOYEE-LEVEL LEAVE FEATURES
# ==========================================================

leave = leave_data.copy()

# Normalize employee code
leave["_emp_code"] = normalize_emp_code(
    leave["Employee Code"]
)

# Convert important leave columns to numeric
leave_numeric_cols = [
    "Opening Balance (A)",
    "Accrued Till Date (B)",
    "Consumed Till Date (C)",
    "Availed Adjustment (D)",
    "Lapse (E)",
    "Balance Till Date (F) = A+B-C+D-E",
    "Future Dated Approved Leave (G)",
    "Balance Including Future Dated Approved Leave H (F-G)",
    "Leave Encashment(I)",
    "Carry Forward To Next Year J= (H-I)"
]

for col in leave_numeric_cols:
    leave[col] = pd.to_numeric(
        leave[col],
        errors="coerce"
    ).fillna(0)


# ----------------------------------------------------------
# Create employee-level leave features
# ----------------------------------------------------------

leave_features = (
    leave
    .groupby("_emp_code")
    .agg(
        Leave_Opening_Balance=(
            "Opening Balance (A)", "sum"
        ),

        Leave_Accrued=(
            "Accrued Till Date (B)", "sum"
        ),

        Leave_Consumed=(
            "Consumed Till Date (C)", "sum"
        ),

        Leave_Adjustment=(
            "Availed Adjustment (D)", "sum"
        ),

        Leave_Lapse=(
            "Lapse (E)", "sum"
        ),

        Leave_Balance=(
            "Balance Till Date (F) = A+B-C+D-E", "sum"
        ),

        Leave_Future_Approved=(
            "Future Dated Approved Leave (G)", "sum"
        ),

        Leave_Balance_After_Future=(
            "Balance Including Future Dated Approved Leave H (F-G)", "sum"
        ),

        Leave_Encashment=(
            "Leave Encashment(I)", "sum"
        ),

        Leave_Carry_Forward=(
            "Carry Forward To Next Year J= (H-I)", "sum"
        ),

        Leave_Record_Count=(
            "Leave Type", "count"
        ),

        Leave_Type_Count=(
            "Leave Type", "nunique"
        )
    )
    .reset_index()
)


print("Leave features shape:", leave_features.shape)

print("\nUnique employees in leave features:")
print(leave_features["_emp_code"].nunique())

print("\nLeave features:")
print(leave_features.head())

Leave features shape: (25952, 13)

Unique employees in leave features:
25952

Leave features:
  _emp_code  Leave_Opening_Balance  Leave_Accrued  Leave_Consumed  \
0     00026                    0.0           8.67             0.0
1     00349                    0.0           8.32             0.0
2     00669                    0.0           4.33             0.0
3     01009                    0.0           8.67             0.0
4     02044                    0.0           7.53             0.0

   Leave_Adjustment  Leave_Lapse  Leave_Balance  Leave_Future_Approved  \
0                 0            0           8.67                    0.0
1                 0            0           8.32                    0.0
2                 0            0           4.33                    0.0
3                 0            0           8.67                    0.0
4                 0            0           7.53                    0.0

   Leave_Balance_After_Future  Leave_Encashment  Leave_Carry_Forward  \
0                        8.67                 0                 8.67
1                        8.32                 0                 8.32
2                        4.33                 0                 4.33
3                        8.67                 0                 8.67
4                        7.53                 0                 7.53

   Leave_Record_Count  Leave_Type_Count
0                   1                 1
1                   1                 1
2                   1                 1
3                   1                 1
4                   1                 1

In [30]:
# ==========================================================
# STEP 8: PREPARE FORM ONE F
# ==========================================================

form = form_data.copy()

# Normalize employee code
form["_emp_code"] = normalize_emp_code(
    form["Employee Code"]
)

# Convert Created Date
form["Created Date"] = pd.to_datetime(
    form["Created Date"],
    errors="coerce"
)

print("Form data shape:", form.shape)
print("Unique employees:", form["_emp_code"].nunique())

print("\nDuplicate employee codes:")
print(
    form["_emp_code"]
    .value_counts()
    .loc[lambda x: x > 1]
    .head(20)
)

Form data shape: (9762, 198)
Unique employees: 7889

Duplicate employee codes:
Series([], Name: count, dtype: Int64)

C:\Users\veena.sharma\AppData\Local\Temp\ipykernel_3824\262546187.py:13: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  form["Created Date"] = pd.to_datetime(

In [31]:
# ==========================================================
# STEP 9: CREATE FORM / SALARY FEATURES
# ==========================================================

form_features = form[
    [
        "_emp_code",
        "Employee Status",
        "Designation",
        "Cost Center",
        "Gender",
        "Marital Status",
        "Location",
        "Region Name",
        "Site Name",
        "Client Verticle",
        "Date Of Joined",
        "Created Date",
        "Monthly Gross Salary"
    ]
].copy()


# ----------------------------------------------------------
# Convert date columns
# ----------------------------------------------------------

form_features["Date Of Joined"] = pd.to_datetime(
    form_features["Date Of Joined"],
    errors="coerce"
)

form_features["Created Date"] = pd.to_datetime(
    form_features["Created Date"],
    errors="coerce"
)


# ----------------------------------------------------------
# Convert salary to numeric
# ----------------------------------------------------------

form_features["Monthly Gross Salary"] = pd.to_numeric(
    form_features["Monthly Gross Salary"],
    errors="coerce"
)


# ----------------------------------------------------------
# Create salary-related feature
# ----------------------------------------------------------

form_features["Annual_Gross_Salary"] = (
    form_features["Monthly Gross Salary"] * 12
)


# ----------------------------------------------------------
# Create tenure feature
# ----------------------------------------------------------

reference_date = pd.Timestamp.today().normalize()

form_features["Tenure_Days"] = (
    reference_date - form_features["Date Of Joined"]
).dt.days

form_features["Tenure_Years"] = (
    form_features["Tenure_Days"] / 365.25
)


print("Form features shape:", form_features.shape)

print("\nUnique employees:")
print(form_features["_emp_code"].nunique())

print("\nForm feature columns:")
print(form_features.columns.tolist())

print("\nSample:")
print(form_features.head())

Form features shape: (9762, 16)

Unique employees:
7889

Form feature columns:
['_emp_code', 'Employee Status', 'Designation', 'Cost Center', 'Gender', 'Marital Status', 'Location', 'Region Name', 'Site Name', 'Client Verticle', 'Date Of Joined', 'Created Date', 'Monthly Gross Salary', 'Annual_Gross_Salary', 'Tenure_Days', 'Tenure_Years']

Sample:
     _emp_code Employee Status                           Designation  \
0         <NA>              No  SR. Executive - Business Development
1  PSIPL500001              No            Executive-Customer Service
2         <NA>              No                         SR.Supervisor
3         <NA>              No  SR. Executive - Business Development
4         <NA>              No                    Manager - Taxation

                          Cost Center  Gender Marital Status Location  \
0  IFMS BASE OFFICE-BANGALORE-FINANCE    Male         Single   Mumbai
1  IFMS BASE OFFICE-BANGALORE-FINANCE    Male         Single   Mumbai
2  IFMS BASE OFFICE-BANGALORE-FINANCE    Male         Single   Mumbai
3    IFMS BASE OFFICE-BANGALORE-ADMIN    Male         Single   Mumbai
4                                 NaN  Female         Single      NaN

  Region Name                           Site Name Client Verticle  \
0        Base  IFMS BASE OFFICE-BANGALORE-FINANCE    Base - South
1        Base  IFMS BASE OFFICE-BANGALORE-FINANCE    Base - South
2        Base  IFMS BASE OFFICE-BANGALORE-FINANCE    Base - South
3        Base    IFMS BASE OFFICE-BANGALORE-ADMIN    Base - South
4         NaN                                 NaN             NaN

  Date Of Joined Created Date  Monthly Gross Salary  Annual_Gross_Salary  \
0     2026-01-19   2026-01-12               31916.0             382992.0
1     2026-01-19   2026-01-13               31916.0             382992.0
2     2026-01-19   2026-01-13               31916.0             382992.0
3     2026-01-19   2026-01-13               25584.0             307008.0
4     2026-01-06   2026-01-13                   0.0                  0.0

   Tenure_Days  Tenure_Years
0          203      0.555784
1          203      0.555784
2          203      0.555784
3          203      0.555784
4          216      0.591376

C:\Users\veena.sharma\AppData\Local\Temp\ipykernel_3824\2426863151.py:28: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  form_features["Date Of Joined"] = pd.to_datetime(

In [32]:
# ==========================================================
# STEP 9A: CHECK FORM EMPLOYEE CODE QUALITY
# ==========================================================

print("Total form rows:", len(form_features))

print(
    "Missing employee codes:",
    form_features["_emp_code"].isna().sum()
)

print(
    "Non-missing employee codes:",
    form_features["_emp_code"].notna().sum()
)

print(
    "Unique non-missing employee codes:",
    form_features["_emp_code"].dropna().nunique()
)

print("\nDuplicate non-missing employee codes:")

form_duplicates = (
    form_features["_emp_code"]
    .dropna()
    .value_counts()
)

print(
    form_duplicates[
        form_duplicates > 1
    ].head(20)
)

print(
    "\nNumber of duplicated employee codes:",
    (form_duplicates > 1).sum()
)

Total form rows: 9762
Missing employee codes: 1873
Non-missing employee codes: 7889
Unique non-missing employee codes: 7889

Duplicate non-missing employee codes:
Series([], Name: count, dtype: Int64)

Number of duplicated employee codes: 0

In [33]:
# ==========================================================
# STEP 10: KEEP ONLY MATCHABLE FORM EMPLOYEES
# ==========================================================

form_features_clean = form_features[
    form_features["_emp_code"].notna()
].copy()

print("Form features before cleaning:", len(form_features))
print("Form features after cleaning:", len(form_features_clean))

print(
    "Unique employee codes:",
    form_features_clean["_emp_code"].nunique()
)

print(
    "Duplicate employee codes:",
    form_features_clean["_emp_code"].duplicated().sum()
)

Form features before cleaning: 9762
Form features after cleaning: 7889
Unique employee codes: 7889
Duplicate employee codes: 0

In [34]:
# ==========================================================
# STEP 11: CHECK FORM ↔ EMPLOYEE MASTER MATCHING
# ==========================================================

model_codes = set(
    model_base["_emp_code"].dropna()
)

form_codes = set(
    form_features_clean["_emp_code"].dropna()
)

matched_codes = form_codes.intersection(model_codes)
unmatched_codes = form_codes - model_codes

print("Unique employees in model_base:", len(model_codes))
print("Unique employees in Form:", len(form_codes))

print("\nMatched Form employees:", len(matched_codes))
print("Unmatched Form employees:", len(unmatched_codes))

print(
    "\nForm match percentage:",
    round(len(matched_codes) / len(form_codes) * 100, 2),
    "%"
)

Unique employees in model_base: 20468
Unique employees in Form: 7889

Matched Form employees: 6645
Unmatched Form employees: 1244

Form match percentage: 84.23 %

In [35]:
# ==========================================================
# STEP 12: MERGE FORM FEATURES INTO MODEL BASE
# ==========================================================

# Keep only the useful Form feature columns
form_merge = form_features_clean.copy()

# Make sure employee code is the same type
form_merge["_emp_code"] = form_merge["_emp_code"].astype("string")

# Avoid duplicate employee-code columns from previous merges
form_merge = form_merge.drop_duplicates(
    subset="_emp_code",
    keep="first"
)

# Merge Form features
model_base = model_base.merge(
    form_merge,
    on="_emp_code",
    how="left",
    suffixes=("", "_form")
)

print("Model base shape after Form merge:", model_base.shape)

print("\nForm feature coverage:")
print(
    model_base[
        "Monthly Gross Salary"
    ].notna().sum()
)

print(
    "Employees with Form data:",
    model_base["Monthly Gross Salary"].notna().sum()
)

print(
    "Employees without Form data:",
    model_base["Monthly Gross Salary"].isna().sum()
)

Model base shape after Form merge: (20468, 110)

Form feature coverage:
6645
Employees with Form data: 6645
Employees without Form data: 13823

In [36]:
# ==========================================================
# STEP 13A: CREATE OT2 AND OT3 FEATURES
# ==========================================================

def create_ot_summary_features(df, prefix):
    temp = df.copy()

    # Normalize employee code
    temp["_emp_code"] = normalize_emp_code(temp["EMP CODE"])

    # Convert OT columns to numeric
    for col in ["CHARGEABLE TOTAL", "NON CHARGEABLE TOTAL", "TOTAL"]:
        temp[col] = pd.to_numeric(temp[col], errors="coerce").fillna(0)

    # Aggregate at employee level
    features = (
        temp.groupby("_emp_code", dropna=True)
        .agg(
            **{
                f"{prefix}_Chargeable_OT": ("CHARGEABLE TOTAL", "sum"),
                f"{prefix}_NonChargeable_OT": ("NON CHARGEABLE TOTAL", "sum"),
                f"{prefix}_Total_OT": ("TOTAL", "sum"),
            }
        )
        .reset_index()
    )

    return features


# Create OT2 features
ot2_features = create_ot_summary_features(
    overtime_data2,
    "OT2"
)

# Create OT3 features
ot3_features = create_ot_summary_features(
    overtime_data3,
    "OT3"
)


print("OT2 features shape:", ot2_features.shape)
print("OT3 features shape:", ot3_features.shape)

print("\nOT2 unique employees:",
    ot2_features["_emp_code"].nunique())

print("OT3 unique employees:",
    ot3_features["_emp_code"].nunique())

print("\nOT2 features:")
print(ot2_features.head())

print("\nOT3 features:")
print(ot3_features.head())

OT2 features shape: (3218, 4)
OT3 features shape: (4781, 4)

OT2 unique employees: 3218
OT3 unique employees: 4781

OT2 features:
  _emp_code  OT2_Chargeable_OT  OT2_NonChargeable_OT  OT2_Total_OT
0     11168                0.0                 104.0         104.0
1     11603                0.0                   0.0           0.0
2     11625              104.0                   0.0         104.0
3     14000                0.0                  56.0          56.0
4     16145                6.0                   0.0           6.0

OT3 features:
  _emp_code  OT3_Chargeable_OT  OT3_NonChargeable_OT  OT3_Total_OT
0     00026               17.0                   0.0          17.0
1     01009                4.0                   0.0           4.0
2     02044                0.0                   0.0           0.0
3     05213                0.0                  21.0          21.0
4     05568                0.0                  15.0          15.0

In [37]:

# ==========================================================
# STEP 13: CHECK OT FEATURE DATASETS
# ==========================================================

print("OT1 features:", ot1_features.shape)
print("OT2 features:", ot2_features.shape)
print("OT3 features:", ot3_features.shape)
print("OT4 features:", ot4_features.shape)

print("\nUnique employees:")
print("OT1:", ot1_features["_emp_code"].nunique())
print("OT2:", ot2_features["_emp_code"].nunique())
print("OT3:", ot3_features["_emp_code"].nunique())
print("OT4:", ot4_features["_emp_code"].nunique())

OT1 features: (3218, 7)
OT2 features: (3218, 4)
OT3 features: (4781, 4)
OT4 features: (4781, 7)

Unique employees:
OT1: 3218
OT2: 3218
OT3: 4781
OT4: 4781

In [38]:
# ==========================================================
# STEP 14: MERGE ALL OT FEATURES INTO MODEL BASE
# ==========================================================

# Make sure all employee codes have the same format
for df in [ot1_features, ot2_features, ot3_features, ot4_features]:
    df["_emp_code"] = normalize_emp_code(df["_emp_code"])


# Merge OT1
model_base = model_base.merge(
    ot1_features,
    on="_emp_code",
    how="left",
    validate="one_to_one"
)

# Merge OT2
model_base = model_base.merge(
    ot2_features,
    on="_emp_code",
    how="left",
    validate="one_to_one"
)

# Merge OT3
model_base = model_base.merge(
    ot3_features,
    on="_emp_code",
    how="left",
    validate="one_to_one"
)

# Merge OT4
model_base = model_base.merge(
    ot4_features,
    on="_emp_code",
    how="left",
    validate="one_to_one"
)


print("Model base shape after OT merge:", model_base.shape)

print("\nEmployees with OT1 data:",
      model_base["OT1_Total_OT"].notna().sum())

print("Employees with OT2 data:",
      model_base["OT2_Total_OT"].notna().sum())

print("Employees with OT3 data:",
      model_base["OT3_Total_OT"].notna().sum())

print("Employees with OT4 data:",
      model_base["OT4_Total_OT"].notna().sum())

print("\nEmployees without OT1 data:",
      model_base["OT1_Total_OT"].isna().sum())

print("Employees without OT3 data:",
      model_base["OT3_Total_OT"].isna().sum())

Model base shape after OT merge: (20468, 128)

Employees with OT1 data: 3206
Employees with OT2 data: 3206
Employees with OT3 data: 4766
Employees with OT4 data: 4761

Employees without OT1 data: 17262
Employees without OT3 data: 15702

In [39]:
# ==========================================================
# STEP 15: MERGE LEAVE FEATURES INTO MODEL BASE
# ==========================================================

# Make sure employee codes are normalized
leave_features["_emp_code"] = normalize_emp_code(
    leave_features["_emp_code"]
)

# Check duplicate employee codes before merge
print(
    "Duplicate employee codes in leave_features:",
    leave_features["_emp_code"].duplicated().sum()
)

# Merge Leave features
model_base = model_base.merge(
    leave_features,
    on="_emp_code",
    how="left",
    validate="one_to_one"
)

print("\nModel base shape after Leave merge:", model_base.shape)

print(
    "\nEmployees with Leave data:",
    model_base["Leave_Record_Count"].notna().sum()
)

print(
    "Employees without Leave data:",
    model_base["Leave_Record_Count"].isna().sum()
)

Duplicate employee codes in leave_features: 0

Model base shape after Leave merge: (20468, 140)

Employees with Leave data: 18332
Employees without Leave data: 2136

In [40]:
# ==========================================================
# STEP 16: CHECK ATTRITION TARGET
# ==========================================================

print("Model base shape:", model_base.shape)

print("\nAttrition column exists:",
      "Attrition" in model_base.columns)

if "Attrition" in model_base.columns:
    print("\nAttrition distribution:")
    print(model_base["Attrition"].value_counts(dropna=False))

    print("\nAttrition percentage:")
    print(
        round(
            model_base["Attrition"].mean() * 100,
            2
        ),
        "%"
    )

    print("\nMissing Attrition:")
    print(model_base["Attrition"].isna().sum())

Model base shape: (20468, 140)

Attrition column exists: True

Attrition distribution:
Attrition
0    20245
1      223
Name: count, dtype: int64

Attrition percentage:
1.09 %

Missing Attrition:
0

In [41]:
# ==========================================================
# STEP 17: INSPECT MODEL FEATURES
# ==========================================================

print("Total columns:", len(model_base.columns))

for i, col in enumerate(model_base.columns, 1):
    print(f"{i:3}. {col}")

Total columns: 140
  1. Group
  2. Company Name
  3. Employee Code
  4. Title
  5. First Name
  6. Middle Name
  7. Last Name
  8. Employee Name
  9. Gender
 10. Nationality
 11. Official Email Address
 12. Personal Email Address
 13. Resident Type
 14. Marital Status
 15. City Name
 16. State Name
 17. Branch
 18. Site Branch
 19. Division
 20. Designation
 21. Department
 22. Sub Department
 23. Cost Center
 24. Site Cost Center
 25. Site Name
 26. Grade
 27. Band
 28. Reason for Requirement
 29. Employee Category
 30. Employee Status
 31. Reporting Manager Code
 32. Reporting Manager Name
 33. Skip Level Manager Code
 34. Skip Level Manager
 35. Actual Join Date
 36. Group Join Date
 37. Resignation Date
 38. Year Of Service (Current DOJ)
 39. Year of Service (Group DOJ)
 40. Physical Disability
 41. Point of Hire
 42. Point of Repatriation
 43. ESIC Flag
 44. ESIC Number
 45. PF Applicable
 46. PF Type
 47. PF Number
 48. UAN Number
 49. FNF Settlement Date
 50. Probation Status
 51. Confirmation Date
 52. Source of Hire
 53. Preferred Name
 54. Dual Nationality
 55. Religion
 56. Agreement type
 57. Effective Start Date
 58. Effective End Date
 59. Employee Air Ticket
 60. Air Ticket Class
 61. Air Ticket frequency
 62. Blood Group
 63. Group Medical Insurance
 64. Confidential Profile Flag
 65. Confidential Profile
 66. Conf. Date (Period Master)
 67. 2nd Nationality
 68. Employer Notice Period
 69. Bank Name
 70. Movement Type
 71. PAN Number
 72. Aadhar Card No
 73. Account Number
 74. IFSC Code
 75. Personal Mobile Number
 76. Emergency Contact Number
 77. Father Name
 78. Birth Date
 79. Last Payable Days
 80. Last Working Date
 81. Cost Code
 82. Profit Code
 83. Client Vertical
 84. Permanent Address
 85. Current Address
 86. Correspondence Address
 87. Leave Status
 88. Resident
 89. Wage Type
 90. TAX Regime
 91. Uniform Deduction
 92. Process Name
 93. Employee_Code_Clean
 94. _emp_code
 95. Attrition
 96. Employee Status_form
 97. Designation_form
 98. Cost Center_form
 99. Gender_form
100. Marital Status_form
101. Location
102. Region Name
103. Site Name_form
104. Client Verticle
105. Date Of Joined
106. Created Date
107. Monthly Gross Salary
108. Annual_Gross_Salary
109. Tenure_Days
110. Tenure_Years
111. OT1_Chargeable_OT
112. OT1_NonChargeable_OT
113. OT1_Total_OT
114. OT1_OT_Days
115. OT1_Avg_Daily_OT
116. OT1_Max_Daily_OT
117. OT2_Chargeable_OT
118. OT2_NonChargeable_OT
119. OT2_Total_OT
120. OT3_Chargeable_OT
121. OT3_NonChargeable_OT
122. OT3_Total_OT
123. OT4_Chargeable_OT
124. OT4_NonChargeable_OT
125. OT4_Total_OT
126. OT4_OT_Days
127. OT4_Avg_Daily_OT
128. OT4_Max_Daily_OT
129. Leave_Opening_Balance
130. Leave_Accrued
131. Leave_Consumed
132. Leave_Adjustment
133. Leave_Lapse
134. Leave_Balance
135. Leave_Future_Approved
136. Leave_Balance_After_Future
137. Leave_Encashment
138. Leave_Carry_Forward
139. Leave_Record_Count
140. Leave_Type_Count

In [42]:

# ==========================================================
# STEP 18: FEATURE AUDIT BEFORE RANDOM FOREST
# ==========================================================

# Target
target_col = "Attrition"

# Columns that should NOT be used as model features
exclude_cols = [
    # Target
    "Attrition",

    # Attrition / outcome leakage
    "Resignation Date",
    "Last Working Date",
    "FNF Settlement Date",
    "Employee Status",
    "Leave Status",
    "Effective End Date",
    "Employee Status_form",

    # Employee identifiers
    "Employee Code",
    "Employee_Code_Clean",
    "_emp_code",

    # Personal identifiers / PII
    "First Name",
    "Middle Name",
    "Last Name",
    "Employee Name",
    "Preferred Name",
    "Official Email Address",
    "Personal Email Address",
    "Personal Mobile Number",
    "Emergency Contact Number",
    "PAN Number",
    "Aadhar Card No",
    "Account Number",
    "IFSC Code",
    "PF Number",
    "UAN Number",
    "ESIC Number",
    "Father Name",
    "Permanent Address",
    "Current Address",
    "Correspondence Address",
]

# Check which requested exclusions actually exist
existing_exclusions = [
    col for col in exclude_cols
    if col in model_base.columns
]

missing_exclusions = [
    col for col in exclude_cols
    if col not in model_base.columns
]

print("Total columns:", len(model_base.columns))

print("\nColumns excluded:", len(existing_exclusions))

print("\nExcluded columns:")
for col in existing_exclusions:
    print("-", col)

print("\nColumns not found:")
for col in missing_exclusions:
    print("-", col)

# Candidate features
candidate_features = [
    col for col in model_base.columns
    if col not in existing_exclusions
]

print("\nCandidate feature count:", len(candidate_features))

print("\nCandidate features:")
for i, col in enumerate(candidate_features, 1):
    print(f"{i:3}. {col}")

Total columns: 140

Columns excluded: 31

Excluded columns:
- Attrition
- Resignation Date
- Last Working Date
- FNF Settlement Date
- Employee Status
- Leave Status
- Effective End Date
- Employee Status_form
- Employee Code
- Employee_Code_Clean
- _emp_code
- First Name
- Middle Name
- Last Name
- Employee Name
- Preferred Name
- Official Email Address
- Personal Email Address
- Personal Mobile Number
- Emergency Contact Number
- PAN Number
- Aadhar Card No
- Account Number
- IFSC Code
- PF Number
- UAN Number
- ESIC Number
- Father Name
- Permanent Address
- Current Address
- Correspondence Address

Columns not found:

Candidate feature count: 109

Candidate features:
  1. Group
  2. Company Name
  3. Title
  4. Gender
  5. Nationality
  6. Resident Type
  7. Marital Status
  8. City Name
  9. State Name
 10. Branch
 11. Site Branch
 12. Division
 13. Designation
 14. Department
 15. Sub Department
 16. Cost Center
 17. Site Cost Center
 18. Site Name
 19. Grade
 20. Band
 21. Reason for Requirement
 22. Employee Category
 23. Reporting Manager Code
 24. Reporting Manager Name
 25. Skip Level Manager Code
 26. Skip Level Manager
 27. Actual Join Date
 28. Group Join Date
 29. Year Of Service (Current DOJ)
 30. Year of Service (Group DOJ)
 31. Physical Disability
 32. Point of Hire
 33. Point of Repatriation
 34. ESIC Flag
 35. PF Applicable
 36. PF Type
 37. Probation Status
 38. Confirmation Date
 39. Source of Hire
 40. Dual Nationality
 41. Religion
 42. Agreement type
 43. Effective Start Date
 44. Employee Air Ticket
 45. Air Ticket Class
 46. Air Ticket frequency
 47. Blood Group
 48. Group Medical Insurance
 49. Confidential Profile Flag
 50. Confidential Profile
 51. Conf. Date (Period Master)
 52. 2nd Nationality
 53. Employer Notice Period
 54. Bank Name
 55. Movement Type
 56. Birth Date
 57. Last Payable Days
 58. Cost Code
 59. Profit Code
 60. Client Vertical
 61. Resident
 62. Wage Type
 63. TAX Regime
 64. Uniform Deduction
 65. Process Name
 66. Designation_form
 67. Cost Center_form
 68. Gender_form
 69. Marital Status_form
 70. Location
 71. Region Name
 72. Site Name_form
 73. Client Verticle
 74. Date Of Joined
 75. Created Date
 76. Monthly Gross Salary
 77. Annual_Gross_Salary
 78. Tenure_Days
 79. Tenure_Years
 80. OT1_Chargeable_OT
 81. OT1_NonChargeable_OT
 82. OT1_Total_OT
 83. OT1_OT_Days
 84. OT1_Avg_Daily_OT
 85. OT1_Max_Daily_OT
 86. OT2_Chargeable_OT
 87. OT2_NonChargeable_OT
 88. OT2_Total_OT
 89. OT3_Chargeable_OT
 90. OT3_NonChargeable_OT
 91. OT3_Total_OT
 92. OT4_Chargeable_OT
 93. OT4_NonChargeable_OT
 94. OT4_Total_OT
 95. OT4_OT_Days
 96. OT4_Avg_Daily_OT
 97. OT4_Max_Daily_OT
 98. Leave_Opening_Balance
 99. Leave_Accrued
100. Leave_Consumed
101. Leave_Adjustment
102. Leave_Lapse
103. Leave_Balance
104. Leave_Future_Approved
105. Leave_Balance_After_Future
106. Leave_Encashment
107. Leave_Carry_Forward
108. Leave_Record_Count
109. Leave_Type_Count

In [43]:
# ==========================================================
# STEP 19: AUDIT CANDIDATE FEATURES
# ==========================================================

audit_rows = []

for col in candidate_features:

    s = model_base[col]

    audit_rows.append({
        "Column": col,
        "Dtype": str(s.dtype),
        "Missing": int(s.isna().sum()),
        "Missing_%": round(s.isna().mean() * 100, 2),
        "Unique": int(s.nunique(dropna=True)),
        "Unique_%": round(
            s.nunique(dropna=True) / len(model_base) * 100, 2
        )
    })

feature_audit = pd.DataFrame(audit_rows)

print("Feature audit shape:", feature_audit.shape)

print("\n===== CANDIDATE FEATURE AUDIT =====")
print(feature_audit.to_string(index=False))

Feature audit shape: (109, 6)

===== CANDIDATE FEATURE AUDIT =====
                       Column          Dtype  Missing  Missing_%  Unique  Unique_%
                        Group            str        0       0.00       1      0.00
                 Company Name            str        0       0.00       1      0.00
                        Title            str        0       0.00       4      0.02
                       Gender            str        0       0.00       2      0.01
                  Nationality            str        0       0.00       1      0.00
                Resident Type            str        0       0.00       1      0.00
               Marital Status            str        0       0.00       7      0.03
                    City Name            str        0       0.00       8      0.04
                   State Name            str        0       0.00       7      0.03
                       Branch            str        0       0.00       9      0.04
                  Site Branch            str        0       0.00       9      0.04
                     Division            str        0       0.00       1      0.00
                  Designation            str        0       0.00     378      1.85
                   Department            str        0       0.00      11      0.05
               Sub Department            str    20276      99.06       2      0.01
                  Cost Center            str        0       0.00     668      3.26
             Site Cost Center            str        0       0.00     668      3.26
                    Site Name            str        0       0.00     800      3.91
                        Grade            str        0       0.00      14      0.07
                         Band            str        0       0.00       2      0.01
       Reason for Requirement            str     7116      34.77       4      0.02
            Employee Category            str        0       0.00       2      0.01
       Reporting Manager Code            str        0       0.00     316      1.54
       Reporting Manager Name            str        0       0.00     316      1.54
      Skip Level Manager Code            str        0       0.00     124      0.61
           Skip Level Manager            str        0       0.00     124      0.61
             Actual Join Date datetime64[us]        0       0.00    2697     13.18
              Group Join Date datetime64[us]        0       0.00    2697     13.18
Year Of Service (Current DOJ)          int64        0       0.00      23      0.11
  Year of Service (Group DOJ)          int64        0       0.00      23      0.11
          Physical Disability            str        0       0.00       2      0.01
                Point of Hire            str    18283      89.32      49      0.24
        Point of Repatriation            str    18282      89.32      51      0.25
                    ESIC Flag         object      123       0.60       3      0.01
                PF Applicable            str     1178       5.76       2      0.01
                      PF Type            str        0       0.00      12      0.06
             Probation Status            str        1       0.00       2      0.01
            Confirmation Date datetime64[us]     3876      18.94    1901      9.29
               Source of Hire            str     7115      34.76       2      0.01
             Dual Nationality            str        0       0.00       1      0.00
                     Religion            str     7106      34.72       4      0.02
               Agreement type        float64    20468     100.00       0      0.00
         Effective Start Date         object        0       0.00    2113     10.32
          Employee Air Ticket            str     8294      40.52       1      0.00
             Air Ticket Class        float64    20468     100.00       0      0.00
         Air Ticket frequency            str     7117      34.77       1      0.00
                  Blood Group            str    18900      92.34       8      0.04
      Group Medical Insurance            str    20467     100.00       1      0.00
    Confidential Profile Flag            str    20442      99.87       1      0.00
         Confidential Profile        float64    20468     100.00       0      0.00
   Conf. Date (Period Master) datetime64[us]     3876      18.94    1901      9.29
              2nd Nationality            str     8272      40.41       1      0.00
       Employer Notice Period        float64        9       0.04       3      0.01
                    Bank Name            str      143       0.70      90      0.44
                Movement Type            str        0       0.00       5      0.02
                   Birth Date datetime64[us]        0       0.00    9091     44.42
            Last Payable Days datetime64[us]    20391      99.62      16      0.08
                    Cost Code         object        0       0.00     651      3.18
                  Profit Code          int64        0       0.00     632      3.09
              Client Vertical            str        0       0.00      18      0.09
                     Resident            str        0       0.00       3      0.01
                    Wage Type            str       11       0.05       2      0.01
                   TAX Regime            str       36       0.18       2      0.01
            Uniform Deduction            str        0       0.00       2      0.01
                 Process Name        float64    20468     100.00       0      0.00
             Designation_form            str    13823      67.53     181      0.88
             Cost Center_form            str    13823      67.53     483      2.36
                  Gender_form            str    13823      67.53       2      0.01
          Marital Status_form            str    13823      67.53       7      0.03
                     Location            str    13823      67.53      45      0.22
                  Region Name            str    13823      67.53       5      0.02
               Site Name_form            str    13823      67.53     576      2.81
              Client Verticle            str    13823      67.53      13      0.06
               Date Of Joined datetime64[us]    13823      67.53     227      1.11
                 Created Date datetime64[us]    13823      67.53     202      0.99
         Monthly Gross Salary        float64    13823      67.53    1633      7.98
          Annual_Gross_Salary        float64    13823      67.53    1633      7.98
                  Tenure_Days        float64    13823      67.53     227      1.11
                 Tenure_Years        float64    13823      67.53     227      1.11
            OT1_Chargeable_OT        float64    17262      84.34     132      0.64
         OT1_NonChargeable_OT        float64    17262      84.34     132      0.64
                 OT1_Total_OT        float64    17262      84.34     184      0.90
                  OT1_OT_Days        float64    17262      84.34      27      0.13
             OT1_Avg_Daily_OT        float64    17262      84.34     184      0.90
             OT1_Max_Daily_OT        float64    17262      84.34      29      0.14
            OT2_Chargeable_OT        float64    17262      84.34     132      0.64
         OT2_NonChargeable_OT        float64    17262      84.34     132      0.64
                 OT2_Total_OT        float64    17262      84.34     184      0.90
            OT3_Chargeable_OT        float64    15702      76.71      92      0.45
         OT3_NonChargeable_OT        float64    15702      76.71     176      0.86
                 OT3_Total_OT        float64    15702      76.71     195      0.95
            OT4_Chargeable_OT        float64    15707      76.74      92      0.45
         OT4_NonChargeable_OT        float64    15707      76.74     176      0.86
                 OT4_Total_OT        float64    15707      76.74     195      0.95
                  OT4_OT_Days        float64    15707      76.74      27      0.13
             OT4_Avg_Daily_OT        float64    15707      76.74     195      0.95
             OT4_Max_Daily_OT        float64    15707      76.74      50      0.24
        Leave_Opening_Balance        float64     2136      10.44     127      0.62
                Leave_Accrued        float64     2136      10.44    1185      5.79
               Leave_Consumed        float64     2136      10.44      32      0.16
             Leave_Adjustment        float64     2136      10.44       1      0.00
                  Leave_Lapse        float64     2136      10.44       1      0.00
                Leave_Balance        float64     2136      10.44    1429      6.98
        Leave_Future_Approved        float64     2136      10.44       6      0.03
   Leave_Balance_After_Future        float64     2136      10.44    1429      6.98
             Leave_Encashment        float64     2136      10.44       1      0.00
          Leave_Carry_Forward        float64     2136      10.44    1429      6.98
           Leave_Record_Count        float64     2136      10.44       4      0.02
             Leave_Type_Count        float64     2136      10.44       4      0.02

In [44]:
# ==========================================================
# HIGH-CARDINALITY FEATURES
# ==========================================================

print("===== HIGH CARDINALITY FEATURES =====")

high_cardinality = feature_audit[
    (feature_audit["Unique_%"] > 10)
].sort_values(
    "Unique",
    ascending=False
)

print(high_cardinality.to_string(index=False))

===== HIGH CARDINALITY FEATURES =====
              Column          Dtype  Missing  Missing_%  Unique  Unique_%
          Birth Date datetime64[us]        0        0.0    9091     44.42
    Actual Join Date datetime64[us]        0        0.0    2697     13.18
     Group Join Date datetime64[us]        0        0.0    2697     13.18
Effective Start Date         object        0        0.0    2113     10.32

In [45]:
# ==========================================================
# STEP 20: CREATE CLEAN MODEL FEATURE SET
# ==========================================================

# Start from the 109 candidate features
model_exclusions = set()

# ----------------------------------------------------------
# 1. Remove sensitive / protected attributes
# ----------------------------------------------------------

sensitive_cols = [
    "Gender",
    "Nationality",
    "Marital Status",
    "Physical Disability",
    "Dual Nationality",
    "Religion",
    "2nd Nationality",
    "Blood Group",
]

# ----------------------------------------------------------
# 2. Remove employee / manager identifiers
# ----------------------------------------------------------

identifier_cols = [
    "Reporting Manager Code",
    "Reporting Manager Name",
    "Skip Level Manager Code",
    "Skip Level Manager",
]

# ----------------------------------------------------------
# 3. Remove raw date columns
# ----------------------------------------------------------

raw_date_cols = [
    "Actual Join Date",
    "Group Join Date",
    "Birth Date",
    "Confirmation Date",
    "Effective Start Date",
    "Conf. Date (Period Master)",
    "Date Of Joined",
    "Created Date",
    "Last Payable Days",
]

# ----------------------------------------------------------
# 4. Remove completely empty / practically empty columns
# ----------------------------------------------------------

empty_cols = [
    "Agreement type",
    "Air Ticket Class",
    "Group Medical Insurance",
    "Confidential Profile",
    "Process Name",
]

very_high_missing_cols = [
    "Sub Department",
    "Point of Hire",
    "Point of Repatriation",
    "Blood Group",
    "Confidential Profile Flag",
]

# ----------------------------------------------------------
# 5. Remove fields with almost no useful variation
# ----------------------------------------------------------

low_information_cols = [
    "Group",
    "Company Name",
    "Resident Type",
    "Division",
    "Nationality",
    "Dual Nationality",
    "2nd Nationality",
    "Employee Air Ticket",
    "Air Ticket frequency",
]

# ----------------------------------------------------------
# 6. Remove redundant Form copies
# ----------------------------------------------------------

redundant_form_cols = [
    "Designation_form",
    "Cost Center_form",
    "Gender_form",
    "Marital Status_form",
    "Site Name_form",
    "Client Verticle",
]

# ----------------------------------------------------------
# 7. Remove financial / personal identifiers
# ----------------------------------------------------------

financial_identifier_cols = [
    "Bank Name",
]

# ----------------------------------------------------------
# Combine all exclusions
# ----------------------------------------------------------

model_exclusions.update(sensitive_cols)
model_exclusions.update(identifier_cols)
model_exclusions.update(raw_date_cols)
model_exclusions.update(empty_cols)
model_exclusions.update(very_high_missing_cols)
model_exclusions.update(low_information_cols)
model_exclusions.update(redundant_form_cols)
model_exclusions.update(financial_identifier_cols)

# Only keep columns that actually exist
model_exclusions = [
    col for col in model_exclusions
    if col in model_base.columns
]

# ----------------------------------------------------------
# Final feature list
# ----------------------------------------------------------

model_features = [
    col for col in model_base.columns
    if col not in model_exclusions
]

print("==================================================")
print("FINAL MODEL FEATURE SUMMARY")
print("==================================================")

print("Original columns:", len(model_base.columns))
print("Excluded columns:", len(model_exclusions))
print("Final model features:", len(model_features))

print("\nFINAL MODEL FEATURES:")

for i, col in enumerate(model_features, 1):
    print(f"{i:3}. {col}")

==================================================
FINAL MODEL FEATURE SUMMARY
==================================================
Original columns: 140
Excluded columns: 43
Final model features: 97

FINAL MODEL FEATURES:
  1. Employee Code
  2. Title
  3. First Name
  4. Middle Name
  5. Last Name
  6. Employee Name
  7. Official Email Address
  8. Personal Email Address
  9. City Name
 10. State Name
 11. Branch
 12. Site Branch
 13. Designation
 14. Department
 15. Cost Center
 16. Site Cost Center
 17. Site Name
 18. Grade
 19. Band
 20. Reason for Requirement
 21. Employee Category
 22. Employee Status
 23. Resignation Date
 24. Year Of Service (Current DOJ)
 25. Year of Service (Group DOJ)
 26. ESIC Flag
 27. ESIC Number
 28. PF Applicable
 29. PF Type
 30. PF Number
 31. UAN Number
 32. FNF Settlement Date
 33. Probation Status
 34. Source of Hire
 35. Preferred Name
 36. Effective End Date
 37. Employer Notice Period
 38. Movement Type
 39. PAN Number
 40. Aadhar Card No
 41. Account Number
 42. IFSC Code
 43. Personal Mobile Number
 44. Emergency Contact Number
 45. Father Name
 46. Last Working Date
 47. Cost Code
 48. Profit Code
 49. Client Vertical
 50. Permanent Address
 51. Current Address
 52. Correspondence Address
 53. Leave Status
 54. Resident
 55. Wage Type
 56. TAX Regime
 57. Uniform Deduction
 58. Employee_Code_Clean
 59. _emp_code
 60. Attrition
 61. Employee Status_form
 62. Location
 63. Region Name
 64. Monthly Gross Salary
 65. Annual_Gross_Salary
 66. Tenure_Days
 67. Tenure_Years
 68. OT1_Chargeable_OT
 69. OT1_NonChargeable_OT
 70. OT1_Total_OT
 71. OT1_OT_Days
 72. OT1_Avg_Daily_OT
 73. OT1_Max_Daily_OT
 74. OT2_Chargeable_OT
 75. OT2_NonChargeable_OT
 76. OT2_Total_OT
 77. OT3_Chargeable_OT
 78. OT3_NonChargeable_OT
 79. OT3_Total_OT
 80. OT4_Chargeable_OT
 81. OT4_NonChargeable_OT
 82. OT4_Total_OT
 83. OT4_OT_Days
 84. OT4_Avg_Daily_OT
 85. OT4_Max_Daily_OT
 86. Leave_Opening_Balance
 87. Leave_Accrued
 88. Leave_Consumed
 89. Leave_Adjustment
 90. Leave_Lapse
 91. Leave_Balance
 92. Leave_Future_Approved
 93. Leave_Balance_After_Future
 94. Leave_Encashment
 95. Leave_Carry_Forward
 96. Leave_Record_Count
 97. Leave_Type_Count

In [46]:

# ==========================================================
# STEP 20: CREATE CLEAN MODEL FEATURE SET
# ==========================================================

# IMPORTANT:
# Start ONLY from the 109 candidate features.
# Do NOT start again from all 140 model_base columns.

candidate_features = [
    c for c in candidate_features
    if c in model_base.columns
]

print("Candidate features available:", len(candidate_features))


# ==========================================================
# 1. TARGET COLUMN
# ==========================================================

target_col = "Attrition"


# ==========================================================
# 2. REMOVE IDENTIFIERS / PERSONAL INFORMATION
# ==========================================================

identifier_cols = {
    "Employee Code",
    "Employee_Code_Clean",
    "_emp_code",

    "First Name",
    "Middle Name",
    "Last Name",
    "Employee Name",
    "Preferred Name",

    "Official Email Address",
    "Personal Email Address",
    "Personal Mobile Number",
    "Emergency Contact Number",

    "PAN Number",
    "Aadhar Card No",
    "Account Number",
    "IFSC Code",
    "PF Number",
    "UAN Number",
    "ESIC Number",

    "Father Name",

    "Permanent Address",
    "Current Address",
    "Correspondence Address",
}


# ==========================================================
# 3. REMOVE TARGET / DATA LEAKAGE COLUMNS
# ==========================================================

leakage_cols = {
    "Attrition",

    "Resignation Date",
    "Last Working Date",
    "FNF Settlement Date",

    "Employee Status",
    "Employee Status_form",

    "Leave Status",
    "Effective End Date",
}


# ==========================================================
# 4. REMOVE SENSITIVE / PROTECTED ATTRIBUTES
# ==========================================================

sensitive_cols = {
    "Gender",
    "Nationality",
    "Marital Status",
    "Physical Disability",
    "Dual Nationality",
    "Religion",
    "2nd Nationality",
    "Blood Group",
}


# ==========================================================
# 5. COMBINE EXCLUSIONS
# ==========================================================

model_exclusions = (
    identifier_cols
    | leakage_cols
    | sensitive_cols
)


# ==========================================================
# 6. CREATE FINAL MODEL FEATURES
# ==========================================================

final_model_features = [
    c for c in candidate_features
    if c not in model_exclusions
]


# ==========================================================
# 7. SAFETY CHECKS
# ==========================================================

# Target must NEVER be present
assert target_col not in final_model_features

# Leakage columns must NEVER be present
leakage_found = [
    c for c in final_model_features
    if c in leakage_cols
]

assert len(leakage_found) == 0, (
    f"Leakage columns found: {leakage_found}"
)

# Identifier columns must NEVER be present
identifier_found = [
    c for c in final_model_features
    if c in identifier_cols
]

assert len(identifier_found) == 0, (
    f"Identifier columns found: {identifier_found}"
)


# ==========================================================
# 8. FINAL SUMMARY
# ==========================================================

print("=" * 60)
print("FINAL MODEL FEATURE SUMMARY")
print("=" * 60)

print("Original columns:", len(model_base.columns))
print("Candidate features:", len(candidate_features))
print("Excluded from candidates:", len(candidate_features) - len(final_model_features))
print("Final model features:", len(final_model_features))

print("\nFINAL MODEL FEATURES:")

for i, col in enumerate(final_model_features, 1):
    print(f"{i:3}. {col}")


# ==========================================================
# 9. SHOW EXCLUDED CANDIDATES
# ==========================================================

excluded_from_candidates = [
    c for c in candidate_features
    if c in model_exclusions
]

print("\n" + "=" * 60)
print("EXCLUDED CANDIDATE FEATURES")
print("=" * 60)

for i, col in enumerate(excluded_from_candidates, 1):
    print(f"{i:3}. {col}")

Candidate features available: 109
============================================================
FINAL MODEL FEATURE SUMMARY
============================================================
Original columns: 140
Candidate features: 109
Excluded from candidates: 8
Final model features: 101

FINAL MODEL FEATURES:
  1. Group
  2. Company Name
  3. Title
  4. Resident Type
  5. City Name
  6. State Name
  7. Branch
  8. Site Branch
  9. Division
 10. Designation
 11. Department
 12. Sub Department
 13. Cost Center
 14. Site Cost Center
 15. Site Name
 16. Grade
 17. Band
 18. Reason for Requirement
 19. Employee Category
 20. Reporting Manager Code
 21. Reporting Manager Name
 22. Skip Level Manager Code
 23. Skip Level Manager
 24. Actual Join Date
 25. Group Join Date
 26. Year Of Service (Current DOJ)
 27. Year of Service (Group DOJ)
 28. Point of Hire
 29. Point of Repatriation
 30. ESIC Flag
 31. PF Applicable
 32. PF Type
 33. Probation Status
 34. Confirmation Date
 35. Source of Hire
 36. Agreement type
 37. Effective Start Date
 38. Employee Air Ticket
 39. Air Ticket Class
 40. Air Ticket frequency
 41. Group Medical Insurance
 42. Confidential Profile Flag
 43. Confidential Profile
 44. Conf. Date (Period Master)
 45. Employer Notice Period
 46. Bank Name
 47. Movement Type
 48. Birth Date
 49. Last Payable Days
 50. Cost Code
 51. Profit Code
 52. Client Vertical
 53. Resident
 54. Wage Type
 55. TAX Regime
 56. Uniform Deduction
 57. Process Name
 58. Designation_form
 59. Cost Center_form
 60. Gender_form
 61. Marital Status_form
 62. Location
 63. Region Name
 64. Site Name_form
 65. Client Verticle
 66. Date Of Joined
 67. Created Date
 68. Monthly Gross Salary
 69. Annual_Gross_Salary
 70. Tenure_Days
 71. Tenure_Years
 72. OT1_Chargeable_OT
 73. OT1_NonChargeable_OT
 74. OT1_Total_OT
 75. OT1_OT_Days
 76. OT1_Avg_Daily_OT
 77. OT1_Max_Daily_OT
 78. OT2_Chargeable_OT
 79. OT2_NonChargeable_OT
 80. OT2_Total_OT
 81. OT3_Chargeable_OT
 82. OT3_NonChargeable_OT
 83. OT3_Total_OT
 84. OT4_Chargeable_OT
 85. OT4_NonChargeable_OT
 86. OT4_Total_OT
 87. OT4_OT_Days
 88. OT4_Avg_Daily_OT
 89. OT4_Max_Daily_OT
 90. Leave_Opening_Balance
 91. Leave_Accrued
 92. Leave_Consumed
 93. Leave_Adjustment
 94. Leave_Lapse
 95. Leave_Balance
 96. Leave_Future_Approved
 97. Leave_Balance_After_Future
 98. Leave_Encashment
 99. Leave_Carry_Forward
100. Leave_Record_Count
101. Leave_Type_Count

============================================================
EXCLUDED CANDIDATE FEATURES
============================================================
  1. Gender
  2. Nationality
  3. Marital Status
  4. Physical Disability
  5. Dual Nationality
  6. Religion
  7. Blood Group
  8. 2nd Nationality

In [47]:
# ==========================================================
# STEP 21: CLEAN FINAL MODEL FEATURES
# ==========================================================

# Start from the 101 features created in Step 20
clean_features = final_model_features.copy()


# ==========================================================
# 1. REMOVE CONSTANT / ZERO-VARIANCE FEATURES
# ==========================================================

constant_cols = [
    c for c in clean_features
    if model_base[c].nunique(dropna=True) <= 1
]


# ==========================================================
# 2. REMOVE EXTREMELY HIGH-MISSING FEATURES
# ==========================================================

missing_pct = model_base[clean_features].isna().mean() * 100

high_missing_cols = missing_pct[
    missing_pct >= 90
].index.tolist()


# ==========================================================
# 3. REMOVE DUPLICATE SENSITIVE / PROTECTED FORM COLUMNS
# ==========================================================

sensitive_form_cols = {
    "Gender_form",
    "Marital Status_form",
}


# ==========================================================
# 4. REMOVE FORM COLUMNS WITH VERY HIGH MISSINGNESS
# ==========================================================

high_missing_form_cols = [
    c for c in clean_features
    if c.endswith("_form") and missing_pct[c] > 60
]


# ==========================================================
# 5. COMBINE EXCLUSIONS
# ==========================================================

step21_exclusions = (
    set(constant_cols)
    | set(high_missing_cols)
    | sensitive_form_cols
    | set(high_missing_form_cols)
)


# ==========================================================
# 6. CREATE CLEAN FEATURES
# ==========================================================

clean_features = [
    c for c in clean_features
    if c not in step21_exclusions
]


# ==========================================================
# 7. FINAL SUMMARY
# ==========================================================

print("=" * 60)
print("STEP 21: CLEAN FEATURE SUMMARY")
print("=" * 60)

print("Features before cleaning:", len(final_model_features))
print("Features removed:", len(step21_exclusions))
print("Features remaining:", len(clean_features))


print("\n" + "=" * 60)
print("CONSTANT FEATURES REMOVED")
print("=" * 60)

for c in constant_cols:
    print(c)


print("\n" + "=" * 60)
print("HIGH-MISSING FEATURES REMOVED (>=90%)")
print("=" * 60)

for c in high_missing_cols:
    print(f"{c}: {missing_pct[c]:.2f}%")


print("\n" + "=" * 60)
print("HIGH-MISSING FORM FEATURES REMOVED")
print("=" * 60)

for c in high_missing_form_cols:
    print(f"{c}: {missing_pct[c]:.2f}%")


print("\n" + "=" * 60)
print("FINAL CLEAN FEATURES")
print("=" * 60)

for i, c in enumerate(clean_features, 1):
    print(f"{i:3}. {c}")

============================================================
STEP 21: CLEAN FEATURE SUMMARY
============================================================
Features before cleaning: 101
Features removed: 22
Features remaining: 79

============================================================
CONSTANT FEATURES REMOVED
============================================================
Group
Company Name
Resident Type
Division
Agreement type
Employee Air Ticket
Air Ticket Class
Air Ticket frequency
Group Medical Insurance
Confidential Profile Flag
Confidential Profile
Process Name
Leave_Adjustment
Leave_Lapse
Leave_Encashment

============================================================
HIGH-MISSING FEATURES REMOVED (>=90%)
============================================================
Sub Department: 99.06%
Agreement type: 100.00%
Air Ticket Class: 100.00%
Group Medical Insurance: 100.00%
Confidential Profile Flag: 99.87%
Confidential Profile: 100.00%
Last Payable Days: 99.62%
Process Name: 100.00%

============================================================
HIGH-MISSING FORM FEATURES REMOVED
============================================================
Designation_form: 67.53%
Cost Center_form: 67.53%
Gender_form: 67.53%
Marital Status_form: 67.53%
Site Name_form: 67.53%

============================================================
FINAL CLEAN FEATURES
============================================================
  1. Title
  2. City Name
  3. State Name
  4. Branch
  5. Site Branch
  6. Designation
  7. Department
  8. Cost Center
  9. Site Cost Center
 10. Site Name
 11. Grade
 12. Band
 13. Reason for Requirement
 14. Employee Category
 15. Reporting Manager Code
 16. Reporting Manager Name
 17. Skip Level Manager Code
 18. Skip Level Manager
 19. Actual Join Date
 20. Group Join Date
 21. Year Of Service (Current DOJ)
 22. Year of Service (Group DOJ)
 23. Point of Hire
 24. Point of Repatriation
 25. ESIC Flag
 26. PF Applicable
 27. PF Type
 28. Probation Status
 29. Confirmation Date
 30. Source of Hire
 31. Effective Start Date
 32. Conf. Date (Period Master)
 33. Employer Notice Period
 34. Bank Name
 35. Movement Type
 36. Birth Date
 37. Cost Code
 38. Profit Code
 39. Client Vertical
 40. Resident
 41. Wage Type
 42. TAX Regime
 43. Uniform Deduction
 44. Location
 45. Region Name
 46. Client Verticle
 47. Date Of Joined
 48. Created Date
 49. Monthly Gross Salary
 50. Annual_Gross_Salary
 51. Tenure_Days
 52. Tenure_Years
 53. OT1_Chargeable_OT
 54. OT1_NonChargeable_OT
 55. OT1_Total_OT
 56. OT1_OT_Days
 57. OT1_Avg_Daily_OT
 58. OT1_Max_Daily_OT
 59. OT2_Chargeable_OT
 60. OT2_NonChargeable_OT
 61. OT2_Total_OT
 62. OT3_Chargeable_OT
 63. OT3_NonChargeable_OT
 64. OT3_Total_OT
 65. OT4_Chargeable_OT
 66. OT4_NonChargeable_OT
 67. OT4_Total_OT
 68. OT4_OT_Days
 69. OT4_Avg_Daily_OT
 70. OT4_Max_Daily_OT
 71. Leave_Opening_Balance
 72. Leave_Accrued
 73. Leave_Consumed
 74. Leave_Balance
 75. Leave_Future_Approved
 76. Leave_Balance_After_Future
 77. Leave_Carry_Forward
 78. Leave_Record_Count
 79. Leave_Type_Count

In [48]:
# ==========================================================
# STEP 22: FINAL FEATURE QUALITY CHECK
# ==========================================================

print("=" * 70)
print("STEP 22: FINAL FEATURE QUALITY CHECK")
print("=" * 70)

feature_audit_final = pd.DataFrame({
    "Column": clean_features,
    "Dtype": [str(model_base[c].dtype) for c in clean_features],
    "Missing": [model_base[c].isna().sum() for c in clean_features],
    "Missing_%": [
        round(model_base[c].isna().mean() * 100, 2)
        for c in clean_features
    ],
    "Unique": [
        model_base[c].nunique(dropna=True)
        for c in clean_features
    ],
})

feature_audit_final["Unique_%"] = (
    feature_audit_final["Unique"]
    / len(model_base)
    * 100
).round(2)


# ----------------------------------------------------------
# Sort by missing percentage
# ----------------------------------------------------------

print("\n===== FEATURES SORTED BY MISSING % =====")

print(
    feature_audit_final
    .sort_values("Missing_%", ascending=False)
    .to_string(index=False)
)


# ----------------------------------------------------------
# High-cardinality categorical columns
# ----------------------------------------------------------

categorical_cols = [
    c for c in clean_features
    if model_base[c].dtype == "object"
    or str(model_base[c].dtype).startswith("string")
]


high_cardinality = (
    feature_audit_final[
        feature_audit_final["Column"].isin(categorical_cols)
    ]
    .sort_values("Unique", ascending=False)
)


print("\n===== HIGH CARDINALITY CATEGORICAL FEATURES =====")

print(
    high_cardinality[
        ["Column", "Dtype", "Missing_%", "Unique", "Unique_%"]
    ].head(30).to_string(index=False)
)


# ----------------------------------------------------------
# Numeric features
# ----------------------------------------------------------

numeric_cols = [
    c for c in clean_features
    if c not in categorical_cols
]

print("\n===== NUMERIC FEATURES =====")
print("Count:", len(numeric_cols))

print("\n===== CATEGORICAL FEATURES =====")
print("Count:", len(categorical_cols))


# ----------------------------------------------------------
# Date-like columns
# ----------------------------------------------------------

date_cols = [
    c for c in clean_features
    if "date" in c.lower()
    or "doj" in c.lower()
    or "birth" in c.lower()
]

print("\n===== DATE-LIKE FEATURES =====")

for c in date_cols:
    print(c)

======================================================================
STEP 22: FINAL FEATURE QUALITY CHECK
======================================================================

===== FEATURES SORTED BY MISSING % =====
                       Column          Dtype  Missing  Missing_%  Unique  Unique_%
                Point of Hire            str    18283      89.32      49      0.24
        Point of Repatriation            str    18282      89.32      51      0.25
                 OT1_Total_OT        float64    17262      84.34     184      0.90
            OT2_Chargeable_OT        float64    17262      84.34     132      0.64
         OT1_NonChargeable_OT        float64    17262      84.34     132      0.64
            OT1_Chargeable_OT        float64    17262      84.34     132      0.64
         OT2_NonChargeable_OT        float64    17262      84.34     132      0.64
                 OT2_Total_OT        float64    17262      84.34     184      0.90
             OT1_Max_Daily_OT        float64    17262      84.34      29      0.14
             OT1_Avg_Daily_OT        float64    17262      84.34     184      0.90
                  OT1_OT_Days        float64    17262      84.34      27      0.13
            OT4_Chargeable_OT        float64    15707      76.74      92      0.45
                 OT4_Total_OT        float64    15707      76.74     195      0.95
             OT4_Avg_Daily_OT        float64    15707      76.74     195      0.95
             OT4_Max_Daily_OT        float64    15707      76.74      50      0.24
         OT4_NonChargeable_OT        float64    15707      76.74     176      0.86
                  OT4_OT_Days        float64    15707      76.74      27      0.13
         OT3_NonChargeable_OT        float64    15702      76.71     176      0.86
            OT3_Chargeable_OT        float64    15702      76.71      92      0.45
                 OT3_Total_OT        float64    15702      76.71     195      0.95
               Date Of Joined datetime64[us]    13823      67.53     227      1.11
                  Region Name            str    13823      67.53       5      0.02
              Client Verticle            str    13823      67.53      13      0.06
                 Created Date datetime64[us]    13823      67.53     202      0.99
         Monthly Gross Salary        float64    13823      67.53    1633      7.98
          Annual_Gross_Salary        float64    13823      67.53    1633      7.98
                 Tenure_Years        float64    13823      67.53     227      1.11
                  Tenure_Days        float64    13823      67.53     227      1.11
                     Location            str    13823      67.53      45      0.22
       Reason for Requirement            str     7116      34.77       4      0.02
               Source of Hire            str     7115      34.76       2      0.01
   Conf. Date (Period Master) datetime64[us]     3876      18.94    1901      9.29
            Confirmation Date datetime64[us]     3876      18.94    1901      9.29
                Leave_Accrued        float64     2136      10.44    1185      5.79
               Leave_Consumed        float64     2136      10.44      32      0.16
   Leave_Balance_After_Future        float64     2136      10.44    1429      6.98
          Leave_Carry_Forward        float64     2136      10.44    1429      6.98
                Leave_Balance        float64     2136      10.44    1429      6.98
        Leave_Future_Approved        float64     2136      10.44       6      0.03
             Leave_Type_Count        float64     2136      10.44       4      0.02
        Leave_Opening_Balance        float64     2136      10.44     127      0.62
           Leave_Record_Count        float64     2136      10.44       4      0.02
                PF Applicable            str     1178       5.76       2      0.01
                    Bank Name            str      143       0.70      90      0.44
                    ESIC Flag         object      123       0.60       3      0.01
                   TAX Regime            str       36       0.18       2      0.01
                    Wage Type            str       11       0.05       2      0.01
       Employer Notice Period        float64        9       0.04       3      0.01
            Employee Category            str        0       0.00       2      0.01
       Reporting Manager Code            str        0       0.00     316      1.54
                        Grade            str        0       0.00      14      0.07
             Site Cost Center            str        0       0.00     668      3.26
                    Site Name            str        0       0.00     800      3.91
                         Band            str        0       0.00       2      0.01
                   Department            str        0       0.00      11      0.05
                   State Name            str        0       0.00       7      0.03
                  Designation            str        0       0.00     378      1.85
                  Site Branch            str        0       0.00       9      0.04
                       Branch            str        0       0.00       9      0.04
                        Title            str        0       0.00       4      0.02
                    City Name            str        0       0.00       8      0.04
                  Cost Center            str        0       0.00     668      3.26
                     Resident            str        0       0.00       3      0.01
           Skip Level Manager            str        0       0.00     124      0.61
            Uniform Deduction            str        0       0.00       2      0.01
                  Profit Code          int64        0       0.00     632      3.09
                Movement Type            str        0       0.00       5      0.02
                   Birth Date datetime64[us]        0       0.00    9091     44.42
                    Cost Code         object        0       0.00     651      3.18
              Client Vertical            str        0       0.00      18      0.09
       Reporting Manager Name            str        0       0.00     316      1.54
  Year of Service (Group DOJ)          int64        0       0.00      23      0.11
Year Of Service (Current DOJ)          int64        0       0.00      23      0.11
              Group Join Date datetime64[us]        0       0.00    2697     13.18
             Actual Join Date datetime64[us]        0       0.00    2697     13.18
      Skip Level Manager Code            str        0       0.00     124      0.61
                      PF Type            str        0       0.00      12      0.06
             Probation Status            str        1       0.00       2      0.01
         Effective Start Date         object        0       0.00    2113     10.32

===== HIGH CARDINALITY CATEGORICAL FEATURES =====
              Column  Dtype  Missing_%  Unique  Unique_%
Effective Start Date object        0.0    2113     10.32
           Cost Code object        0.0     651      3.18
           ESIC Flag object        0.6       3      0.01

===== NUMERIC FEATURES =====
Count: 76

===== CATEGORICAL FEATURES =====
Count: 3

===== DATE-LIKE FEATURES =====
Actual Join Date
Group Join Date
Year Of Service (Current DOJ)
Year of Service (Group DOJ)
Confirmation Date
Effective Start Date
Conf. Date (Period Master)
Birth Date
Date Of Joined
Created Date

In [49]:

# ==========================================================
# STEP 23: PREPARE FEATURES FOR MODELING
# ==========================================================

import pandas as pd
import numpy as np

# Start with the 79 clean features
model_features = clean_features.copy()

print("=" * 70)
print("STEP 23: MODEL FEATURE PREPARATION")
print("=" * 70)


# ==========================================================
# 1. IDENTIFY DATE COLUMNS
# ==========================================================

date_cols = [
    c for c in model_features
    if (
        "date" in c.lower()
        or "doj" in c.lower()
        or "birth" in c.lower()
    )
]

print("\nDATE COLUMNS:")
for c in date_cols:
    print(" -", c)


# ==========================================================
# 2. IDENTIFY CATEGORICAL COLUMNS CORRECTLY
# ==========================================================

categorical_cols = []

for c in model_features:

    dtype = model_base[c].dtype

    if (
        pd.api.types.is_object_dtype(dtype)
        or pd.api.types.is_string_dtype(dtype)
        or pd.api.types.is_categorical_dtype(dtype)
    ):
        categorical_cols.append(c)


# Remove date columns from categorical list
categorical_cols = [
    c for c in categorical_cols
    if c not in date_cols
]


# ==========================================================
# 3. IDENTIFY NUMERIC COLUMNS
# ==========================================================

numeric_cols = [
    c for c in model_features
    if c not in categorical_cols
    and c not in date_cols
]


# ==========================================================
# 4. PRINT CORRECT COUNTS
# ==========================================================

print("\n" + "=" * 70)
print("FEATURE TYPE SUMMARY")
print("=" * 70)

print("Total model features:", len(model_features))
print("Date features:", len(date_cols))
print("Categorical features:", len(categorical_cols))
print("Numeric features:", len(numeric_cols))

print("\nCATEGORICAL FEATURES:")
for i, c in enumerate(categorical_cols, 1):
    print(f"{i:3}. {c}")

print("\nNUMERIC FEATURES:")
for i, c in enumerate(numeric_cols, 1):
    print(f"{i:3}. {c}")


# ==========================================================
# 5. CHECK HIGH-CARDINALITY CATEGORICAL FEATURES
# ==========================================================

print("\n" + "=" * 70)
print("HIGH-CARDINALITY CATEGORICAL FEATURES")
print("=" * 70)

for c in categorical_cols:

    unique_count = model_base[c].nunique(dropna=True)

    if unique_count >= 100:
        print(
            f"{c}: "
            f"{unique_count} unique values"
        )


# ==========================================================
# 6. CHECK DATE TYPES
# ==========================================================

print("\n" + "=" * 70)
print("DATE COLUMN TYPES")
print("=" * 70)

for c in date_cols:
    print(
        f"{c}: "
        f"{model_base[c].dtype}"
    )


# ==========================================================
# 7. CHECK MISSINGNESS FOR CATEGORICAL FEATURES
# ==========================================================

print("\n" + "=" * 70)
print("CATEGORICAL MISSINGNESS")
print("=" * 70)

for c in categorical_cols:

    missing_pct = model_base[c].isna().mean() * 100

    print(
        f"{c}: "
        f"{missing_pct:.2f}% missing"
    )

======================================================================
STEP 23: MODEL FEATURE PREPARATION
======================================================================

DATE COLUMNS:
 - Actual Join Date
 - Group Join Date
 - Year Of Service (Current DOJ)
 - Year of Service (Group DOJ)
 - Confirmation Date
 - Effective Start Date
 - Conf. Date (Period Master)
 - Birth Date
 - Date Of Joined
 - Created Date

======================================================================
FEATURE TYPE SUMMARY
======================================================================
Total model features: 79
Date features: 10
Categorical features: 36
Numeric features: 33

CATEGORICAL FEATURES:
  1. Title
  2. City Name
  3. State Name
  4. Branch
  5. Site Branch
  6. Designation
  7. Department
  8. Cost Center
  9. Site Cost Center
 10. Site Name
 11. Grade
 12. Band
 13. Reason for Requirement
 14. Employee Category
 15. Reporting Manager Code
 16. Reporting Manager Name
 17. Skip Level Manager Code
 18. Skip Level Manager
 19. Point of Hire
 20. Point of Repatriation
 21. ESIC Flag
 22. PF Applicable
 23. PF Type
 24. Probation Status
 25. Source of Hire
 26. Bank Name
 27. Movement Type
 28. Cost Code
 29. Client Vertical
 30. Resident
 31. Wage Type
 32. TAX Regime
 33. Uniform Deduction
 34. Location
 35. Region Name
 36. Client Verticle

NUMERIC FEATURES:
  1. Employer Notice Period
  2. Profit Code
  3. Monthly Gross Salary
  4. Annual_Gross_Salary
  5. Tenure_Days
  6. Tenure_Years
  7. OT1_Chargeable_OT
  8. OT1_NonChargeable_OT
  9. OT1_Total_OT
 10. OT1_OT_Days
 11. OT1_Avg_Daily_OT
 12. OT1_Max_Daily_OT
 13. OT2_Chargeable_OT
 14. OT2_NonChargeable_OT
 15. OT2_Total_OT
 16. OT3_Chargeable_OT
 17. OT3_NonChargeable_OT
 18. OT3_Total_OT
 19. OT4_Chargeable_OT
 20. OT4_NonChargeable_OT
 21. OT4_Total_OT
 22. OT4_OT_Days
 23. OT4_Avg_Daily_OT
 24. OT4_Max_Daily_OT
 25. Leave_Opening_Balance
 26. Leave_Accrued
 27. Leave_Consumed
 28. Leave_Balance
 29. Leave_Future_Approved
 30. Leave_Balance_After_Future
 31. Leave_Carry_Forward
 32. Leave_Record_Count
 33. Leave_Type_Count

======================================================================
HIGH-CARDINALITY CATEGORICAL FEATURES
======================================================================
Designation: 378 unique values
Cost Center: 668 unique values
Site Cost Center: 668 unique values
Site Name: 800 unique values
Reporting Manager Code: 316 unique values
Reporting Manager Name: 316 unique values
Skip Level Manager Code: 124 unique values
Skip Level Manager: 124 unique values
Cost Code: 651 unique values

======================================================================
DATE COLUMN TYPES
======================================================================
Actual Join Date: datetime64[us]
Group Join Date: datetime64[us]
Year Of Service (Current DOJ): int64
Year of Service (Group DOJ): int64
Confirmation Date: datetime64[us]
Effective Start Date: object
Conf. Date (Period Master): datetime64[us]
Birth Date: datetime64[us]
Date Of Joined: datetime64[us]
Created Date: datetime64[us]

======================================================================
CATEGORICAL MISSINGNESS
======================================================================
Title: 0.00% missing
City Name: 0.00% missing
State Name: 0.00% missing
Branch: 0.00% missing
Site Branch: 0.00% missing
Designation: 0.00% missing
Department: 0.00% missing
Cost Center: 0.00% missing
Site Cost Center: 0.00% missing
Site Name: 0.00% missing
Grade: 0.00% missing
Band: 0.00% missing
Reason for Requirement: 34.77% missing
Employee Category: 0.00% missing
Reporting Manager Code: 0.00% missing
Reporting Manager Name: 0.00% missing
Skip Level Manager Code: 0.00% missing
Skip Level Manager: 0.00% missing
Point of Hire: 89.32% missing
Point of Repatriation: 89.32% missing
ESIC Flag: 0.60% missing
PF Applicable: 5.76% missing
PF Type: 0.00% missing
Probation Status: 0.00% missing
Source of Hire: 34.76% missing
Bank Name: 0.70% missing
Movement Type: 0.00% missing
Cost Code: 0.00% missing
Client Vertical: 0.00% missing
Resident: 0.00% missing
Wage Type: 0.05% missing
TAX Regime: 0.18% missing
Uniform Deduction: 0.00% missing
Location: 67.53% missing
Region Name: 67.53% missing
Client Verticle: 67.53% missing

C:\Users\veena.sharma\AppData\Local\Temp\ipykernel_3824\381583991.py:47: Pandas4Warning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  or pd.api.types.is_categorical_dtype(dtype)

In [50]:

# ==========================================================
# STEP 24: PREPARE MODELING DATASET
# ==========================================================

import numpy as np
import pandas as pd

# ----------------------------------------------------------
# Start from clean features
# ----------------------------------------------------------

model_features_step24 = clean_features.copy()


# ----------------------------------------------------------
# Remove extremely sparse categorical fields
# ----------------------------------------------------------

sparse_cols = [
    "Point of Hire",
    "Point of Repatriation",
]

model_features_step24 = [
    c for c in model_features_step24
    if c not in sparse_cols
]


# ----------------------------------------------------------
# Create working dataframe
# ----------------------------------------------------------

model_data = model_base[
    model_features_step24 + ["Attrition"]
].copy()


# ==========================================================
# 1. CONVERT EFFECTIVE START DATE TO DATETIME
# ==========================================================

if "Effective Start Date" in model_data.columns:

    model_data["Effective Start Date"] = pd.to_datetime(
        model_data["Effective Start Date"],
        errors="coerce"
    )


# ==========================================================
# 2. CREATE AGE FROM BIRTH DATE
# ==========================================================

reference_date = pd.Timestamp("2026-08-07")

if "Birth Date" in model_data.columns:

    model_data["Age_Years"] = (
        reference_date - model_data["Birth Date"]
    ).dt.days / 365.25

    model_data["Age_Years"] = (
        model_data["Age_Years"]
        .clip(lower=18, upper=70)
    )


# ==========================================================
# 3. CREATE TENURE FROM JOIN DATE
# ==========================================================

if "Actual Join Date" in model_data.columns:

    model_data["Calculated_Tenure_Years"] = (
        reference_date - model_data["Actual Join Date"]
    ).dt.days / 365.25

    model_data["Calculated_Tenure_Years"] = (
        model_data["Calculated_Tenure_Years"]
        .clip(lower=0)
    )


# ==========================================================
# 4. CREATE CONFIRMATION STATUS
# ==========================================================

if "Confirmation Date" in model_data.columns:

    model_data["Is_Confirmed"] = (
        model_data["Confirmation Date"].notna()
    ).astype(int)


# ==========================================================
# 5. CREATE OT DATA AVAILABILITY FLAGS
# ==========================================================

ot_groups = [
    "OT1",
    "OT2",
    "OT3",
    "OT4",
]

for ot in ot_groups:

    total_col = f"{ot}_Total_OT"

    if total_col in model_data.columns:

        model_data[f"{ot}_Data_Available"] = (
            model_data[total_col].notna()
        ).astype(int)


# ==========================================================
# 6. CREATE FORM / SALARY DATA AVAILABILITY FLAG
# ==========================================================

if "Monthly Gross Salary" in model_data.columns:

    model_data["Salary_Data_Available"] = (
        model_data["Monthly Gross Salary"].notna()
    ).astype(int)


# ==========================================================
# 7. CREATE LEAVE DATA AVAILABILITY FLAG
# ==========================================================

if "Leave_Balance" in model_data.columns:

    model_data["Leave_Data_Available"] = (
        model_data["Leave_Balance"].notna()
    ).astype(int)


# ==========================================================
# 8. FILL OT MISSING VALUES WITH ZERO
# ==========================================================

ot_feature_cols = [
    c for c in model_data.columns
    if c.startswith("OT1_")
    or c.startswith("OT2_")
    or c.startswith("OT3_")
    or c.startswith("OT4_")
]

for c in ot_feature_cols:

    if "Data_Available" not in c:

        model_data[c] = model_data[c].fillna(0)


# ==========================================================
# 9. FILL LEAVE NUMERIC MISSING VALUES
# ==========================================================

leave_feature_cols = [
    c for c in model_data.columns
    if c.startswith("Leave_")
]

for c in leave_feature_cols:

    if c != "Leave_Data_Available":

        model_data[c] = model_data[c].fillna(0)


# ==========================================================
# 10. CHECK DATASET
# ==========================================================

print("=" * 70)
print("STEP 24: MODELING DATASET")
print("=" * 70)

print("Shape:", model_data.shape)

print("\nTarget distribution:")
print(model_data["Attrition"].value_counts())

print("\nTarget percentage:")
print(
    model_data["Attrition"].value_counts(normalize=True)
    .mul(100)
    .round(2)
)

print("\nMissing target:")
print(model_data["Attrition"].isna().sum())

print("\nOT availability:")

for ot in ot_groups:

    flag = f"{ot}_Data_Available"

    if flag in model_data.columns:

        print(
            f"{ot}:",
            model_data[flag].value_counts().to_dict()
        )

print("\nSalary availability:")

if "Salary_Data_Available" in model_data.columns:
    print(
        model_data["Salary_Data_Available"]
        .value_counts()
        .to_dict()
    )

print("\nLeave availability:")

if "Leave_Data_Available" in model_data.columns:
    print(
        model_data["Leave_Data_Available"]
        .value_counts()
        .to_dict()
    )

======================================================================
STEP 24: MODELING DATASET
======================================================================
Shape: (20468, 87)

Target distribution:
Attrition
0    20245
1      223
Name: count, dtype: int64

Target percentage:
Attrition
0    98.91
1     1.09
Name: proportion, dtype: float64

Missing target:
0

OT availability:
OT1: {0: 17262, 1: 3206}
OT2: {0: 17262, 1: 3206}
OT3: {0: 15702, 1: 4766}
OT4: {0: 15707, 1: 4761}

Salary availability:
{0: 13823, 1: 6645}

Leave availability:
{1: 18332, 0: 2136}

In [51]:

# ==========================================================
# STEP 25: BUILD X AND y FOR RANDOM FOREST
# ==========================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("STEP 25: BUILD MODEL INPUTS")
print("=" * 70)


# ==========================================================
# 1. COPY MODEL DATA
# ==========================================================

rf_data = model_data.copy()


# ==========================================================
# 2. TARGET
# ==========================================================

y = rf_data["Attrition"].astype(int)

X = rf_data.drop(
    columns=["Attrition"]
).copy()


# ==========================================================
# 3. CONVERT DATE FEATURES INTO NUMERIC FEATURES
# ==========================================================

date_columns = [
    c for c in X.columns
    if pd.api.types.is_datetime64_any_dtype(X[c])
]


print("\nDate columns to transform:")

for c in date_columns:
    print(" -", c)


# Use a fixed reference date for reproducibility
reference_date = pd.Timestamp("2026-08-07")


for c in date_columns:

    # Convert date to number of days from reference date
    X[c + "_Days"] = (
        reference_date - X[c]
    ).dt.days

    # Missing date indicator
    X[c + "_Missing"] = (
        X[c].isna()
    ).astype(int)

    # Remove original datetime column
    X.drop(
        columns=[c],
        inplace=True
    )


# ==========================================================
# 4. CHECK EFFECTIVE START DATE
# ==========================================================

# It was originally object, but Step 24 converted it.
# If anything still remains as object but looks like a date,
# we will handle it later rather than silently encoding it.


# ==========================================================
# 5. IDENTIFY CATEGORICAL / NUMERIC FEATURES
# ==========================================================

categorical_features = [
    c for c in X.columns
    if (
        pd.api.types.is_object_dtype(X[c])
        or pd.api.types.is_string_dtype(X[c])
        or isinstance(X[c].dtype, pd.CategoricalDtype)
    )
]


numeric_features = [
    c for c in X.columns
    if c not in categorical_features
]


# ==========================================================
# 6. PRINT SUMMARY
# ==========================================================

print("\n" + "=" * 70)
print("MODEL INPUT SUMMARY")
print("=" * 70)

print("X shape:", X.shape)
print("y shape:", y.shape)

print("\nTarget distribution:")
print(y.value_counts())

print("\nTarget percentages:")
print(
    y.value_counts(normalize=True)
    .mul(100)
    .round(2)
)

print("\nCategorical features:", len(categorical_features))
print("Numeric features:", len(numeric_features))

print("\nCategorical columns:")

for i, c in enumerate(categorical_features, 1):
    print(f"{i:3}. {c}")

print("\nNumeric columns:")

for i, c in enumerate(numeric_features, 1):
    print(f"{i:3}. {c}")


# ==========================================================
# 7. CHECK REMAINING OBJECT COLUMNS
# ==========================================================

print("\n" + "=" * 70)
print("REMAINING OBJECT / STRING COLUMNS")
print("=" * 70)

for c in categorical_features:

    print(
        f"{c}: "
        f"dtype={X[c].dtype}, "
        f"unique={X[c].nunique(dropna=True)}, "
        f"missing={X[c].isna().sum()}"
    )


# ==========================================================
# 8. FINAL SAFETY CHECK
# ==========================================================

print("\n" + "=" * 70)
print("SAFETY CHECK")
print("=" * 70)

print("Target column present in X:", "Attrition" in X.columns)

print(
    "Employee identity columns accidentally present:",
    [
        c for c in [
            "Employee Code",
            "Employee_Code_Clean",
            "_emp_code"
        ]
        if c in X.columns
    ]
)

print(
    "Resignation leakage columns present:",
    [
        c for c in [
            "Resignation Date",
            "Last Working Date",
            "FNF Settlement Date"
        ]
        if c in X.columns
    ]
)

======================================================================
STEP 25: BUILD MODEL INPUTS
======================================================================

Date columns to transform:
 - Actual Join Date
 - Group Join Date
 - Confirmation Date
 - Effective Start Date
 - Conf. Date (Period Master)
 - Birth Date
 - Date Of Joined
 - Created Date

======================================================================
MODEL INPUT SUMMARY
======================================================================
X shape: (20468, 94)
y shape: (20468,)

Target distribution:
Attrition
0    20245
1      223
Name: count, dtype: int64

Target percentages:
Attrition
0    98.91
1     1.09
Name: proportion, dtype: float64

Categorical features: 34
Numeric features: 60

Categorical columns:
  1. Title
  2. City Name
  3. State Name
  4. Branch
  5. Site Branch
  6. Designation
  7. Department
  8. Cost Center
  9. Site Cost Center
 10. Site Name
 11. Grade
 12. Band
 13. Reason for Requirement
 14. Employee Category
 15. Reporting Manager Code
 16. Reporting Manager Name
 17. Skip Level Manager Code
 18. Skip Level Manager
 19. ESIC Flag
 20. PF Applicable
 21. PF Type
 22. Probation Status
 23. Source of Hire
 24. Bank Name
 25. Movement Type
 26. Cost Code
 27. Client Vertical
 28. Resident
 29. Wage Type
 30. TAX Regime
 31. Uniform Deduction
 32. Location
 33. Region Name
 34. Client Verticle

Numeric columns:
  1. Year Of Service (Current DOJ)
  2. Year of Service (Group DOJ)
  3. Employer Notice Period
  4. Profit Code
  5. Monthly Gross Salary
  6. Annual_Gross_Salary
  7. Tenure_Days
  8. Tenure_Years
  9. OT1_Chargeable_OT
 10. OT1_NonChargeable_OT
 11. OT1_Total_OT
 12. OT1_OT_Days
 13. OT1_Avg_Daily_OT
 14. OT1_Max_Daily_OT
 15. OT2_Chargeable_OT
 16. OT2_NonChargeable_OT
 17. OT2_Total_OT
 18. OT3_Chargeable_OT
 19. OT3_NonChargeable_OT
 20. OT3_Total_OT
 21. OT4_Chargeable_OT
 22. OT4_NonChargeable_OT
 23. OT4_Total_OT
 24. OT4_OT_Days
 25. OT4_Avg_Daily_OT
 26. OT4_Max_Daily_OT
 27. Leave_Opening_Balance
 28. Leave_Accrued
 29. Leave_Consumed
 30. Leave_Balance
 31. Leave_Future_Approved
 32. Leave_Balance_After_Future
 33. Leave_Carry_Forward
 34. Leave_Record_Count
 35. Leave_Type_Count
 36. Age_Years
 37. Calculated_Tenure_Years
 38. Is_Confirmed
 39. OT1_Data_Available
 40. OT2_Data_Available
 41. OT3_Data_Available
 42. OT4_Data_Available
 43. Salary_Data_Available
 44. Leave_Data_Available
 45. Actual Join Date_Days
 46. Actual Join Date_Missing
 47. Group Join Date_Days
 48. Group Join Date_Missing
 49. Confirmation Date_Days
 50. Confirmation Date_Missing
 51. Effective Start Date_Days
 52. Effective Start Date_Missing
 53. Conf. Date (Period Master)_Days
 54. Conf. Date (Period Master)_Missing
 55. Birth Date_Days
 56. Birth Date_Missing
 57. Date Of Joined_Days
 58. Date Of Joined_Missing
 59. Created Date_Days
 60. Created Date_Missing

======================================================================
REMAINING OBJECT / STRING COLUMNS
======================================================================
Title: dtype=str, unique=4, missing=0
City Name: dtype=str, unique=8, missing=0
State Name: dtype=str, unique=7, missing=0
Branch: dtype=str, unique=9, missing=0
Site Branch: dtype=str, unique=9, missing=0
Designation: dtype=str, unique=378, missing=0
Department: dtype=str, unique=11, missing=0
Cost Center: dtype=str, unique=668, missing=0
Site Cost Center: dtype=str, unique=668, missing=0
Site Name: dtype=str, unique=800, missing=0
Grade: dtype=str, unique=14, missing=0
Band: dtype=str, unique=2, missing=0
Reason for Requirement: dtype=str, unique=4, missing=7116
Employee Category: dtype=str, unique=2, missing=0
Reporting Manager Code: dtype=str, unique=316, missing=0
Reporting Manager Name: dtype=str, unique=316, missing=0
Skip Level Manager Code: dtype=str, unique=124, missing=0
Skip Level Manager: dtype=str, unique=124, missing=0
ESIC Flag: dtype=object, unique=3, missing=123
PF Applicable: dtype=str, unique=2, missing=1178
PF Type: dtype=str, unique=12, missing=0
Probation Status: dtype=str, unique=2, missing=1
Source of Hire: dtype=str, unique=2, missing=7115
Bank Name: dtype=str, unique=90, missing=143
Movement Type: dtype=str, unique=5, missing=0
Cost Code: dtype=object, unique=651, missing=0
Client Vertical: dtype=str, unique=18, missing=0
Resident: dtype=str, unique=3, missing=0
Wage Type: dtype=str, unique=2, missing=11
TAX Regime: dtype=str, unique=2, missing=36
Uniform Deduction: dtype=str, unique=2, missing=0
Location: dtype=str, unique=45, missing=13823
Region Name: dtype=str, unique=5, missing=13823
Client Verticle: dtype=str, unique=13, missing=13823

======================================================================
SAFETY CHECK
======================================================================
Target column present in X: False
Employee identity columns accidentally present: []
Resignation leakage columns present: []

In [52]:
# ==========================================================
# STEP 26: TRAIN / TEST SPLIT + PREPROCESSING
# ==========================================================

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline

print("=" * 70)
print("STEP 26: TRAIN / TEST SPLIT + PREPROCESSING")
print("=" * 70)


# ==========================================================
# 1. TRAIN / TEST SPLIT
# ==========================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)


# ==========================================================
# 2. VERIFY CLASS DISTRIBUTION
# ==========================================================

print("\nTRAINING SET")
print("Shape:", X_train.shape)

print("\nTraining target distribution:")
print(y_train.value_counts())

print("\nTraining target percentage:")
print(
    y_train.value_counts(normalize=True)
    .mul(100)
    .round(2)
)


print("\n" + "-" * 70)

print("\nTEST SET")
print("Shape:", X_test.shape)

print("\nTest target distribution:")
print(y_test.value_counts())

print("\nTest target percentage:")
print(
    y_test.value_counts(normalize=True)
    .mul(100)
    .round(2)
)


# ==========================================================
# 3. PREPROCESSING
# ==========================================================

# Numeric pipeline
numeric_pipeline = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(strategy="median")
        )
    ]
)


# Categorical pipeline
categorical_pipeline = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(
                strategy="constant",
                fill_value="Missing"
            )
        ),
        (
            "encoder",
            OneHotEncoder(
                handle_unknown="ignore",
                min_frequency=2
            )
        )
    ]
)


# ==========================================================
# 4. COMBINE PREPROCESSORS
# ==========================================================

preprocessor = ColumnTransformer(
    transformers=[
        (
            "numeric",
            numeric_pipeline,
            numeric_features
        ),
        (
            "categorical",
            categorical_pipeline,
            categorical_features
        )
    ],
    remainder="drop"
)


# ==========================================================
# 5. FIT ONLY ON TRAINING DATA
# ==========================================================

X_train_processed = preprocessor.fit_transform(
    X_train
)

X_test_processed = preprocessor.transform(
    X_test
)


# ==========================================================
# 6. OUTPUT SHAPE
# ==========================================================

print("\n" + "=" * 70)
print("PREPROCESSING RESULT")
print("=" * 70)

print(
    "Original feature count:",
    X_train.shape[1]
)

print(
    "Processed training shape:",
    X_train_processed.shape
)

print(
    "Processed test shape:",
    X_test_processed.shape
)


# ==========================================================
# 7. SPARSITY CHECK
# ==========================================================

print("\nProcessed matrix type:")
print(type(X_train_processed))

if hasattr(X_train_processed, "nnz"):

    print(
        "Training non-zero values:",
        X_train_processed.nnz
    )

    print(
        "Training matrix density:",
        round(
            X_train_processed.nnz /
            (
                X_train_processed.shape[0]
                * X_train_processed.shape[1]
            ) * 100,
            4
        ),
        "%"
    )


# ==========================================================
# 8. FINAL CHECK
# ==========================================================

print("\n" + "=" * 70)
print("FINAL CHECK")
print("=" * 70)

print(
    "Train rows:",
    len(X_train)
)

print(
    "Test rows:",
    len(X_test)
)

print(
    "Train attrition cases:",
    int(y_train.sum())
)

print(
    "Test attrition cases:",
    int(y_test.sum())
)

print(
    "Preprocessor fitted successfully: YES"
)

======================================================================
STEP 26: TRAIN / TEST SPLIT + PREPROCESSING
======================================================================

TRAINING SET
Shape: (16374, 94)

Training target distribution:
Attrition
0    16196
1      178
Name: count, dtype: int64

Training target percentage:
Attrition
0    98.91
1     1.09
Name: proportion, dtype: float64

----------------------------------------------------------------------

TEST SET
Shape: (4094, 94)

Test target distribution:
Attrition
0    4049
1      45
Name: count, dtype: int64

Test target percentage:
Attrition
0    98.9
1     1.1
Name: proportion, dtype: float64

TypeError: Encoders require their input argument must be uniformly strings or numbers. Got ['int', 'str']

In [ ]:
# ==========================================================
# STEP 26.1: FIX MIXED CATEGORICAL VALUES
# ==========================================================

import pandas as pd
import numpy as np

# Make copies
X_train_fixed = X_train.copy()
X_test_fixed = X_test.copy()

# ----------------------------------------------------------
# 1. Clean categorical columns
# ----------------------------------------------------------

for col in categorical_features:

    # Convert everything to string safely.
    # Missing values are explicitly replaced before conversion.
    X_train_fixed[col] = (
        X_train_fixed[col]
        .astype("object")
        .where(X_train_fixed[col].notna(), "MISSING")
        .astype(str)
    )

    X_test_fixed[col] = (
        X_test_fixed[col]
        .astype("object")
        .where(X_test_fixed[col].notna(), "MISSING")
        .astype(str)
    )


# ----------------------------------------------------------
# 2. Clean numeric columns
# ----------------------------------------------------------

for col in numeric_features:

    X_train_fixed[col] = pd.to_numeric(
        X_train_fixed[col],
        errors="coerce"
    )

    X_test_fixed[col] = pd.to_numeric(
        X_test_fixed[col],
        errors="coerce"
    )


print("Categorical values fixed successfully.")
print("Training shape:", X_train_fixed.shape)
print("Test shape:", X_test_fixed.shape)


# ==========================================================
# 3. PREPROCESSOR
# ==========================================================

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer


categorical_pipeline = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(
                strategy="constant",
                fill_value="MISSING"
            )
        ),
        (
            "encoder",
            OneHotEncoder(
                handle_unknown="ignore",
                sparse_output=True
            )
        )
    ]
)


numeric_pipeline = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(
                strategy="median"
            )
        )
    ]
)


preprocessor = ColumnTransformer(
    transformers=[
        (
            "categorical",
            categorical_pipeline,
            categorical_features
        ),
        (
            "numeric",
            numeric_pipeline,
            numeric_features
        )
    ],
    remainder="drop"
)


# ==========================================================
# 4. FIT ONLY ON TRAINING DATA
# ==========================================================

X_train_processed = preprocessor.fit_transform(
    X_train_fixed
)

X_test_processed = preprocessor.transform(
    X_test_fixed
)


# ==========================================================
# 5. RESULTS
# ==========================================================

print("\n" + "=" * 60)
print("STEP 26.1: PREPROCESSING SUCCESS")
print("=" * 60)

print("Original X train shape:", X_train.shape)
print("Processed X train shape:", X_train_processed.shape)

print("Original X test shape:", X_test.shape)
print("Processed X test shape:", X_test_processed.shape)

print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

Categorical values fixed successfully.
Training shape: (16374, 94)
Test shape: (4094, 94)

============================================================
STEP 26.1: PREPROCESSING SUCCESS
============================================================
Original X train shape: (16374, 94)
Processed X train shape: (16374, 4263)
Original X test shape: (4094, 94)
Processed X test shape: (4094, 4263)
y_train shape: (16374,)
y_test shape: (4094,)

In [ ]:
# ==========================================================
# STEP 27: RANDOM FOREST MODEL
# ==========================================================

from sklearn.ensemble import RandomForestClassifier

# Create Random Forest
rf_model = RandomForestClassifier(
    n_estimators=300,
    max_depth=None,
    min_samples_split=10,
    min_samples_leaf=3,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

print("Training Random Forest...")

# Train
rf_model.fit(
    X_train_processed,
    y_train
)

print("\n" + "=" * 60)
print("STEP 27: RANDOM FOREST TRAINING SUCCESS")
print("=" * 60)

print("Number of trees:", rf_model.n_estimators)
print("Training samples:", X_train_processed.shape[0])
print("Processed features:", X_train_processed.shape[1])

Training Random Forest...

============================================================
STEP 27: RANDOM FOREST TRAINING SUCCESS
============================================================
Number of trees: 300
Training samples: 16374
Processed features: 4263

In [ ]:
# ==========================================================
# STEP 28: RANDOM FOREST PREDICTIONS & MODEL EVALUATION
# ==========================================================

from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_auc_score,
    average_precision_score,
    accuracy_score
)

# ----------------------------------------------------------
# 1. Predictions
# ----------------------------------------------------------

y_test_pred = rf_model.predict(X_test_processed)
y_test_prob = rf_model.predict_proba(X_test_processed)[:, 1]


# ----------------------------------------------------------
# 2. Confusion Matrix
# ----------------------------------------------------------

cm = confusion_matrix(y_test, y_test_pred)

print("=" * 60)
print("STEP 28: RANDOM FOREST MODEL EVALUATION")
print("=" * 60)

print("\nConfusion Matrix:")
print(cm)


# ----------------------------------------------------------
# 3. Classification Report
# ----------------------------------------------------------

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_test_pred,
        digits=4,
        zero_division=0
    )
)


# ----------------------------------------------------------
# 4. Accuracy
# ----------------------------------------------------------

accuracy = accuracy_score(
    y_test,
    y_test_pred
)

print(f"Accuracy: {accuracy:.4f}")


# ----------------------------------------------------------
# 5. ROC-AUC
# ----------------------------------------------------------

roc_auc = roc_auc_score(
    y_test,
    y_test_prob
)

print(f"ROC-AUC: {roc_auc:.4f}")


# ----------------------------------------------------------
# 6. PR-AUC
# ----------------------------------------------------------

pr_auc = average_precision_score(
    y_test,
    y_test_prob
)

print(f"PR-AUC: {pr_auc:.4f}")


# ----------------------------------------------------------
# 7. Actual vs Predicted Attrition
# ----------------------------------------------------------

print("\nActual attrition cases in test set:",
      int((y_test == 1).sum()))

print("Predicted attrition cases:",
      int((y_test_pred == 1).sum()))

print("\n" + "=" * 60)

============================================================
STEP 28: RANDOM FOREST MODEL EVALUATION
============================================================

Confusion Matrix:
[[4043    6]
 [  18   27]]

Classification Report:
              precision    recall  f1-score   support

           0     0.9956    0.9985    0.9970      4049
           1     0.8182    0.6000    0.6923        45

    accuracy                         0.9941      4094
   macro avg     0.9069    0.7993    0.8447      4094
weighted avg     0.9936    0.9941    0.9937      4094

Accuracy: 0.9941
ROC-AUC: 0.9797
PR-AUC: 0.7548

Actual attrition cases in test set: 45
Predicted attrition cases: 33

============================================================

In [ ]:
# ==========================================================
# STEP 29: RANDOM FOREST FEATURE IMPORTANCE
# ==========================================================

import pandas as pd
import numpy as np

print("=" * 60)
print("STEP 29: RANDOM FOREST FEATURE IMPORTANCE")
print("=" * 60)


# ==========================================================
# 1. GET FEATURE IMPORTANCE FROM RANDOM FOREST
# ==========================================================

encoded_importance = rf_model.feature_importances_

print("\nNumber of encoded features:",
      len(encoded_importance))


# ==========================================================
# 2. GET ENCODED FEATURE NAMES
# ==========================================================

encoded_feature_names = preprocessor.get_feature_names_out()

print("Number of encoded feature names:",
      len(encoded_feature_names))


# Safety check
assert len(encoded_importance) == len(encoded_feature_names), \
    "Feature importance and feature names count do not match."


# ==========================================================
# 3. CREATE ENCODED IMPORTANCE DATAFRAME
# ==========================================================

importance_df = pd.DataFrame({
    "Encoded_Feature": encoded_feature_names,
    "Importance": encoded_importance
})


# ==========================================================
# 4. MAP ENCODED FEATURES BACK TO ORIGINAL FEATURES
# ==========================================================

def get_original_feature(encoded_name):

    # Remove ColumnTransformer prefix
    if "__" in encoded_name:
        encoded_name = encoded_name.split("__", 1)[1]

    # Check categorical features first
    for col in categorical_features:
        if encoded_name == col or encoded_name.startswith(col + "_"):
            return col

    # Check numeric features
    for col in numeric_features:
        if encoded_name == col:
            return col

    # Fallback
    return encoded_name


importance_df["Original_Feature"] = (
    importance_df["Encoded_Feature"]
    .apply(get_original_feature)
)


# ==========================================================
# 5. AGGREGATE IMPORTANCE
# ==========================================================

feature_importance = (
    importance_df
    .groupby("Original_Feature", as_index=False)["Importance"]
    .sum()
    .sort_values(
        "Importance",
        ascending=False
    )
    .reset_index(drop=True)
)


# ==========================================================
# 6. CONVERT TO PERCENTAGE
# ==========================================================

feature_importance["Importance_%"] = (
    feature_importance["Importance"] * 100
)


# ==========================================================
# 7. ADD RANK
# ==========================================================

feature_importance.insert(
    0,
    "Rank",
    range(1, len(feature_importance) + 1)
)


# ==========================================================
# 8. DISPLAY TOP 30 PREDICTIVE FACTORS
# ==========================================================

print("\n" + "=" * 60)
print("TOP 30 PREDICTIVE FACTORS")
print("=" * 60)

print(
    feature_importance[
        [
            "Rank",
            "Original_Feature",
            "Importance",
            "Importance_%"
        ]
    ].head(30).to_string(index=False)
)


# ==========================================================
# 9. CHECK TOTAL IMPORTANCE
# ==========================================================

print("\n" + "=" * 60)
print("IMPORTANCE CHECK")
print("=" * 60)

print(
    "Total encoded importance:",
    encoded_importance.sum()
)

print(
    "Total aggregated importance:",
    feature_importance["Importance"].sum()
)


# ==========================================================
# 10. SAVE FEATURE IMPORTANCE
# ==========================================================

feature_importance.to_excel(
    "random_forest_feature_importance.xlsx",
    index=False
)

print("\nSaved:")
print("random_forest_feature_importance.xlsx")

============================================================
STEP 29: RANDOM FOREST FEATURE IMPORTANCE
============================================================

Number of encoded features: 4263
Number of encoded feature names: 4263

============================================================
TOP 30 PREDICTIVE FACTORS
============================================================
 Rank                Original_Feature  Importance  Importance_%
    1                   Movement Type    0.156699     15.669943
    2       Effective Start Date_Days    0.061295      6.129519
    3                   Leave_Accrued    0.037537      3.753696
    4             Leave_Carry_Forward    0.031949      3.194904
    5                   Leave_Balance    0.029393      2.939260
    6                     Cost Center    0.028043      2.804305
    7      Leave_Balance_After_Future    0.027007      2.700710
    8         Skip Level Manager Code    0.026743      2.674262
    9                       Site Name    0.026627      2.662711
   10                       Cost Code    0.026495      2.649514
   11          Reporting Manager Name    0.026081      2.608137
   12                Site Cost Center    0.025886      2.588584
   13              Skip Level Manager    0.025262      2.526193
   14          Reporting Manager Code    0.024275      2.427546
   15                 Client Vertical    0.019464      1.946371
   16                     Site Branch    0.018180      1.818010
   17            Group Join Date_Days    0.017238      1.723765
   18         Calculated_Tenure_Years    0.017131      1.713093
   19           Actual Join Date_Days    0.016128      1.612837
   20                       City Name    0.015993      1.599253
   21                          Branch    0.015576      1.557618
   22          Confirmation Date_Days    0.015187      1.518749
   23 Conf. Date (Period Master)_Days    0.014283      1.428312
   24                     Designation    0.013737      1.373662
   25                     Region Name    0.012980      1.297975
   26                      State Name    0.012977      1.297657
   27                 Client Verticle    0.012011      1.201108
   28                       Age_Years    0.010028      1.002816
   29                 Birth Date_Days    0.009527      0.952694
   30                     Tenure_Days    0.009224      0.922425

============================================================
IMPORTANCE CHECK
============================================================
Total encoded importance: 0.9999999999999998
Total aggregated importance: 0.9999999999999999

Saved:
random_forest_feature_importance.xlsx

In [ ]:
# ==========================================================
# STEP 30: ANALYZE TOP PREDICTIVE FACTOR - MOVEMENT TYPE
# ==========================================================

movement_analysis = (
    model_base
    .groupby("Movement Type", dropna=False)
    .agg(
        Employees=("Attrition", "count"),
        Attrition_Count=("Attrition", "sum"),
        Attrition_Rate=("Attrition", "mean")
    )
    .reset_index()
)

movement_analysis["Attrition_Rate_%"] = (
    movement_analysis["Attrition_Rate"] * 100
)

movement_analysis = movement_analysis.sort_values(
    "Attrition_Rate_%",
    ascending=False
)

print("=" * 60)
print("STEP 30: MOVEMENT TYPE vs ATTRITION")
print("=" * 60)

print(
    movement_analysis[
        [
            "Movement Type",
            "Employees",
            "Attrition_Count",
            "Attrition_Rate_%"
        ]
    ].to_string(index=False)
)

============================================================
STEP 30: MOVEMENT TYPE vs ATTRITION
============================================================
    Movement Type  Employees  Attrition_Count  Attrition_Rate_%
      Resignation        175              175        100.000000
Employment Change         72                2          2.777778
        Promotion        185                2          1.081081
         Transfer       2842                7          0.246305
       New Joinee      17194               37          0.215191

In [ ]:

# ==========================================================
# STEP 31: CHECK MOVEMENT TYPE FOR TARGET LEAKAGE
# ==========================================================

print("=" * 60)
print("STEP 31: MOVEMENT TYPE LEAKAGE CHECK")
print("=" * 60)

print("\nMovement Type vs Attrition:")
print(
    pd.crosstab(
        model_base["Movement Type"],
        model_base["Attrition"],
        margins=True
    )
)

print("\n\nMovement Type values:")
print(
    model_base["Movement Type"]
    .value_counts(dropna=False)
)

============================================================
STEP 31: MOVEMENT TYPE LEAKAGE CHECK
============================================================

Movement Type vs Attrition:
Attrition              0    1    All
Movement Type
Employment Change     70    2     72
New Joinee         17157   37  17194
Promotion            183    2    185
Resignation            0  175    175
Transfer            2835    7   2842
All                20245  223  20468


Movement Type values:
Movement Type
New Joinee           17194
Transfer              2842
Promotion              185
Resignation            175
Employment Change       72
Name: count, dtype: int64

In [ ]:

# ============================================================
# STEP 32: REMOVE MOVEMENT TYPE LEAKAGE
# ============================================================

print("=" * 60)
print("STEP 32: REMOVE LEAKAGE FEATURES")
print("=" * 60)

# Create a copy of the modeling dataset
model_base_clean = model_base.copy()

# Remove Movement Type because it directly identifies resignation
leakage_features = [
    "Movement Type"
]

model_base_clean = model_base_clean.drop(
    columns=leakage_features,
    errors="ignore"
)

print("\nRemoved leakage features:")
for col in leakage_features:
    print("-", col)

print("\nNew modeling dataset shape:")
print(model_base_clean.shape)

print("\nTarget distribution:")
print(model_base_clean["Attrition"].value_counts())

print("\nMovement Type present:",
      "Movement Type" in model_base_clean.columns)

============================================================
STEP 32: REMOVE LEAKAGE FEATURES
============================================================

Removed leakage features:
- Movement Type

New modeling dataset shape:
(20468, 139)

Target distribution:
Attrition
0    20245
1      223
Name: count, dtype: int64

Movement Type present: False

In [ ]:

# ============================================================
# STEP 33: REBUILD MODEL INPUTS AFTER LEAKAGE REMOVAL
# ============================================================

print("=" * 60)
print("STEP 33: REBUILD MODEL INPUTS")
print("=" * 60)

# ------------------------------------------------------------
# 1. Separate target
# ------------------------------------------------------------

y_clean = model_base_clean["Attrition"].copy()

X_clean = model_base_clean.drop(
    columns=["Attrition"],
    errors="ignore"
).copy()

# ------------------------------------------------------------
# 2. Safety checks
# ------------------------------------------------------------

print("\nX shape:", X_clean.shape)
print("y shape:", y_clean.shape)

print("\nTarget distribution:")
print(y_clean.value_counts())

print("\nTarget percentage:")
print(
    y_clean.value_counts(normalize=True).mul(100).round(2)
)

# ------------------------------------------------------------
# 3. Check for leakage / identity columns
# ------------------------------------------------------------

leakage_check = [
    "Attrition",
    "Resignation Date",
    "Last Working Date",
    "FNF Settlement Date",
    "Employee Status",
    "Leave Status",
    "Effective End Date",
    "Movement Type"
]

identity_check = [
    "Employee Code",
    "Employee_Code_Clean",
    "_emp_code",
    "First Name",
    "Middle Name",
    "Last Name",
    "Employee Name",
    "Official Email Address",
    "Personal Email Address"
]

print("\nLeakage columns still present:")
print([
    col for col in leakage_check
    if col in X_clean.columns
])

print("\nEmployee identity columns still present:")
print([
    col for col in identity_check
    if col in X_clean.columns
])

# ------------------------------------------------------------
# 4. Verify Movement Type is gone
# ------------------------------------------------------------

assert "Movement Type" not in X_clean.columns

print("\nMovement Type present:", "Movement Type" in X_clean.columns)

# ------------------------------------------------------------
# 5. Separate feature types
# ------------------------------------------------------------

date_columns_clean = [
    col for col in [
        "Actual Join Date",
        "Group Join Date",
        "Confirmation Date",
        "Effective Start Date",
        "Conf. Date (Period Master)",
        "Birth Date",
        "Date Of Joined",
        "Created Date"
    ]
    if col in X_clean.columns
]

categorical_columns_clean = X_clean.select_dtypes(
    include=["object", "string", "category"]
).columns.tolist()

# Remove date columns from categorical list
categorical_columns_clean = [
    col for col in categorical_columns_clean
    if col not in date_columns_clean
]

numeric_columns_clean = X_clean.select_dtypes(
    include=["number", "bool"]
).columns.tolist()

print("\n" + "=" * 60)
print("FEATURE TYPE SUMMARY")
print("=" * 60)

print("\nDate features:", len(date_columns_clean))
for col in date_columns_clean:
    print("-", col)

print("\nCategorical features:", len(categorical_columns_clean))
for col in categorical_columns_clean:
    print("-", col)

print("\nNumeric features:", len(numeric_columns_clean))
for col in numeric_columns_clean:
    print("-", col)

print("\nTotal features accounted for:",
      len(date_columns_clean)
      + len(categorical_columns_clean)
      + len(numeric_columns_clean))

============================================================
STEP 33: REBUILD MODEL INPUTS
============================================================

X shape: (20468, 138)
y shape: (20468,)

Target distribution:
Attrition
0    20245
1      223
Name: count, dtype: int64

Target percentage:
Attrition
0    98.91
1     1.09
Name: proportion, dtype: float64

Leakage columns still present:
['Resignation Date', 'Last Working Date', 'FNF Settlement Date', 'Employee Status', 'Leave Status', 'Effective End Date']

Employee identity columns still present:
['Employee Code', 'Employee_Code_Clean', '_emp_code', 'First Name', 'Middle Name', 'Last Name', 'Employee Name', 'Official Email Address', 'Personal Email Address']

Movement Type present: False

============================================================
FEATURE TYPE SUMMARY
============================================================

Date features: 8
- Actual Join Date
- Group Join Date
- Confirmation Date
- Effective Start Date
- Conf. Date (Period Master)
- Birth Date
- Date Of Joined
- Created Date

Categorical features: 79
- Group
- Company Name
- Employee Code
- Title
- First Name
- Middle Name
- Last Name
- Employee Name
- Gender
- Nationality
- Official Email Address
- Personal Email Address
- Resident Type
- Marital Status
- City Name
- State Name
- Branch
- Site Branch
- Division
- Designation
- Department
- Sub Department
- Cost Center
- Site Cost Center
- Site Name
- Grade
- Band
- Reason for Requirement
- Employee Category
- Employee Status
- Reporting Manager Code
- Reporting Manager Name
- Skip Level Manager Code
- Skip Level Manager
- Physical Disability
- Point of Hire
- Point of Repatriation
- ESIC Flag
- PF Applicable
- PF Type
- PF Number
- UAN Number
- Probation Status
- Source of Hire
- Preferred Name
- Dual Nationality
- Religion
- Employee Air Ticket
- Air Ticket frequency
- Blood Group
- Group Medical Insurance
- Confidential Profile Flag
- 2nd Nationality
- Bank Name
- PAN Number
- Aadhar Card No
- Account Number
- IFSC Code
- Father Name
- Cost Code
- Client Vertical
- Permanent Address
- Current Address
- Correspondence Address
- Resident
- Wage Type
- TAX Regime
- Uniform Deduction
- Employee_Code_Clean
- _emp_code
- Employee Status_form
- Designation_form
- Cost Center_form
- Gender_form
- Marital Status_form
- Location
- Region Name
- Site Name_form
- Client Verticle

Numeric features: 47
- Year Of Service (Current DOJ)
- Year of Service (Group DOJ)
- ESIC Number
- Agreement type
- Effective End Date
- Air Ticket Class
- Confidential Profile
- Employer Notice Period
- Personal Mobile Number
- Emergency Contact Number
- Profit Code
- Leave Status
- Process Name
- Monthly Gross Salary
- Annual_Gross_Salary
- Tenure_Days
- Tenure_Years
- OT1_Chargeable_OT
- OT1_NonChargeable_OT
- OT1_Total_OT
- OT1_OT_Days
- OT1_Avg_Daily_OT
- OT1_Max_Daily_OT
- OT2_Chargeable_OT
- OT2_NonChargeable_OT
- OT2_Total_OT
- OT3_Chargeable_OT
- OT3_NonChargeable_OT
- OT3_Total_OT
- OT4_Chargeable_OT
- OT4_NonChargeable_OT
- OT4_Total_OT
- OT4_OT_Days
- OT4_Avg_Daily_OT
- OT4_Max_Daily_OT
- Leave_Opening_Balance
- Leave_Accrued
- Leave_Consumed
- Leave_Adjustment
- Leave_Lapse
- Leave_Balance
- Leave_Future_Approved
- Leave_Balance_After_Future
- Leave_Encashment
- Leave_Carry_Forward
- Leave_Record_Count
- Leave_Type_Count

Total features accounted for: 134

In [ ]:
# ============================================================
# STEP 34: REBUILD FINAL CLEAN MODEL DATASET
# ============================================================

print("=" * 60)
print("STEP 34: REBUILD FINAL CLEAN MODEL DATASET")
print("=" * 60)

# ------------------------------------------------------------
# FINAL CLEAN FEATURES FROM STEP 21
# ------------------------------------------------------------

final_clean_features = [
    "Title",
    "City Name",
    "State Name",
    "Branch",
    "Site Branch",
    "Designation",
    "Department",
    "Cost Center",
    "Site Cost Center",
    "Site Name",
    "Grade",
    "Band",
    "Reason for Requirement",
    "Employee Category",
    "Reporting Manager Code",
    "Reporting Manager Name",
    "Skip Level Manager Code",
    "Skip Level Manager",
    "Actual Join Date",
    "Group Join Date",
    "Year Of Service (Current DOJ)",
    "Year of Service (Group DOJ)",
    "Point of Hire",
    "Point of Repatriation",
    "ESIC Flag",
    "PF Applicable",
    "PF Type",
    "Probation Status",
    "Confirmation Date",
    "Source of Hire",
    "Effective Start Date",
    "Conf. Date (Period Master)",
    "Employer Notice Period",
    "Bank Name",
    "Birth Date",
    "Cost Code",
    "Profit Code",
    "Client Vertical",
    "Resident",
    "Wage Type",
    "TAX Regime",
    "Uniform Deduction",
    "Location",
    "Region Name",
    "Client Verticle",
    "Date Of Joined",
    "Created Date",
    "Monthly Gross Salary",
    "Annual_Gross_Salary",
    "Tenure_Days",
    "Tenure_Years",
    "OT1_Chargeable_OT",
    "OT1_NonChargeable_OT",
    "OT1_Total_OT",
    "OT1_OT_Days",
    "OT1_Avg_Daily_OT",
    "OT1_Max_Daily_OT",
    "OT2_Chargeable_OT",
    "OT2_NonChargeable_OT",
    "OT2_Total_OT",
    "OT3_Chargeable_OT",
    "OT3_NonChargeable_OT",
    "OT3_Total_OT",
    "OT4_Chargeable_OT",
    "OT4_NonChargeable_OT",
    "OT4_Total_OT",
    "OT4_OT_Days",
    "OT4_Avg_Daily_OT",
    "OT4_Max_Daily_OT",
    "Leave_Opening_Balance",
    "Leave_Accrued",
    "Leave_Consumed",
    "Leave_Balance",
    "Leave_Future_Approved",
    "Leave_Balance_After_Future",
    "Leave_Carry_Forward",
    "Leave_Record_Count",
    "Leave_Type_Count"
]

# ------------------------------------------------------------
# CHECK
# ------------------------------------------------------------

print("\nNumber of final clean features:", len(final_clean_features))

# Make sure Movement Type is NOT included
assert "Movement Type" not in final_clean_features

# Make sure target is NOT included
assert "Attrition" not in final_clean_features

# ------------------------------------------------------------
# KEEP ONLY CLEAN FEATURES + TARGET
# ------------------------------------------------------------

model_data_clean = model_base[
    ["Attrition"] + final_clean_features
].copy()

# ------------------------------------------------------------
# OUTPUT
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("CLEAN MODEL DATASET")
print("=" * 60)

print("\nShape:", model_data_clean.shape)

print("\nTarget distribution:")
print(model_data_clean["Attrition"].value_counts())

print("\nTarget percentage:")
print(
    model_data_clean["Attrition"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

# ------------------------------------------------------------
# SAFETY CHECK
# ------------------------------------------------------------

forbidden_columns = [
    "Movement Type",
    "Resignation Date",
    "Last Working Date",
    "FNF Settlement Date",
    "Employee Status",
    "Leave Status",
    "Effective End Date",
    "Employee Code",
    "Employee_Code_Clean",
    "_emp_code",
    "First Name",
    "Middle Name",
    "Last Name",
    "Employee Name",
    "Official Email Address",
    "Personal Email Address",
    "Personal Mobile Number",
    "Emergency Contact Number",
    "PAN Number",
    "Aadhar Card No",
    "Account Number",
    "IFSC Code",
    "PF Number",
    "UAN Number",
    "ESIC Number",
    "Father Name",
    "Permanent Address",
    "Current Address",
    "Correspondence Address"
]

forbidden_present = [
    col for col in forbidden_columns
    if col in model_data_clean.columns
]

print("\nForbidden/leakage/identity columns present:")
print(forbidden_present)

print("\nMovement Type present:",
      "Movement Type" in model_data_clean.columns)

assert len(forbidden_present) == 0
assert "Movement Type" not in model_data_clean.columns

print("\nSTEP 34 SUCCESS")

============================================================
STEP 34: REBUILD FINAL CLEAN MODEL DATASET
============================================================

Number of final clean features: 78

============================================================
CLEAN MODEL DATASET
============================================================

Shape: (20468, 79)

Target distribution:
Attrition
0    20245
1      223
Name: count, dtype: int64

Target percentage:
Attrition
0    98.91
1     1.09
Name: proportion, dtype: float64

Forbidden/leakage/identity columns present:
[]

Movement Type present: False

STEP 34 SUCCESS

In [ ]:
# ============================================================
# STEP 35: FEATURE ENGINEERING + DATE TRANSFORMATION
# ============================================================

print("=" * 60)
print("STEP 35: FEATURE ENGINEERING + DATE TRANSFORMATION")
print("=" * 60)

# Work from the clean dataset created in Step 34
modeling_data = model_data_clean.copy()

# ------------------------------------------------------------
# 1. Separate target
# ------------------------------------------------------------

y = modeling_data["Attrition"].copy()

X = modeling_data.drop(
    columns=["Attrition"],
    errors="ignore"
).copy()

# ------------------------------------------------------------
# 2. Date columns
# ------------------------------------------------------------

date_columns = [
    "Actual Join Date",
    "Group Join Date",
    "Confirmation Date",
    "Effective Start Date",
    "Conf. Date (Period Master)",
    "Birth Date",
    "Date Of Joined",
    "Created Date"
]

date_columns = [
    col for col in date_columns
    if col in X.columns
]

print("\nDate columns:")
for col in date_columns:
    print("-", col)

# ------------------------------------------------------------
# 3. Convert date columns safely
# ------------------------------------------------------------

for col in date_columns:
    X[col] = pd.to_datetime(
        X[col],
        errors="coerce"
    )

# ------------------------------------------------------------
# 4. Create a fixed reference date
# ------------------------------------------------------------
# Use the latest available date in the dataset.
# This avoids using the current system date and keeps
# the transformation reproducible.

all_dates = []

for col in date_columns:
    valid_dates = X[col].dropna()

    if len(valid_dates) > 0:
        all_dates.append(valid_dates.max())

if all_dates:
    reference_date = max(all_dates)
else:
    reference_date = pd.Timestamp("2026-01-01")

print("\nReference date:", reference_date)

# ------------------------------------------------------------
# 5. Age
# ------------------------------------------------------------

if "Birth Date" in X.columns:

    X["Age_Years"] = (
        (reference_date - X["Birth Date"])
        .dt.days / 365.25
    )

    # Invalid ages become missing
    X.loc[
        (X["Age_Years"] < 15) |
        (X["Age_Years"] > 100),
        "Age_Years"
    ] = np.nan

# ------------------------------------------------------------
# 6. Calculated tenure
# ------------------------------------------------------------

if "Actual Join Date" in X.columns:

    X["Calculated_Tenure_Years"] = (
        (reference_date - X["Actual Join Date"])
        .dt.days / 365.25
    )

    X.loc[
        X["Calculated_Tenure_Years"] < 0,
        "Calculated_Tenure_Years"
    ] = np.nan

# ------------------------------------------------------------
# 7. Confirmation flag
# ------------------------------------------------------------

if "Confirmation Date" in X.columns:

    X["Is_Confirmed"] = (
        X["Confirmation Date"].notna()
        .astype(int)
    )

# ------------------------------------------------------------
# 8. Data availability indicators
# ------------------------------------------------------------

ot_columns = {
    "OT1": "OT1_Total_OT",
    "OT2": "OT2_Total_OT",
    "OT3": "OT3_Total_OT",
    "OT4": "OT4_Total_OT"
}

for prefix, col in ot_columns.items():

    if col in X.columns:
        X[f"{prefix}_Data_Available"] = (
            X[col].notna()
            .astype(int)
        )

# Salary availability
if "Monthly Gross Salary" in X.columns:

    X["Salary_Data_Available"] = (
        X["Monthly Gross Salary"]
        .notna()
        .astype(int)
    )

# Leave availability
if "Leave_Balance" in X.columns:

    X["Leave_Data_Available"] = (
        X["Leave_Balance"]
        .notna()
        .astype(int)
    )

# ------------------------------------------------------------
# 9. Convert dates into numeric day values
# ------------------------------------------------------------

for col in date_columns:

    X[f"{col}_Days"] = (
        X[col] - pd.Timestamp("1970-01-01")
    ).dt.days

    X[f"{col}_Missing"] = (
        X[col].isna()
        .astype(int)
    )

    # Remove original datetime column
    X.drop(
        columns=[col],
        inplace=True
    )

# ------------------------------------------------------------
# 10. Safety checks
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("MODEL INPUT SUMMARY")
print("=" * 60)

print("\nX shape:", X.shape)
print("y shape:", y.shape)

print("\nTarget distribution:")
print(y.value_counts())

print("\nTarget percentage:")
print(
    y.value_counts(normalize=True)
    .mul(100)
    .round(2)
)

print("\nRemaining datetime columns:")
print(
    X.select_dtypes(
        include=["datetime64[ns]", "datetime64[us]"]
    ).columns.tolist()
)

print("\nTarget present in X:", "Attrition" in X.columns)

print(
    "Movement Type present in X:",
    "Movement Type" in X.columns
)

# ------------------------------------------------------------
# 11. Check for forbidden columns
# ------------------------------------------------------------

forbidden_columns = [
    "Attrition",
    "Movement Type",
    "Resignation Date",
    "Last Working Date",
    "FNF Settlement Date",
    "Employee Status",
    "Leave Status",
    "Effective End Date",
    "Employee Code",
    "Employee_Code_Clean",
    "_emp_code",
    "First Name",
    "Middle Name",
    "Last Name",
    "Employee Name",
    "Official Email Address",
    "Personal Email Address",
    "Personal Mobile Number",
    "Emergency Contact Number",
    "PAN Number",
    "Aadhar Card No",
    "Account Number",
    "IFSC Code",
    "PF Number",
    "UAN Number",
    "ESIC Number",
    "Father Name",
    "Permanent Address",
    "Current Address",
    "Correspondence Address"
]

forbidden_present = [
    col for col in forbidden_columns
    if col in X.columns
]

print("\nForbidden columns present:")
print(forbidden_present)

assert len(forbidden_present) == 0

print("\nSTEP 35 SUCCESS")

============================================================
STEP 35: FEATURE ENGINEERING + DATE TRANSFORMATION
============================================================

Date columns:
- Actual Join Date
- Group Join Date
- Confirmation Date
- Effective Start Date
- Conf. Date (Period Master)
- Birth Date
- Date Of Joined
- Created Date

Reference date: 2027-01-23 00:00:00

============================================================
MODEL INPUT SUMMARY
============================================================

X shape: (20468, 95)
y shape: (20468,)

Target distribution:
Attrition
0    20245
1      223
Name: count, dtype: int64

Target percentage:
Attrition
0    98.91
1     1.09
Name: proportion, dtype: float64

Remaining datetime columns:

ValueError: 'datetime64[us]' is too specific of a frequency, try passing 'datetime64'

In [ ]:
# ============================================================
# STEP 35: FEATURE ENGINEERING + DATE TRANSFORMATION
# FIXED FOR datetime64[us]
# ============================================================

print("=" * 60)
print("STEP 35: FEATURE ENGINEERING + DATE TRANSFORMATION")
print("=" * 60)

# ------------------------------------------------------------
# 1. Start from clean dataset
# ------------------------------------------------------------

modeling_data = model_data_clean.copy()

# ------------------------------------------------------------
# 2. Separate target
# ------------------------------------------------------------

y = modeling_data["Attrition"].copy()

X = modeling_data.drop(
    columns=["Attrition"],
    errors="ignore"
).copy()

# ------------------------------------------------------------
# 3. Date columns
# ------------------------------------------------------------

date_columns = [
    "Actual Join Date",
    "Group Join Date",
    "Confirmation Date",
    "Effective Start Date",
    "Conf. Date (Period Master)",
    "Birth Date",
    "Date Of Joined",
    "Created Date"
]

date_columns = [
    col for col in date_columns
    if col in X.columns
]

print("\nDate columns:")
for col in date_columns:
    print("-", col)

# ------------------------------------------------------------
# 4. FIX datetime64[us] -> datetime64[ns]
# ------------------------------------------------------------

for col in date_columns:

    # Convert safely
    X[col] = pd.to_datetime(
        X[col],
        errors="coerce"
    )

    # Explicitly convert datetime unit to nanoseconds
    X[col] = X[col].dt.as_unit("ns")

print("\nDate conversion completed successfully.")


# ============================================================
# CHECK MAX DATE OF EACH DATE COLUMN
# ============================================================

print("=" * 60)
print("MAXIMUM DATE BY DATE COLUMN")
print("=" * 60)

for col in date_columns:
    valid_dates = X[col].dropna()

    if len(valid_dates) > 0:
        print(f"{col:<40} -> {valid_dates.max()}")

# ============================================================
# 5. DETERMINE REFERENCE DATE
# ============================================================

# Use only actual employee/history dates.
# Do NOT use Confirmation Date or Conf. Date (Period Master)
# because they contain future dates up to 2027-01-23.

reference_date_columns = [
    "Actual Join Date",
    "Group Join Date",
    "Effective Start Date",
    "Date Of Joined"
]

reference_dates = []

for col in reference_date_columns:
    if col in X.columns:
        valid_dates = X[col].dropna()

        if len(valid_dates) > 0:
            reference_dates.append(valid_dates.max())

if reference_dates:
    reference_date = max(reference_dates)
else:
    reference_date = pd.Timestamp("2026-01-01")

print("\nReference date:", reference_date)
# ------------------------------------------------------------
# 6. Age
# ------------------------------------------------------------

if "Birth Date" in X.columns:

    X["Age_Years"] = (
        (reference_date - X["Birth Date"])
        .dt.days / 365.25
    )

    X.loc[
        (X["Age_Years"] < 15) |
        (X["Age_Years"] > 100),
        "Age_Years"
    ] = np.nan

# ------------------------------------------------------------
# 7. Calculated tenure
# ------------------------------------------------------------

if "Actual Join Date" in X.columns:

    X["Calculated_Tenure_Years"] = (
        (reference_date - X["Actual Join Date"])
        .dt.days / 365.25
    )

    X.loc[
        X["Calculated_Tenure_Years"] < 0,
        "Calculated_Tenure_Years"
    ] = np.nan

# ------------------------------------------------------------
# 8. Confirmation flag
# ------------------------------------------------------------

if "Confirmation Date" in X.columns:

    X["Is_Confirmed"] = (
        X["Confirmation Date"].notna()
        .astype(int)
    )

# ------------------------------------------------------------
# 9. OT availability
# ------------------------------------------------------------

ot_columns = {
    "OT1": "OT1_Total_OT",
    "OT2": "OT2_Total_OT",
    "OT3": "OT3_Total_OT",
    "OT4": "OT4_Total_OT"
}

for prefix, col in ot_columns.items():

    if col in X.columns:

        X[f"{prefix}_Data_Available"] = (
            X[col].notna()
            .astype(int)
        )

# ------------------------------------------------------------
# 10. Salary availability
# ------------------------------------------------------------

if "Monthly Gross Salary" in X.columns:

    X["Salary_Data_Available"] = (
        X["Monthly Gross Salary"]
        .notna()
        .astype(int)
    )

# ------------------------------------------------------------
# 11. Leave availability
# ------------------------------------------------------------

if "Leave_Balance" in X.columns:

    X["Leave_Data_Available"] = (
        X["Leave_Balance"]
        .notna()
        .astype(int)
    )

# ------------------------------------------------------------
# 12. Convert dates into numeric day values
# ------------------------------------------------------------

epoch = pd.Timestamp("1970-01-01")

for col in date_columns:

    X[f"{col}_Days"] = (
        X[col] - epoch
    ).dt.days

    X[f"{col}_Missing"] = (
        X[col].isna()
        .astype(int)
    )

    # Remove original datetime column
    X.drop(
        columns=[col],
        inplace=True
    )

# ------------------------------------------------------------
# 13. Safety checks
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("MODEL INPUT SUMMARY")
print("=" * 60)

print("\nX shape:", X.shape)
print("y shape:", y.shape)

print("\nTarget distribution:")
print(y.value_counts())

print("\nTarget percentage:")
print(
    y.value_counts(normalize=True)
    .mul(100)
    .round(2)
)

print("\nRemaining datetime columns:")
print(
    X.select_dtypes(
        include=["datetime64"]
    ).columns.tolist()
)

print("\nTarget present in X:")
print("Attrition" in X.columns)

print("\nMovement Type present in X:")
print("Movement Type" in X.columns)

# ------------------------------------------------------------
# 14. Forbidden columns check
# ------------------------------------------------------------

forbidden_columns = [
    "Attrition",
    "Movement Type",
    "Resignation Date",
    "Last Working Date",
    "FNF Settlement Date",
    "Employee Status",
    "Leave Status",
    "Effective End Date",
    "Employee Code",
    "Employee_Code_Clean",
    "_emp_code",
    "First Name",
    "Middle Name",
    "Last Name",
    "Employee Name",
    "Official Email Address",
    "Personal Email Address",
    "Personal Mobile Number",
    "Emergency Contact Number",
    "PAN Number",
    "Aadhar Card No",
    "Account Number",
    "IFSC Code",
    "PF Number",
    "UAN Number",
    "ESIC Number",
    "Father Name",
    "Permanent Address",
    "Current Address",
    "Correspondence Address"
]

forbidden_present = [
    col for col in forbidden_columns
    if col in X.columns
]

print("\nForbidden columns present:")
print(forbidden_present)

assert len(forbidden_present) == 0
assert "Movement Type" not in X.columns
assert "Attrition" not in X.columns

print("\nSTEP 35 SUCCESS")

============================================================
STEP 35: FEATURE ENGINEERING + DATE TRANSFORMATION
============================================================

Date columns:
- Actual Join Date
- Group Join Date
- Confirmation Date
- Effective Start Date
- Conf. Date (Period Master)
- Birth Date
- Date Of Joined
- Created Date

Date conversion completed successfully.
============================================================
MAXIMUM DATE BY DATE COLUMN
============================================================
Actual Join Date                         -> 2026-08-31 00:00:00
Group Join Date                          -> 2026-08-31 00:00:00
Confirmation Date                        -> 2027-01-23 00:00:00
Effective Start Date                     -> 2026-08-31 00:00:00
Conf. Date (Period Master)               -> 2027-01-23 00:00:00
Birth Date                               -> 2009-03-22 00:00:00
Date Of Joined                           -> 2026-08-31 00:00:00
Created Date                             -> 2026-08-07 00:00:00

Reference date: 2026-08-31 00:00:00

============================================================
MODEL INPUT SUMMARY
============================================================

X shape: (20468, 95)
y shape: (20468,)

Target distribution:
Attrition
0    20245
1      223
Name: count, dtype: int64

Target percentage:
Attrition
0    98.91
1     1.09
Name: proportion, dtype: float64

Remaining datetime columns:
[]

Target present in X:
False

Movement Type present in X:
False

Forbidden columns present:
[]

STEP 35 SUCCESS

In [ ]:
# ============================================================
# STEP 35A: CHECK EFFECTIVE START DATE FORMAT
# ============================================================

print("=" * 60)
print("CHECKING EFFECTIVE START DATE")
print("=" * 60)

col = "Effective Start Date"

print("\nOriginal dtype:")
print(model_data_clean[col].dtype)

print("\nSample values:")
print(model_data_clean[col].dropna().head(20).to_list())

print("\nUnique sample values:")
print(model_data_clean[col].dropna().astype(str).unique()[:30])

print("\nValues containing 2-digit year pattern:")
for value in model_data_clean[col].dropna().astype(str).unique():
    if len(value) >= 8:
        print(value)

============================================================
CHECKING EFFECTIVE START DATE
============================================================

Original dtype:
object

Sample values:
[datetime.datetime(2025, 4, 20, 0, 0), datetime.datetime(2022, 12, 15, 0, 0), datetime.datetime(2024, 11, 28, 0, 0), datetime.datetime(2022, 2, 4, 0, 0), datetime.datetime(2018, 10, 12, 0, 0), datetime.datetime(2018, 10, 12, 0, 0), datetime.datetime(2022, 4, 3, 0, 0), datetime.datetime(2024, 3, 12, 0, 0), datetime.datetime(2024, 9, 24, 0, 0), datetime.datetime(2023, 7, 2, 0, 0), datetime.datetime(2022, 9, 2, 0, 0), datetime.datetime(2023, 2, 7, 0, 0), datetime.datetime(2023, 9, 4, 0, 0), datetime.datetime(2023, 12, 12, 0, 0), datetime.datetime(2024, 12, 1, 0, 0), datetime.datetime(2024, 1, 9, 0, 0), datetime.datetime(2025, 4, 4, 0, 0), datetime.datetime(2024, 12, 1, 0, 0), datetime.datetime(2024, 7, 1, 0, 0), datetime.datetime(2024, 2, 27, 0, 0)]

Unique sample values:
<StringArray>
['2025-04-20 00:00:00', '2022-12-15 00:00:00', '2024-11-28 00:00:00',
 '2022-02-04 00:00:00', '2018-10-12 00:00:00', '2022-04-03 00:00:00',
 '2024-03-12 00:00:00', '2024-09-24 00:00:00', '2023-07-02 00:00:00',
 '2022-09-02 00:00:00', '2023-02-07 00:00:00', '2023-09-04 00:00:00',
 '2023-12-12 00:00:00', '2024-12-01 00:00:00', '2024-01-09 00:00:00',
 '2025-04-04 00:00:00', '2024-07-01 00:00:00', '2024-02-27 00:00:00',
 '2024-10-10 00:00:00', '2020-11-01 00:00:00', '2025-07-02 00:00:00',
 '2026-07-01 00:00:00', '2022-06-05 00:00:00', '2026-01-01 00:00:00',
 '2024-01-04 00:00:00', '2024-09-19 00:00:00', '2024-01-08 00:00:00',
 '2022-03-09 00:00:00', '2024-11-06 00:00:00', '2026-04-01 00:00:00']
Length: 30, dtype: str

Values containing 2-digit year pattern:
2025-04-20 00:00:00
2022-12-15 00:00:00
2024-11-28 00:00:00
2022-02-04 00:00:00
2018-10-12 00:00:00
2022-04-03 00:00:00
2024-03-12 00:00:00
2024-09-24 00:00:00
2023-07-02 00:00:00
2022-09-02 00:00:00
2023-02-07 00:00:00
2023-09-04 00:00:00
2023-12-12 00:00:00
2024-12-01 00:00:00
2024-01-09 00:00:00
2025-04-04 00:00:00
2024-07-01 00:00:00
2024-02-27 00:00:00
2024-10-10 00:00:00
2020-11-01 00:00:00
2025-07-02 00:00:00
2026-07-01 00:00:00
2022-06-05 00:00:00
2026-01-01 00:00:00
2024-01-04 00:00:00
2024-09-19 00:00:00
2024-01-08 00:00:00
2022-03-09 00:00:00
2024-11-06 00:00:00
2026-04-01 00:00:00
2021-09-03 00:00:00
2023-03-07 00:00:00
2022-10-16 00:00:00
2024-04-02 00:00:00
2020-06-27 00:00:00
2023-07-22 00:00:00
2025-02-11 00:00:00
2023-03-19 00:00:00
2023-04-24 00:00:00
2024-02-19 00:00:00
2024-11-08 00:00:00
2024-07-17 00:00:00
2020-01-03 00:00:00
2024-06-18 00:00:00
2024-11-20 00:00:00
2023-09-07 00:00:00
2022-10-12 00:00:00
2024-03-20 00:00:00
2024-08-02 00:00:00
2021-11-11 00:00:00
2025-01-16 00:00:00
2023-10-17 00:00:00
2024-06-07 00:00:00
2024-07-07 00:00:00
2023-11-29 00:00:00
2025-01-21 00:00:00
2020-04-10 00:00:00
2021-06-09 00:00:00
2023-01-07 00:00:00
2019-11-11 00:00:00
2024-07-19 00:00:00
2024-08-01 00:00:00
2025-03-03 00:00:00
2024-06-05 00:00:00
2024-06-02 00:00:00
2024-09-10 00:00:00
2024-11-24 00:00:00
2020-11-02 00:00:00
2024-10-01 00:00:00
2023-09-03 00:00:00
2025-03-21 00:00:00
2024-11-01 00:00:00
2023-05-14 00:00:00
2018-10-20 00:00:00
2021-01-10 00:00:00
2024-12-02 00:00:00
2026-05-01 00:00:00
2025-08-26 00:00:00
2025-02-05 00:00:00
2024-10-03 00:00:00
2020-04-07 00:00:00
2023-11-03 00:00:00
2022-09-19 00:00:00
2023-06-08 00:00:00
2025-03-31 00:00:00
2022-02-15 00:00:00
2021-09-04 00:00:00
2023-05-09 00:00:00
2022-09-04 00:00:00
2024-12-17 00:00:00
2024-08-08 00:00:00
2025-02-09 00:00:00
2024-11-25 00:00:00
2022-10-11 00:00:00
2024-03-05 00:00:00
2023-08-10 00:00:00
2024-04-10 00:00:00
2018-10-17 00:00:00
2018-10-13 00:00:00
2025-03-15 00:00:00
2022-06-28 00:00:00
2024-06-04 00:00:00
2026-04-30 00:00:00
2018-10-16 00:00:00
2023-05-13 00:00:00
2025-02-22 00:00:00
2024-12-03 00:00:00
2022-09-07 00:00:00
2022-08-29 00:00:00
2020-10-23 00:00:00
2019-08-23 00:00:00
2024-05-17 00:00:00
2023-05-03 00:00:00
2025-03-05 00:00:00
2026-04-26 00:00:00
2022-10-30 00:00:00
2025-04-30 00:00:00
2022-04-18 00:00:00
2019-12-02 00:00:00
2023-05-05 00:00:00
2021-08-11 00:00:00
2024-11-02 00:00:00
2025-04-02 00:00:00
2024-07-18 00:00:00
2024-05-11 00:00:00
2023-09-13 00:00:00
2023-12-14 00:00:00
2024-08-26 00:00:00
2019-03-09 00:00:00
2022-08-28 00:00:00
2024-04-03 00:00:00
2024-07-25 00:00:00
2023-07-01 00:00:00
2023-12-01 00:00:00
2020-10-22 00:00:00
2020-11-10 00:00:00
2024-01-05 00:00:00
2023-07-18 00:00:00
2020-11-03 00:00:00
2024-07-02 00:00:00
2024-05-13 00:00:00
2025-05-27 00:00:00
2022-11-04 00:00:00
2018-10-14 00:00:00
2018-10-07 00:00:00
2018-10-10 00:00:00
2022-04-02 00:00:00
2024-11-03 00:00:00
2024-10-04 00:00:00
2021-08-10 00:00:00
2024-06-22 00:00:00
2026-06-26 00:00:00
2025-08-02 00:00:00
2021-10-02 00:00:00
2022-05-11 00:00:00
2025-03-30 00:00:00
2025-02-18 00:00:00
2021-08-22 00:00:00
2024-11-29 00:00:00
2022-04-08 00:00:00
2024-11-13 00:00:00
2023-09-05 00:00:00
2019-07-04 00:00:00
2024-08-22 00:00:00
2020-04-12 00:00:00
2022-05-03 00:00:00
2024-10-23 00:00:00
2023-02-08 00:00:00
2023-08-01 00:00:00
2026-04-13 00:00:00
2024-09-03 00:00:00
2026-03-27 00:00:00
2023-04-17 00:00:00
2018-07-11 00:00:00
2020-09-15 00:00:00
2023-06-10 00:00:00
2018-08-29 00:00:00
2023-06-16 00:00:00
2023-06-23 00:00:00
2025-02-03 00:00:00
2025-01-03 00:00:00
2024-09-25 00:00:00
2026-06-01 00:00:00
2023-06-29 00:00:00
2023-08-28 00:00:00
2025-02-08 00:00:00
2023-09-12 00:00:00
2020-10-28 00:00:00
2023-03-01 00:00:00
2021-03-29 00:00:00
2024-03-24 00:00:00
2025-02-12 00:00:00
2020-10-29 00:00:00
2020-04-04 00:00:00
2024-11-05 00:00:00
2024-01-18 00:00:00
2018-07-12 00:00:00
2023-07-17 00:00:00
2025-02-10 00:00:00
2023-12-02 00:00:00
2022-03-16 00:00:00
2019-04-09 00:00:00
2023-09-29 00:00:00
2024-10-05 00:00:00
2026-08-06 00:00:00
2023-10-03 00:00:00
2023-06-27 00:00:00
2024-08-05 00:00:00
2020-10-30 00:00:00
2024-08-23 00:00:00
2024-05-21 00:00:00
2025-02-20 00:00:00
2024-03-02 00:00:00
2024-12-25 00:00:00
2018-07-10 00:00:00
2020-04-09 00:00:00
2019-09-27 00:00:00
2024-01-30 00:00:00
2023-12-03 00:00:00
2019-06-11 00:00:00
2021-08-23 00:00:00
2021-11-07 00:00:00
2021-12-29 00:00:00
2023-03-03 00:00:00
2024-06-29 00:00:00
2019-12-23 00:00:00
2023-07-30 00:00:00
2022-11-12 00:00:00
2023-02-03 00:00:00
2025-06-02 00:00:00
2023-02-27 00:00:00
2024-07-16 00:00:00
2023-08-02 00:00:00
2026-07-18 00:00:00
2025-02-17 00:00:00
2020-09-03 00:00:00
2023-04-08 00:00:00
2021-12-30 00:00:00
2023-03-05 00:00:00
2023-05-02 00:00:00
2023-09-14 00:00:00
2025-12-26 00:00:00
2019-02-08 00:00:00
2023-08-29 00:00:00
2023-01-22 00:00:00
2024-04-04 00:00:00
2025-01-23 00:00:00
2022-04-06 00:00:00
2024-08-04 00:00:00
2022-08-02 00:00:00
2024-04-16 00:00:00
2024-05-03 00:00:00
2024-05-10 00:00:00
2024-12-20 00:00:00
2019-03-12 00:00:00
2022-09-18 00:00:00
2023-03-11 00:00:00
2021-12-03 00:00:00
2025-01-04 00:00:00
2021-10-07 00:00:00
2024-04-18 00:00:00
2024-02-14 00:00:00
2024-08-31 00:00:00
2023-03-16 00:00:00
2024-05-24 00:00:00
2025-01-13 00:00:00
2025-02-19 00:00:00
2023-06-17 00:00:00
2026-04-20 00:00:00
2024-02-02 00:00:00
2021-05-14 00:00:00
2018-10-15 00:00:00
2022-11-03 00:00:00
2024-04-30 00:00:00
2024-08-27 00:00:00
2023-09-06 00:00:00
2020-12-08 00:00:00
2024-02-12 00:00:00
2024-01-02 00:00:00
2020-02-01 00:00:00
2026-03-11 00:00:00
2024-09-21 00:00:00
2023-02-04 00:00:00
2025-04-23 00:00:00
2020-11-05 00:00:00
2025-04-09 00:00:00
2021-11-06 00:00:00
2022-04-22 00:00:00
2025-03-23 00:00:00
2024-02-26 00:00:00
2024-11-22 00:00:00
2025-03-08 00:00:00
2025-03-06 00:00:00
2023-02-23 00:00:00
2023-08-06 00:00:00
2026-05-27 00:00:00
2024-01-27 00:00:00
2021-08-31 00:00:00
2020-11-12 00:00:00
2023-01-21 00:00:00
2024-11-12 00:00:00
2022-10-07 00:00:00
2024-05-02 00:00:00
2022-09-13 00:00:00
2022-11-01 00:00:00
2023-04-02 00:00:00
2020-01-29 00:00:00
2025-02-01 00:00:00
2018-10-18 00:00:00
2024-02-13 00:00:00
2024-04-27 00:00:00
2024-10-26 00:00:00
2021-11-21 00:00:00
2022-12-01 00:00:00
2024-04-26 00:00:00
2024-06-25 00:00:00
2023-02-22 00:00:00
2023-10-26 00:00:00
2023-11-16 00:00:00
2020-11-20 00:00:00
2024-03-18 00:00:00
2023-07-13 00:00:00
2021-04-22 00:00:00
2023-08-27 00:00:00
2023-07-27 00:00:00
2024-09-17 00:00:00
2022-11-06 00:00:00
2023-12-13 00:00:00
2024-05-07 00:00:00
2022-06-03 00:00:00
2025-03-04 00:00:00
2023-08-26 00:00:00
2023-10-21 00:00:00
2024-11-26 00:00:00
2024-09-01 00:00:00
2024-09-18 00:00:00
2020-01-27 00:00:00
2022-05-05 00:00:00
2021-03-09 00:00:00
2020-11-06 00:00:00
2022-01-08 00:00:00
2022-10-03 00:00:00
2023-05-06 00:00:00
2023-09-15 00:00:00
2014-10-23 00:00:00
2023-11-25 00:00:00
2023-09-20 00:00:00
2024-05-16 00:00:00
2020-07-07 00:00:00
2025-03-01 00:00:00
2022-09-20 00:00:00
2024-12-04 00:00:00
2022-05-28 00:00:00
2022-08-27 00:00:00
2023-12-26 00:00:00
2021-11-30 00:00:00
2024-07-11 00:00:00
2021-01-09 00:00:00
2024-03-17 00:00:00
2024-03-29 00:00:00
2025-04-24 00:00:00
2022-04-04 00:00:00
2023-01-20 00:00:00
2022-04-07 00:00:00
2020-04-05 00:00:00
2024-03-04 00:00:00
2019-07-20 00:00:00
2019-01-31 00:00:00
2023-07-19 00:00:00
2025-04-03 00:00:00
2022-04-12 00:00:00
2021-04-24 00:00:00
2022-03-07 00:00:00
2021-08-19 00:00:00
2020-11-04 00:00:00
2021-08-30 00:00:00
2022-02-03 00:00:00
2022-11-17 00:00:00
2021-02-05 00:00:00
2019-04-16 00:00:00
2026-05-22 00:00:00
2020-09-23 00:00:00
2021-08-16 00:00:00
2021-08-24 00:00:00
2024-01-17 00:00:00
2023-01-19 00:00:00
2023-01-25 00:00:00
2024-12-12 00:00:00
2024-06-03 00:00:00
2024-03-22 00:00:00
2021-03-03 00:00:00
2021-05-04 00:00:00
2024-10-08 00:00:00
2022-03-26 00:00:00
2023-02-14 00:00:00
2024-07-15 00:00:00
2020-10-31 00:00:00
2025-03-07 00:00:00
2022-09-26 00:00:00
2023-06-02 00:00:00
2025-03-12 00:00:00
2025-01-11 00:00:00
2022-07-21 00:00:00
2023-08-09 00:00:00
2023-01-24 00:00:00
2022-10-09 00:00:00
2023-02-26 00:00:00
2024-08-03 00:00:00
2023-05-17 00:00:00
2022-01-06 00:00:00
2024-06-15 00:00:00
2021-09-02 00:00:00
2024-03-26 00:00:00
2024-11-04 00:00:00
2023-01-30 00:00:00
2024-12-31 00:00:00
2019-04-27 00:00:00
2021-02-27 00:00:00
2024-12-05 00:00:00
2024-12-15 00:00:00
2022-04-29 00:00:00
2024-04-22 00:00:00
2021-04-04 00:00:00
2022-11-09 00:00:00
2023-08-20 00:00:00
2023-08-22 00:00:00
2024-09-04 00:00:00
2025-04-29 00:00:00
2022-06-04 00:00:00
2023-12-21 00:00:00
2022-11-15 00:00:00
2023-01-03 00:00:00
2025-03-14 00:00:00
2024-10-25 00:00:00
2018-10-19 00:00:00
2020-10-26 00:00:00
2024-03-08 00:00:00
2022-12-19 00:00:00
2023-12-08 00:00:00
2023-02-11 00:00:00
2023-12-15 00:00:00
2024-03-14 00:00:00
2024-10-09 00:00:00
2020-12-10 00:00:00
2023-02-25 00:00:00
2024-05-14 00:00:00
2025-03-26 00:00:00
2023-09-02 00:00:00
2024-08-25 00:00:00
2025-04-06 00:00:00
2023-09-11 00:00:00
2019-06-10 00:00:00
2021-03-26 00:00:00
2024-01-01 00:00:00
2023-04-28 00:00:00
2022-10-14 00:00:00
2022-10-21 00:00:00
2024-02-28 00:00:00
2023-05-08 00:00:00
2019-04-13 00:00:00
2024-11-21 00:00:00
2022-10-31 00:00:00
2022-11-22 00:00:00
2023-10-02 00:00:00
2023-12-23 00:00:00
2024-03-07 00:00:00
2023-05-18 00:00:00
2020-04-18 00:00:00
2025-04-08 00:00:00
2020-05-21 00:00:00
2020-10-24 00:00:00
2024-03-01 00:00:00
2023-09-18 00:00:00
2024-02-16 00:00:00
2025-02-02 00:00:00
2019-10-18 00:00:00
2025-04-01 00:00:00
2025-03-13 00:00:00
2024-12-24 00:00:00
2021-08-02 00:00:00
2023-04-06 00:00:00
2025-04-28 00:00:00
2025-03-02 00:00:00
2023-03-22 00:00:00
2024-04-19 00:00:00
2024-10-02 00:00:00
2025-02-14 00:00:00
2022-11-23 00:00:00
2023-03-12 00:00:00
2019-01-04 00:00:00
2020-04-06 00:00:00
2021-04-11 00:00:00
2022-12-02 00:00:00
2020-01-24 00:00:00
2022-02-13 00:00:00
2024-04-08 00:00:00
2024-03-11 00:00:00
2024-02-21 00:00:00
2024-06-10 00:00:00
2023-02-17 00:00:00
2019-11-25 00:00:00
2023-02-19 00:00:00
2020-07-05 00:00:00
2025-02-21 00:00:00
2023-03-04 00:00:00
2020-05-28 00:00:00
2020-12-26 00:00:00
2024-07-04 00:00:00
2022-07-07 00:00:00
2023-07-08 00:00:00
2025-02-07 00:00:00
2024-02-10 00:00:00
2022-05-04 00:00:00
2025-04-17 00:00:00
2024-03-27 00:00:00
2023-05-30 00:00:00
2022-04-21 00:00:00
2023-11-17 00:00:00
2026-05-26 00:00:00
2022-06-13 00:00:00
2026-02-16 00:00:00
2024-10-15 00:00:00
2023-12-09 00:00:00
2020-09-21 00:00:00
2024-12-26 00:00:00
2024-06-13 00:00:00
2024-01-12 00:00:00
2024-07-29 00:00:00
2022-05-21 00:00:00
2021-10-13 00:00:00
2024-01-15 00:00:00
2022-02-12 00:00:00
2019-04-04 00:00:00
2023-11-18 00:00:00
2023-08-05 00:00:00
2020-11-07 00:00:00
2020-07-17 00:00:00
2024-05-20 00:00:00
2024-11-15 00:00:00
2023-10-12 00:00:00
2023-06-05 00:00:00
2024-02-08 00:00:00
2023-07-12 00:00:00
2025-04-16 00:00:00
2022-05-22 00:00:00
2022-05-20 00:00:00
2025-03-29 00:00:00
2022-03-06 00:00:00
2022-01-11 00:00:00
2021-10-26 00:00:00
2022-02-07 00:00:00
2025-03-18 00:00:00
2024-06-12 00:00:00
2020-11-08 00:00:00
2023-12-07 00:00:00
2023-10-07 00:00:00
2020-03-09 00:00:00
2023-01-27 00:00:00
2022-04-23 00:00:00
2024-01-07 00:00:00
2024-12-29 00:00:00
2023-06-12 00:00:00
2025-01-06 00:00:00
2025-01-14 00:00:00
2023-10-14 00:00:00
2024-06-28 00:00:00
2023-01-14 00:00:00
2022-08-22 00:00:00
2023-05-27 00:00:00
2022-05-08 00:00:00
2023-05-04 00:00:00
2023-12-05 00:00:00
2023-02-09 00:00:00
2023-07-11 00:00:00
2024-01-06 00:00:00
2023-02-10 00:00:00
2020-08-02 00:00:00
2018-07-09 00:00:00
2024-07-31 00:00:00
2024-05-23 00:00:00
2025-04-11 00:00:00
2023-06-13 00:00:00
2023-06-20 00:00:00
2019-05-07 00:00:00
2024-02-15 00:00:00
2024-10-07 00:00:00
2024-04-24 00:00:00
2023-02-18 00:00:00
2022-07-09 00:00:00
2024-11-18 00:00:00
2024-02-17 00:00:00
2024-03-15 00:00:00
2022-06-30 00:00:00
2022-05-18 00:00:00
2023-09-01 00:00:00
2023-12-04 00:00:00
2023-09-08 00:00:00
2022-03-15 00:00:00
2024-12-13 00:00:00
2021-09-30 00:00:00
2023-09-17 00:00:00
2023-06-26 00:00:00
2022-05-27 00:00:00
2023-11-28 00:00:00
2023-05-23 00:00:00
2021-10-10 00:00:00
2024-12-06 00:00:00
2021-09-11 00:00:00
2023-09-21 00:00:00
2021-05-05 00:00:00
2022-05-02 00:00:00
2019-07-14 00:00:00
2025-02-27 00:00:00
2022-05-29 00:00:00
2024-03-16 00:00:00
2023-08-11 00:00:00
2021-04-06 00:00:00
2022-10-13 00:00:00
2024-11-19 00:00:00
2023-01-10 00:00:00
2024-09-07 00:00:00
2024-12-10 00:00:00
2021-07-08 00:00:00
2022-03-03 00:00:00
2018-09-12 00:00:00
2019-09-24 00:00:00
2024-08-28 00:00:00
2020-01-14 00:00:00
2024-07-08 00:00:00
2024-12-11 00:00:00
2023-04-25 00:00:00
2025-02-04 00:00:00
2022-12-16 00:00:00
2021-11-23 00:00:00
2022-07-20 00:00:00
2022-11-07 00:00:00
2023-02-02 00:00:00
2025-06-03 00:00:00
2025-06-07 00:00:00
2025-07-11 00:00:00
2025-06-13 00:00:00
2025-07-26 00:00:00
2025-06-01 00:00:00
2025-07-10 00:00:00
2025-07-24 00:00:00
2025-05-26 00:00:00
2025-07-19 00:00:00
2025-06-24 00:00:00
2025-06-04 00:00:00
2025-06-06 00:00:00
2025-07-12 00:00:00
2025-07-25 00:00:00
2025-04-22 00:00:00
2025-07-15 00:00:00
2025-06-20 00:00:00
2025-07-31 00:00:00
2025-08-01 00:00:00
2025-07-14 00:00:00
2025-05-07 00:00:00
2025-07-13 00:00:00
2025-07-01 00:00:00
2025-05-29 00:00:00
2025-06-10 00:00:00
2025-05-13 00:00:00
2025-06-11 00:00:00
2025-06-05 00:00:00
2025-04-25 00:00:00
2025-05-10 00:00:00
2025-05-21 00:00:00
2025-06-17 00:00:00
2025-05-08 00:00:00
2025-08-07 00:00:00
2025-05-05 00:00:00
2025-05-24 00:00:00
2025-06-23 00:00:00
2025-04-26 00:00:00
2025-05-20 00:00:00
2025-05-16 00:00:00
2025-05-04 00:00:00
2025-07-16 00:00:00
2025-06-28 00:00:00
2025-07-03 00:00:00
2025-05-19 00:00:00
2025-07-27 00:00:00
2025-08-05 00:00:00
2025-05-15 00:00:00
2025-06-26 00:00:00
2025-06-18 00:00:00
2025-05-31 00:00:00
2025-07-08 00:00:00
2025-06-16 00:00:00
2025-07-07 00:00:00
2025-06-12 00:00:00
2025-05-28 00:00:00
2026-05-14 00:00:00
2025-08-04 00:00:00
2025-07-04 00:00:00
2025-05-01 00:00:00
2026-04-11 00:00:00
2025-07-21 00:00:00
2025-07-20 00:00:00
2025-07-22 00:00:00
2025-07-05 00:00:00
2025-05-09 00:00:00
2026-06-08 00:00:00
2025-07-30 00:00:00
2025-07-29 00:00:00
2025-06-25 00:00:00
2025-05-12 00:00:00
2025-09-16 00:00:00
2025-09-08 00:00:00
2025-09-01 00:00:00
2025-10-08 00:00:00
2025-09-25 00:00:00
2025-09-23 00:00:00
2025-09-12 00:00:00
2025-09-07 00:00:00
2026-05-29 00:00:00
2025-09-26 00:00:00
2025-09-09 00:00:00
2025-09-21 00:00:00
2025-09-02 00:00:00
2025-09-04 00:00:00
2025-10-01 00:00:00
2025-10-02 00:00:00
2025-09-24 00:00:00
2025-10-15 00:00:00
2025-09-10 00:00:00
2025-09-30 00:00:00
2025-08-21 00:00:00
2025-08-06 00:00:00
2025-08-08 00:00:00
2025-08-15 00:00:00
2025-08-13 00:00:00
2025-08-16 00:00:00
2025-08-14 00:00:00
2025-08-10 00:00:00
2025-08-12 00:00:00
2025-08-03 00:00:00
2025-08-20 00:00:00
2025-08-18 00:00:00
2025-08-19 00:00:00
2025-09-03 00:00:00
2025-09-05 00:00:00
2026-06-27 00:00:00
2026-05-30 00:00:00
2026-07-26 00:00:00
2025-10-16 00:00:00
2025-10-17 00:00:00
2025-10-20 00:00:00
2025-10-21 00:00:00
2025-10-27 00:00:00
2025-10-26 00:00:00
2025-10-28 00:00:00
2025-10-30 00:00:00
2025-10-04 00:00:00
2025-10-29 00:00:00
2025-10-14 00:00:00
2025-10-25 00:00:00
2026-03-01 00:00:00
2025-10-11 00:00:00
2025-11-06 00:00:00
2026-03-03 00:00:00
2025-11-03 00:00:00
2025-11-02 00:00:00
2025-11-04 00:00:00
2026-04-25 00:00:00
2025-11-07 00:00:00
2025-11-08 00:00:00
2025-11-11 00:00:00
2025-11-10 00:00:00
2026-01-14 00:00:00
2025-11-13 00:00:00
2025-11-12 00:00:00
2025-11-15 00:00:00
2025-11-17 00:00:00
2025-11-19 00:00:00
2025-11-27 00:00:00
2025-11-18 00:00:00
2025-11-01 00:00:00
2025-11-21 00:00:00
2025-11-26 00:00:00
2025-11-25 00:00:00
2025-11-23 00:00:00
2025-11-20 00:00:00
2025-11-28 00:00:00
2025-12-01 00:00:00
2025-12-02 00:00:00
2025-12-03 00:00:00
2025-12-06 00:00:00
2025-12-20 00:00:00
2025-12-22 00:00:00
2025-12-23 00:00:00
2025-12-17 00:00:00
2025-12-18 00:00:00
2025-12-04 00:00:00
2025-12-05 00:00:00
2025-12-19 00:00:00
2025-12-09 00:00:00
2025-12-07 00:00:00
2025-12-14 00:00:00
2025-12-15 00:00:00
2026-05-04 00:00:00
2026-08-01 00:00:00
2025-12-27 00:00:00
2025-12-11 00:00:00
2026-05-28 00:00:00
2026-01-02 00:00:00
2026-01-06 00:00:00
2026-01-04 00:00:00
2026-01-03 00:00:00
2025-12-24 00:00:00
2025-12-31 00:00:00
2026-01-07 00:00:00
2026-01-05 00:00:00
2026-01-13 00:00:00
2026-04-22 00:00:00
2026-01-10 00:00:00
2026-01-19 00:00:00
2026-01-09 00:00:00
2026-04-02 00:00:00
2026-01-12 00:00:00
2026-01-24 00:00:00
2026-01-16 00:00:00
2026-01-08 00:00:00
2026-01-28 00:00:00
2026-01-27 00:00:00
2026-02-02 00:00:00
2026-02-01 00:00:00
2026-01-25 00:00:00
2026-01-29 00:00:00
2026-02-04 00:00:00
2026-01-31 00:00:00
2026-02-05 00:00:00
2026-02-09 00:00:00
2026-02-06 00:00:00
2026-02-07 00:00:00
2026-02-10 00:00:00
2026-02-12 00:00:00
2026-02-11 00:00:00
2026-02-15 00:00:00
2026-02-13 00:00:00
2026-04-12 00:00:00
2026-02-19 00:00:00
2026-02-14 00:00:00
2026-02-21 00:00:00
2026-02-20 00:00:00
2026-02-23 00:00:00
2026-02-24 00:00:00
2026-02-25 00:00:00
2026-04-08 00:00:00
2026-02-27 00:00:00
2026-03-02 00:00:00
2026-02-26 00:00:00
2026-03-09 00:00:00
2026-03-05 00:00:00
2026-03-04 00:00:00
2026-03-12 00:00:00
2026-03-10 00:00:00
2026-03-17 00:00:00
2026-03-07 00:00:00
2026-03-16 00:00:00
2026-03-15 00:00:00
2026-03-20 00:00:00
2026-03-13 00:00:00
2026-03-19 00:00:00
2026-03-23 00:00:00
2026-03-26 00:00:00
2026-03-25 00:00:00
2026-03-24 00:00:00
2026-03-06 00:00:00
2026-04-03 00:00:00
2026-04-09 00:00:00
2026-04-10 00:00:00
2026-04-06 00:00:00
2026-06-02 00:00:00
2026-04-15 00:00:00
2026-03-31 00:00:00
2026-04-16 00:00:00
2026-04-17 00:00:00
2026-04-05 00:00:00
2026-04-24 00:00:00
2026-04-04 00:00:00
2026-04-28 00:00:00
2026-06-03 00:00:00
2026-04-14 00:00:00
2026-04-27 00:00:00
2026-04-23 00:00:00
2026-04-18 00:00:00
2026-05-06 00:00:00
2026-05-02 00:00:00
2026-05-15 00:00:00
2026-05-05 00:00:00
2026-05-09 00:00:00
2026-05-12 00:00:00
2026-05-11 00:00:00
2026-05-16 00:00:00
2026-05-13 00:00:00
2026-05-10 00:00:00
2026-05-07 00:00:00
2026-05-18 00:00:00
2026-05-20 00:00:00
2026-05-19 00:00:00
2026-05-21 00:00:00
2026-05-08 00:00:00
2026-05-25 00:00:00
2026-05-23 00:00:00
2026-04-29 00:00:00
2026-06-13 00:00:00
2026-05-03 00:00:00
2026-05-24 00:00:00
2026-06-04 00:00:00

In [ ]:
# ============================================================
# STEP 35: FIX MALFORMED EFFECTIVE START DATE
# ============================================================

import pandas as pd
import numpy as np
from datetime import datetime

col = "Effective Start Date"

print("=" * 60)
print("FIXING EFFECTIVE START DATE")
print("=" * 60)

# ------------------------------------------------------------
# 1. Find suspicious year values
# ------------------------------------------------------------

suspicious = []

for idx, value in model_data_clean[col].items():
    if pd.isna(value):
        continue

    text = str(value)

    # Detect years such as 0025, 0024, etc.
    if any(f"-{year:04d}-" in text for year in range(1, 100)):
        suspicious.append((idx, value))

print(f"\nSuspicious date values found: {len(suspicious)}")

for idx, value in suspicious[:20]:
    print(f"Index: {idx} | Value: {value}")


# ------------------------------------------------------------
# 2. Correct the known malformed date
# ------------------------------------------------------------

for idx, value in suspicious:
    text = str(value)

    if text == "01-DEC-0025":
        model_data_clean.at[idx, col] = datetime(2025, 12, 1)

        print(
            f"\nCorrected index {idx}: "
            f"{value} -> 2025-12-01"
        )


# ------------------------------------------------------------
# 3. Convert the complete column safely
# ------------------------------------------------------------

model_data_clean[col] = pd.to_datetime(
    model_data_clean[col],
    errors="coerce"
)


# ------------------------------------------------------------
# 4. Validation
# ------------------------------------------------------------

print("\nFinal dtype:")
print(model_data_clean[col].dtype)

print("\nMissing dates after conversion:")
print(model_data_clean[col].isna().sum())

print("\nMinimum date:")
print(model_data_clean[col].min())

print("\nMaximum date:")
print(model_data_clean[col].max())

print("\nDate conversion completed successfully.")

============================================================
FIXING EFFECTIVE START DATE
============================================================

Suspicious date values found: 0

Final dtype:
datetime64[us]

Missing dates after conversion:
0

Minimum date:
0025-12-01 00:00:00

Maximum date:
2026-08-31 00:00:00

Date conversion completed successfully.

In [ ]:
# ============================================================
# STEP 35B: FIX YEAR 0025 IN EFFECTIVE START DATE
# ============================================================

col = "Effective Start Date"

print("=" * 60)
print("CHECKING FOR INVALID YEAR VALUES")
print("=" * 60)

# Find dates where year is less than 1900
invalid_mask = model_data_clean[col].notna() & (
    model_data_clean[col].dt.year < 1900
)

print(f"\nInvalid date rows found: {invalid_mask.sum()}")

if invalid_mask.sum() > 0:
    print("\nInvalid dates found:")
    print(model_data_clean.loc[invalid_mask, col].value_counts())

    # Specifically fix year 0025 -> 2025
    def fix_invalid_year(x):
        if pd.isna(x):
            return x

        if x.year == 25:
            return x.replace(year=2025)

        return x

    model_data_clean[col] = model_data_clean[col].apply(fix_invalid_year)

    print("\nCorrected year 0025 -> 2025")

# Convert to standard pandas datetime
model_data_clean[col] = pd.to_datetime(
    model_data_clean[col],
    errors="coerce"
)

print("\n" + "=" * 60)
print("VALIDATION")
print("=" * 60)

print("\nDtype:")
print(model_data_clean[col].dtype)

print("\nMinimum date:")
print(model_data_clean[col].min())

print("\nMaximum date:")
print(model_data_clean[col].max())

print("\nDates before 1900:")
print(
    (model_data_clean[col].notna() &
     (model_data_clean[col].dt.year < 1900)).sum()
)

print("\nMissing dates:")
print(model_data_clean[col].isna().sum())

print("\nDate correction completed successfully.")

============================================================
CHECKING FOR INVALID YEAR VALUES
============================================================

Invalid date rows found: 21

Invalid dates found:
Effective Start Date
25-12-01    21
Name: count, dtype: int64

Corrected year 0025 -> 2025

============================================================
VALIDATION
============================================================

Dtype:
datetime64[us]

Minimum date:
2014-10-23 00:00:00

Maximum date:
2026-08-31 00:00:00

Dates before 1900:
0

Missing dates:
0

Date correction completed successfully.

In [ ]:
# ============================================================
# STEP 36: TRAIN / TEST SPLIT
# ============================================================

from sklearn.model_selection import train_test_split

print("=" * 60)
print("STEP 36: TRAIN / TEST SPLIT")
print("=" * 60)

# ------------------------------------------------------------
# 1. Verify X and y
# ------------------------------------------------------------

print("\nInput shapes:")
print("X:", X.shape)
print("y:", y.shape)

print("\nTarget distribution:")
print(y.value_counts())

print("\nTarget percentage:")
print((y.value_counts(normalize=True) * 100).round(2))


# ------------------------------------------------------------
# 2. Train / Test split
# ------------------------------------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)


# ------------------------------------------------------------
# 3. Check resulting shapes
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("SPLIT RESULTS")
print("=" * 60)

print("\nX_train shape:", X_train.shape)
print("X_test shape :", X_test.shape)

print("y_train shape:", y_train.shape)
print("y_test shape :", y_test.shape)


# ------------------------------------------------------------
# 4. Check target distribution in both sets
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("TRAIN TARGET DISTRIBUTION")
print("=" * 60)

print(y_train.value_counts())
print("\nPercentage:")
print((y_train.value_counts(normalize=True) * 100).round(2))


print("\n" + "=" * 60)
print("TEST TARGET DISTRIBUTION")
print("=" * 60)

print(y_test.value_counts())
print("\nPercentage:")
print((y_test.value_counts(normalize=True) * 100).round(2))


print("\n" + "=" * 60)
print("STEP 36 SUCCESS")
print("=" * 60)

============================================================
STEP 36: TRAIN / TEST SPLIT
============================================================

Input shapes:
X: (20468, 95)
y: (20468,)

Target distribution:
Attrition
0    20245
1      223
Name: count, dtype: int64

Target percentage:
Attrition
0    98.91
1     1.09
Name: proportion, dtype: float64

============================================================
SPLIT RESULTS
============================================================

X_train shape: (16374, 95)
X_test shape : (4094, 95)
y_train shape: (16374,)
y_test shape : (4094,)

============================================================
TRAIN TARGET DISTRIBUTION
============================================================
Attrition
0    16196
1      178
Name: count, dtype: int64

Percentage:
Attrition
0    98.91
1     1.09
Name: proportion, dtype: float64

============================================================
TEST TARGET DISTRIBUTION
============================================================
Attrition
0    4049
1      45
Name: count, dtype: int64

Percentage:
Attrition
0    98.9
1     1.1
Name: proportion, dtype: float64

============================================================
STEP 36 SUCCESS
============================================================

In [ ]:
# ============================================================
# STEP 37: RANDOM FOREST MODEL PREPARATION
# ============================================================

from sklearn.ensemble import RandomForestClassifier

print("=" * 60)
print("STEP 37: RANDOM FOREST MODEL PREPARATION")
print("=" * 60)

# ------------------------------------------------------------
# 1. Check data types
# ------------------------------------------------------------

print("\nChecking X_train data types...")

print("\nNumeric columns:",
      X_train.select_dtypes(include=["number"]).shape[1])

print("Non-numeric columns:",
      X_train.select_dtypes(exclude=["number"]).shape[1])


# ------------------------------------------------------------
# 2. Check missing values
# ------------------------------------------------------------

print("\nTotal missing values in X_train:",
      X_train.isna().sum().sum())

print("Total missing values in X_test:",
      X_test.isna().sum().sum())


# ------------------------------------------------------------
# 3. Create Random Forest
# ------------------------------------------------------------

rf_model = RandomForestClassifier(
    n_estimators=300,
    max_depth=None,
    min_samples_split=5,
    min_samples_leaf=2,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

print("\nRandom Forest configuration:")
print(rf_model)


print("\n" + "=" * 60)
print("STEP 37 SUCCESS")
print("=" * 60)

============================================================
STEP 37: RANDOM FOREST MODEL PREPARATION
============================================================

Checking X_train data types...

Numeric columns: 60
Non-numeric columns: 35

Total missing values in X_train: 400071
Total missing values in X_test: 100315

Random Forest configuration:
RandomForestClassifier(class_weight='balanced', min_samples_leaf=2,
                       min_samples_split=5, n_estimators=300, n_jobs=-1,
                       random_state=42)

============================================================
STEP 37 SUCCESS
============================================================

In [ ]:
# ============================================================
# STEP 38: INSPECT NON-NUMERIC AND MISSING FEATURES
# ============================================================

print("=" * 60)
print("STEP 38: FEATURE TYPE & MISSING VALUE INSPECTION")
print("=" * 60)


# ------------------------------------------------------------
# 1. Non-numeric columns
# ------------------------------------------------------------

non_numeric_cols = X_train.select_dtypes(
    exclude=["number"]
).columns.tolist()

print("\n" + "=" * 60)
print("NON-NUMERIC COLUMNS")
print("=" * 60)

print("Count:", len(non_numeric_cols))

for i, col in enumerate(non_numeric_cols, 1):
    print(f"{i:02d}. {col}")


# ------------------------------------------------------------
# 2. Missing values by column
# ------------------------------------------------------------

missing_summary = X_train.isna().sum()

missing_summary = missing_summary[
    missing_summary > 0
].sort_values(ascending=False)


print("\n" + "=" * 60)
print("MISSING VALUES BY COLUMN")
print("=" * 60)

print(missing_summary.to_string())


# ------------------------------------------------------------
# 3. Missing percentage
# ------------------------------------------------------------

missing_percentage = (
    X_train.isna().mean() * 100
).sort_values(ascending=False)

missing_percentage = missing_percentage[
    missing_percentage > 0
]


print("\n" + "=" * 60)
print("MISSING PERCENTAGE BY COLUMN")
print("=" * 60)

print(missing_percentage.round(2).to_string())


# ------------------------------------------------------------
# 4. High-missing columns
# ------------------------------------------------------------

high_missing = missing_percentage[
    missing_percentage >= 50
]

print("\n" + "=" * 60)
print("COLUMNS WITH >= 50% MISSING VALUES")
print("=" * 60)

print("Count:", len(high_missing))
print(high_missing.round(2).to_string())


print("\n" + "=" * 60)
print("STEP 38 COMPLETE")
print("=" * 60)

============================================================
STEP 38: FEATURE TYPE & MISSING VALUE INSPECTION
============================================================

============================================================
NON-NUMERIC COLUMNS
============================================================
Count: 35
01. Title
02. City Name
03. State Name
04. Branch
05. Site Branch
06. Designation
07. Department
08. Cost Center
09. Site Cost Center
10. Site Name
11. Grade
12. Band
13. Reason for Requirement
14. Employee Category
15. Reporting Manager Code
16. Reporting Manager Name
17. Skip Level Manager Code
18. Skip Level Manager
19. Point of Hire
20. Point of Repatriation
21. ESIC Flag
22. PF Applicable
23. PF Type
24. Probation Status
25. Source of Hire
26. Bank Name
27. Cost Code
28. Client Vertical
29. Resident
30. Wage Type
31. TAX Regime
32. Uniform Deduction
33. Location
34. Region Name
35. Client Verticle

============================================================
MISSING VALUES BY COLUMN
============================================================
Point of Hire                      14651
Point of Repatriation              14649
OT2_Chargeable_OT                  13789
OT1_Avg_Daily_OT                   13789
OT1_Max_Daily_OT                   13789
OT1_OT_Days                        13789
OT1_Total_OT                       13789
OT1_NonChargeable_OT               13789
OT2_Total_OT                       13789
OT2_NonChargeable_OT               13789
OT1_Chargeable_OT                  13789
OT4_Max_Daily_OT                   12590
OT4_OT_Days                        12590
OT4_Chargeable_OT                  12590
OT4_NonChargeable_OT               12590
OT4_Total_OT                       12590
OT4_Avg_Daily_OT                   12590
OT3_Chargeable_OT                  12586
OT3_Total_OT                       12586
OT3_NonChargeable_OT               12586
Tenure_Years                       11050
Created Date_Days                  11050
Tenure_Days                        11050
Client Verticle                    11050
Date Of Joined_Days                11050
Annual_Gross_Salary                11050
Region Name                        11050
Monthly Gross Salary               11050
Location                           11050
Reason for Requirement              5693
Source of Hire                      5693
Conf. Date (Period Master)_Days     3067
Confirmation Date_Days              3067
Leave_Future_Approved               1690
Leave_Balance                       1690
Leave_Consumed                      1690
Leave_Accrued                       1690
Leave_Type_Count                    1690
Leave_Record_Count                  1690
Leave_Carry_Forward                 1690
Leave_Opening_Balance               1690
Leave_Balance_After_Future          1690
PF Applicable                        932
Bank Name                            123
ESIC Flag                             92
TAX Regime                            28
Wage Type                              9
Employer Notice Period                 7
Probation Status                       1

============================================================
MISSING PERCENTAGE BY COLUMN
============================================================
Point of Hire                      89.48
Point of Repatriation              89.47
OT2_NonChargeable_OT               84.21
OT1_OT_Days                        84.21
OT1_Total_OT                       84.21
OT1_NonChargeable_OT               84.21
OT2_Total_OT                       84.21
OT1_Avg_Daily_OT                   84.21
OT1_Max_Daily_OT                   84.21
OT2_Chargeable_OT                  84.21
OT1_Chargeable_OT                  84.21
OT4_NonChargeable_OT               76.89
OT4_Total_OT                       76.89
OT4_Chargeable_OT                  76.89
OT4_Max_Daily_OT                   76.89
OT4_OT_Days                        76.89
OT4_Avg_Daily_OT                   76.89
OT3_Chargeable_OT                  76.87
OT3_Total_OT                       76.87
OT3_NonChargeable_OT               76.87
Date Of Joined_Days                67.49
Region Name                        67.49
Tenure_Years                       67.49
Annual_Gross_Salary                67.49
Tenure_Days                        67.49
Location                           67.49
Monthly Gross Salary               67.49
Created Date_Days                  67.49
Client Verticle                    67.49
Source of Hire                     34.77
Reason for Requirement             34.77
Confirmation Date_Days             18.73
Conf. Date (Period Master)_Days    18.73
Leave_Type_Count                   10.32
Leave_Record_Count                 10.32
Leave_Carry_Forward                10.32
Leave_Balance                      10.32
Leave_Accrued                      10.32
Leave_Consumed                     10.32
Leave_Future_Approved              10.32
Leave_Opening_Balance              10.32
Leave_Balance_After_Future         10.32
PF Applicable                       5.69
Bank Name                           0.75
ESIC Flag                           0.56
TAX Regime                          0.17
Wage Type                           0.05
Employer Notice Period              0.04
Probation Status                    0.01

============================================================
COLUMNS WITH >= 50% MISSING VALUES
============================================================
Count: 29
Point of Hire            89.48
Point of Repatriation    89.47
OT2_NonChargeable_OT     84.21
OT1_OT_Days              84.21
OT1_Total_OT             84.21
OT1_NonChargeable_OT     84.21
OT2_Total_OT             84.21
OT1_Avg_Daily_OT         84.21
OT1_Max_Daily_OT         84.21
OT2_Chargeable_OT        84.21
OT1_Chargeable_OT        84.21
OT4_NonChargeable_OT     76.89
OT4_Total_OT             76.89
OT4_Chargeable_OT        76.89
OT4_Max_Daily_OT         76.89
OT4_OT_Days              76.89
OT4_Avg_Daily_OT         76.89
OT3_Chargeable_OT        76.87
OT3_Total_OT             76.87
OT3_NonChargeable_OT     76.87
Date Of Joined_Days      67.49
Region Name              67.49
Tenure_Years             67.49
Annual_Gross_Salary      67.49
Tenure_Days              67.49
Location                 67.49
Monthly Gross Salary     67.49
Created Date_Days        67.49
Client Verticle          67.49

============================================================
STEP 38 COMPLETE
============================================================

In [ ]:
# ============================================================
# STEP 39: FEATURE CARDINALITY & IDENTIFIER AUDIT
# ============================================================

print("=" * 60)
print("STEP 39: FEATURE CARDINALITY & IDENTIFIER AUDIT")
print("=" * 60)


# ------------------------------------------------------------
# 1. Unique values in categorical columns
# ------------------------------------------------------------

categorical_cols = X_train.select_dtypes(
    exclude=["number"]
).columns.tolist()

categorical_cardinality = pd.DataFrame({
    "Column": categorical_cols,
    "Unique_Count": [
        X_train[col].nunique(dropna=True)
        for col in categorical_cols
    ],
    "Missing_Count": [
        X_train[col].isna().sum()
        for col in categorical_cols
    ]
})

categorical_cardinality["Unique_%"] = (
    categorical_cardinality["Unique_Count"]
    / len(X_train) * 100
)

categorical_cardinality = categorical_cardinality.sort_values(
    "Unique_Count",
    ascending=False
)


print("\n" + "=" * 60)
print("CATEGORICAL COLUMN CARDINALITY")
print("=" * 60)

print(categorical_cardinality.to_string(index=False))


# ------------------------------------------------------------
# 2. Numeric columns with very high cardinality
# ------------------------------------------------------------

numeric_cols = X_train.select_dtypes(
    include=["number"]
).columns.tolist()

numeric_cardinality = pd.DataFrame({
    "Column": numeric_cols,
    "Unique_Count": [
        X_train[col].nunique(dropna=True)
        for col in numeric_cols
    ],
    "Missing_Count": [
        X_train[col].isna().sum()
        for col in numeric_cols
    ]
})

numeric_cardinality = numeric_cardinality.sort_values(
    "Unique_Count",
    ascending=False
)


print("\n" + "=" * 60)
print("NUMERIC COLUMN CARDINALITY")
print("=" * 60)

print(numeric_cardinality.to_string(index=False))


# ------------------------------------------------------------
# 3. Possible identifier-like columns
# ------------------------------------------------------------

possible_id_cols = []

for col in X_train.columns:

    unique_count = X_train[col].nunique(dropna=True)
    unique_ratio = unique_count / len(X_train)

    col_lower = col.lower()

    if (
        unique_ratio > 0.80
        or
        any(word in col_lower for word in [
            "employee code",
            "employee id",
            "employee no",
            "emp code",
            "emp id",
            "person id",
            "user id"
        ])
    ):
        possible_id_cols.append(col)


print("\n" + "=" * 60)
print("POSSIBLE IDENTIFIER-LIKE COLUMNS")
print("=" * 60)

if possible_id_cols:
    for col in possible_id_cols:
        print(
            f"{col:<40} "
            f"unique={X_train[col].nunique(dropna=True)}"
        )
else:
    print("No obvious identifier-like columns found.")


# ------------------------------------------------------------
# 4. Very high-cardinality categorical columns
# ------------------------------------------------------------

high_cardinality_cat = categorical_cardinality[
    categorical_cardinality["Unique_%"] > 5
]

print("\n" + "=" * 60)
print("HIGH-CARDINALITY CATEGORICAL COLUMNS")
print("(More than 5% unique values)")
print("=" * 60)

if len(high_cardinality_cat) > 0:
    print(
        high_cardinality_cat.to_string(index=False)
    )
else:
    print("None found.")


print("\n" + "=" * 60)
print("STEP 39 COMPLETE")
print("=" * 60)

============================================================
STEP 39: FEATURE CARDINALITY & IDENTIFIER AUDIT
============================================================

============================================================
CATEGORICAL COLUMN CARDINALITY
============================================================
                 Column  Unique_Count  Missing_Count  Unique_%
              Site Name           772              0  4.714792
            Cost Center           654              0  3.994137
       Site Cost Center           654              0  3.994137
              Cost Code           637              0  3.890314
            Designation           348              0  2.125321
 Reporting Manager Code           310              0  1.893245
 Reporting Manager Name           310              0  1.893245
Skip Level Manager Code           119              0  0.726762
     Skip Level Manager           119              0  0.726762
              Bank Name            85            123  0.519116
  Point of Repatriation            50          14649  0.305362
          Point of Hire            48          14651  0.293148
               Location            45          11050  0.274826
        Client Vertical            18              0  0.109930
                  Grade            14              0  0.085501
        Client Verticle            13          11050  0.079394
                PF Type            12              0  0.073287
             Department            10              0  0.061072
                 Branch             9              0  0.054965
            Site Branch             9              0  0.054965
              City Name             8              0  0.048858
             State Name             7              0  0.042751
            Region Name             5          11050  0.030536
                  Title             4              0  0.024429
 Reason for Requirement             4           5693  0.024429
               Resident             3              0  0.018322
              ESIC Flag             3             92  0.018322
                   Band             2              0  0.012214
      Employee Category             2              0  0.012214
          PF Applicable             2            932  0.012214
       Probation Status             2              1  0.012214
             TAX Regime             2             28  0.012214
              Wage Type             2              9  0.012214
      Uniform Deduction             2              0  0.012214
         Source of Hire             1           5693  0.006107

============================================================
NUMERIC COLUMN CARDINALITY
============================================================
                            Column  Unique_Count  Missing_Count
                   Birth Date_Days          8083              0
                         Age_Years          8083              0
           Calculated_Tenure_Years          2499              0
             Actual Join Date_Days          2499              0
              Group Join Date_Days          2499              0
         Effective Start Date_Days          1994              0
   Conf. Date (Period Master)_Days          1800           3067
            Confirmation Date_Days          1800           3067
               Annual_Gross_Salary          1451          11050
              Monthly Gross Salary          1451          11050
                     Leave_Balance          1374           1690
        Leave_Balance_After_Future          1374           1690
               Leave_Carry_Forward          1374           1690
                     Leave_Accrued          1158           1690
                       Profit Code           619              0
                      Tenure_Years           225          11050
               Date Of Joined_Days           225          11050
                       Tenure_Days           225          11050
                 Created Date_Days           202          11050
                      OT3_Total_OT           178          12586
                  OT4_Avg_Daily_OT           178          12590
                      OT4_Total_OT           178          12590
                  OT1_Avg_Daily_OT           166          13789
                      OT1_Total_OT           166          13789
                      OT2_Total_OT           166          13789
              OT4_NonChargeable_OT           161          12590
              OT3_NonChargeable_OT           161          12586
              OT2_NonChargeable_OT           119          13789
              OT1_NonChargeable_OT           119          13789
                 OT1_Chargeable_OT           115          13789
                 OT2_Chargeable_OT           115          13789
             Leave_Opening_Balance           104           1690
                 OT3_Chargeable_OT            88          12586
                 OT4_Chargeable_OT            88          12590
                  OT4_Max_Daily_OT            46          12590
                    Leave_Consumed            30           1690
                       OT1_OT_Days            27          13789
                  OT1_Max_Daily_OT            27          13789
                       OT4_OT_Days            27          12590
     Year Of Service (Current DOJ)            23              0
       Year of Service (Group DOJ)            23              0
             Leave_Future_Approved             5           1690
                  Leave_Type_Count             4           1690
                Leave_Record_Count             4           1690
            Employer Notice Period             3              7
              Leave_Data_Available             2              0
                OT4_Data_Available             2              0
             Salary_Data_Available             2              0
                OT2_Data_Available             2              0
                OT1_Data_Available             2              0
                      Is_Confirmed             2              0
                OT3_Data_Available             2              0
            Date Of Joined_Missing             2              0
Conf. Date (Period Master)_Missing             2              0
              Created Date_Missing             2              0
         Confirmation Date_Missing             2              0
      Effective Start Date_Missing             1              0
           Group Join Date_Missing             1              0
          Actual Join Date_Missing             1              0
                Birth Date_Missing             1              0

============================================================
POSSIBLE IDENTIFIER-LIKE COLUMNS
============================================================
No obvious identifier-like columns found.

============================================================
HIGH-CARDINALITY CATEGORICAL COLUMNS
(More than 5% unique values)
============================================================
None found.

============================================================
STEP 39 COMPLETE
============================================================

In [ ]:

# ============================================================
# STEP 40: REMOVE LEAKAGE & NON-INFORMATIVE FEATURES
# ============================================================

print("=" * 60)
print("STEP 40: FEATURE CLEANING BEFORE PREPROCESSING")
print("=" * 60)


# ------------------------------------------------------------
# 1. Features that can contain future information
# ------------------------------------------------------------

leakage_columns = [
    "Confirmation Date_Days",
    "Conf. Date (Period Master)_Days",
]


# ------------------------------------------------------------
# 2. Non-informative / constant feature
# ------------------------------------------------------------

constant_columns = [
    "Source of Hire",
]


# ------------------------------------------------------------
# 3. Combine columns to remove
# ------------------------------------------------------------

columns_to_drop = leakage_columns + constant_columns

# Keep only columns that actually exist
columns_to_drop = [
    col for col in columns_to_drop
    if col in X_train.columns
]

print("\nColumns to remove:")

for col in columns_to_drop:
    print("-", col)


# ------------------------------------------------------------
# 4. Remove from train and test
# ------------------------------------------------------------

X_train_clean = X_train.drop(
    columns=columns_to_drop
).copy()

X_test_clean = X_test.drop(
    columns=columns_to_drop
).copy()


# ------------------------------------------------------------
# 5. Verify
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("AFTER FEATURE REMOVAL")
print("=" * 60)

print("\nOriginal number of features:", X_train.shape[1])

print("Removed features:", len(columns_to_drop))

print("Remaining features:", X_train_clean.shape[1])

print("\nX_train_clean shape:",
      X_train_clean.shape)

print("X_test_clean shape:",
      X_test_clean.shape)


# ------------------------------------------------------------
# 6. Check for remaining datetime columns
# ------------------------------------------------------------

remaining_datetime = X_train_clean.select_dtypes(
    include=["datetime", "datetimetz"]
).columns.tolist()

print("\nRemaining datetime columns:")
print(remaining_datetime)


# ------------------------------------------------------------
# 7. Check target is not present
# ------------------------------------------------------------

print("\nTarget present in X_train_clean:",
      "Attrition" in X_train_clean.columns)


print("\n" + "=" * 60)
print("STEP 40 SUCCESS")
print("=" * 60)

============================================================
STEP 40: FEATURE CLEANING BEFORE PREPROCESSING
============================================================

Columns to remove:
- Confirmation Date_Days
- Conf. Date (Period Master)_Days
- Source of Hire

============================================================
AFTER FEATURE REMOVAL
============================================================

Original number of features: 95
Removed features: 3
Remaining features: 92

X_train_clean shape: (16374, 92)
X_test_clean shape: (4094, 92)

Remaining datetime columns:
[]

Target present in X_train_clean: False

============================================================
STEP 40 SUCCESS
============================================================

In [ ]:
# ============================================================
# STEP 41: PREPROCESSING PIPELINE
# ============================================================

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

print("=" * 60)
print("STEP 41: PREPROCESSING")
print("=" * 60)


# ------------------------------------------------------------
# 1. Identify numeric and categorical columns
# ------------------------------------------------------------

numeric_features = X_train_clean.select_dtypes(
    include=["number"]
).columns.tolist()

categorical_features = X_train_clean.select_dtypes(
    exclude=["number"]
).columns.tolist()


print("\nNumeric features:", len(numeric_features))
print("Categorical features:", len(categorical_features))


# ------------------------------------------------------------
# 2. FIX MIXED DATA TYPES IN CATEGORICAL COLUMNS
# ------------------------------------------------------------
# Some categorical columns contain both numbers and strings.
# Convert all non-missing categorical values to strings so that
# OneHotEncoder receives a consistent data type.

for col in categorical_features:

    X_train_clean[col] = X_train_clean[col].apply(
        lambda x: str(x) if pd.notna(x) else np.nan
    )

    X_test_clean[col] = X_test_clean[col].apply(
        lambda x: str(x) if pd.notna(x) else np.nan
    )


print("\nCategorical data types standardized to strings.")


# ------------------------------------------------------------
# 3. Numeric preprocessing
# ------------------------------------------------------------
# Missing numeric values -> median

numeric_pipeline = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(strategy="median")
        )
    ]
)


# ------------------------------------------------------------
# 4. Categorical preprocessing
# ------------------------------------------------------------
# Missing categorical values -> "Unknown"
# Then One-Hot Encoding.

categorical_pipeline = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(
                strategy="constant",
                fill_value="Unknown"
            )
        ),
        (
            "onehot",
            OneHotEncoder(
                handle_unknown="ignore",
                sparse_output=False
            )
        )
    ]
)


# ------------------------------------------------------------
# 5. Combine preprocessing
# ------------------------------------------------------------

preprocessor = ColumnTransformer(
    transformers=[
        (
            "num",
            numeric_pipeline,
            numeric_features
        ),
        (
            "cat",
            categorical_pipeline,
            categorical_features
        )
    ],
    remainder="drop"
)


# ------------------------------------------------------------
# 6. FIT ONLY ON TRAINING DATA
# ------------------------------------------------------------

X_train_processed = preprocessor.fit_transform(
    X_train_clean
)


# ------------------------------------------------------------
# 7. TRANSFORM TEST DATA
# ------------------------------------------------------------

X_test_processed = preprocessor.transform(
    X_test_clean
)


# ------------------------------------------------------------
# 8. Get feature names
# ------------------------------------------------------------

feature_names = preprocessor.get_feature_names_out()


# ------------------------------------------------------------
# 9. Convert processed data to DataFrame
# ------------------------------------------------------------

X_train_processed = pd.DataFrame(
    X_train_processed,
    columns=feature_names,
    index=X_train_clean.index
)

X_test_processed = pd.DataFrame(
    X_test_processed,
    columns=feature_names,
    index=X_test_clean.index
)


# ------------------------------------------------------------
# 10. VALIDATION
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("PREPROCESSING RESULTS")
print("=" * 60)

print("\nOriginal features:", X_train_clean.shape[1])

print(
    "Processed features:",
    X_train_processed.shape[1]
)

print(
    "\nX_train_processed shape:",
    X_train_processed.shape
)

print(
    "X_test_processed shape:",
    X_test_processed.shape
)

print(
    "\nMissing values in processed train:",
    X_train_processed.isna().sum().sum()
)

print(
    "Missing values in processed test:",
    X_test_processed.isna().sum().sum()
)


print("\n" + "=" * 60)
print("STEP 41 SUCCESS")
print("=" * 60)

============================================================
STEP 41: PREPROCESSING
============================================================

Numeric features: 58
Categorical features: 34

Categorical data types standardized to strings.

============================================================
PREPROCESSING RESULTS
============================================================

Original features: 92
Processed features: 4354

X_train_processed shape: (16374, 4354)
X_test_processed shape: (4094, 4354)

Missing values in processed train: 0
Missing values in processed test: 0

============================================================
STEP 41 SUCCESS
============================================================

In [ ]:
# ============================================================
# STEP 42: RANDOM FOREST MODEL TRAINING
# ============================================================

print("=" * 60)
print("STEP 42: RANDOM FOREST MODEL TRAINING")
print("=" * 60)

print("\nTraining data shape:")
print("X_train_processed:", X_train_processed.shape)
print("y_train:", y_train.shape)

print("\nTest data shape:")
print("X_test_processed:", X_test_processed.shape)
print("y_test:", y_test.shape)

print("\nTarget distribution in training data:")
print(y_train.value_counts())

print("\nStarting Random Forest training...")


# ------------------------------------------------------------
# 1. Create Random Forest model
# ------------------------------------------------------------

rf_model = RandomForestClassifier(
    n_estimators=300,
    class_weight="balanced",
    min_samples_split=5,
    min_samples_leaf=2,
    random_state=42,
    n_jobs=-1
)


# ------------------------------------------------------------
# 2. Train model
# ------------------------------------------------------------

rf_model.fit(
    X_train_processed,
    y_train
)


# ------------------------------------------------------------
# 3. Training completed
# ------------------------------------------------------------

print("\nRandom Forest training completed successfully.")


# ------------------------------------------------------------
# 4. Basic model information
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("MODEL INFORMATION")
print("=" * 60)

print("Number of trees:", rf_model.n_estimators)
print("Number of features:", rf_model.n_features_in_)
print("Classes:", rf_model.classes_)


print("\n" + "=" * 60)
print("STEP 42 SUCCESS")
print("=" * 60)

============================================================
STEP 42: RANDOM FOREST MODEL TRAINING
============================================================

Training data shape:
X_train_processed: (16374, 4354)
y_train: (16374,)

Test data shape:
X_test_processed: (4094, 4354)
y_test: (4094,)

Target distribution in training data:
Attrition
0    16196
1      178
Name: count, dtype: int64

Starting Random Forest training...

Random Forest training completed successfully.

============================================================
MODEL INFORMATION
============================================================
Number of trees: 300
Number of features: 4354
Classes: [0 1]

============================================================
STEP 42 SUCCESS
============================================================

In [ ]:
# ============================================================
# STEP 43: RANDOM FOREST PREDICTIONS
# ============================================================

print("=" * 60)
print("STEP 43: RANDOM FOREST PREDICTIONS")
print("=" * 60)


# ------------------------------------------------------------
# 1. Predict class
# ------------------------------------------------------------

y_pred = rf_model.predict(
    X_test_processed
)


# ------------------------------------------------------------
# 2. Predict probability of attrition
# ------------------------------------------------------------

y_pred_proba = rf_model.predict_proba(
    X_test_processed
)[:, 1]


# ------------------------------------------------------------
# 3. Basic validation
# ------------------------------------------------------------

print("\nPrediction completed successfully.")

print("\nPrediction shape:")
print("y_pred:", y_pred.shape)

print("\nProbability shape:")
print("y_pred_proba:", y_pred_proba.shape)


# ------------------------------------------------------------
# 4. Actual vs predicted distribution
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("ACTUAL TARGET DISTRIBUTION")
print("=" * 60)

print(
    y_test.value_counts().sort_index()
)


print("\n" + "=" * 60)
print("PREDICTED TARGET DISTRIBUTION")
print("=" * 60)

print(
    pd.Series(y_pred).value_counts().sort_index()
)


# ------------------------------------------------------------
# 5. Probability statistics
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("ATTRITION PROBABILITY SUMMARY")
print("=" * 60)

print(
    pd.Series(y_pred_proba).describe()
)


# ------------------------------------------------------------
# 6. Check probability range
# ------------------------------------------------------------

print("\nMinimum probability:", y_pred_proba.min())
print("Maximum probability:", y_pred_proba.max())


# ------------------------------------------------------------
# 7. Create prediction result DataFrame
# ------------------------------------------------------------

prediction_results = pd.DataFrame({
    "Actual_Attrition": y_test.values,
    "Predicted_Attrition": y_pred,
    "Attrition_Probability": y_pred_proba
})


print("\n" + "=" * 60)
print("SAMPLE PREDICTIONS")
print("=" * 60)

print(
    prediction_results.head(10)
)


print("\n" + "=" * 60)
print("STEP 43 SUCCESS")
print("=" * 60)

============================================================
STEP 43: RANDOM FOREST PREDICTIONS
============================================================

Prediction completed successfully.

Prediction shape:
y_pred: (4094,)

Probability shape:
y_pred_proba: (4094,)

============================================================
ACTUAL TARGET DISTRIBUTION
============================================================
Attrition
0    4049
1      45
Name: count, dtype: int64

============================================================
PREDICTED TARGET DISTRIBUTION
============================================================
0    4062
1      32
Name: count, dtype: int64

============================================================
ATTRITION PROBABILITY SUMMARY
============================================================
count    4094.000000
mean        0.060735
std         0.095174
min         0.000000
25%         0.009672
50%         0.023738
75%         0.069018
max         0.986774
dtype: float64

Minimum probability: 0.0
Maximum probability: 0.9867743614909473

============================================================
SAMPLE PREDICTIONS
============================================================
   Actual_Attrition  Predicted_Attrition  Attrition_Probability
0                 0                    0               0.002345
1                 0                    0               0.028397
2                 0                    0               0.016225
3                 0                    0               0.098298
4                 0                    0               0.089484
5                 0                    0               0.015619
6                 0                    0               0.006587
7                 0                    0               0.198881
8                 0                    0               0.166293
9                 0                    0               0.038737

============================================================
STEP 43 SUCCESS
============================================================

In [ ]:

# ============================================================
# STEP 44: RANDOM FOREST MODEL EVALUATION
# ============================================================

from sklearn.metrics import (
    confusion_matrix,
    classification_report,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    average_precision_score
)

print("=" * 60)
print("STEP 44: RANDOM FOREST MODEL EVALUATION")
print("=" * 60)


# ------------------------------------------------------------
# 1. Confusion Matrix
# ------------------------------------------------------------

cm = confusion_matrix(
    y_test,
    y_pred
)

tn, fp, fn, tp = cm.ravel()


print("\n" + "=" * 60)
print("CONFUSION MATRIX")
print("=" * 60)

print(cm)

print("\nTrue Negatives :", tn)
print("False Positives:", fp)
print("False Negatives:", fn)
print("True Positives :", tp)


# ------------------------------------------------------------
# 2. Classification Report
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("CLASSIFICATION REPORT")
print("=" * 60)

print(
    classification_report(
        y_test,
        y_pred,
        digits=4,
        zero_division=0
    )
)


# ------------------------------------------------------------
# 3. Individual metrics
# ------------------------------------------------------------

accuracy = accuracy_score(
    y_test,
    y_pred
)

precision = precision_score(
    y_test,
    y_pred,
    zero_division=0
)

recall = recall_score(
    y_test,
    y_pred,
    zero_division=0
)

f1 = f1_score(
    y_test,
    y_pred,
    zero_division=0
)

roc_auc = roc_auc_score(
    y_test,
    y_pred_proba
)

pr_auc = average_precision_score(
    y_test,
    y_pred_proba
)


print("\n" + "=" * 60)
print("MODEL METRICS")
print("=" * 60)

print(f"Accuracy : {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall   : {recall:.4f}")
print(f"F1 Score : {f1:.4f}")
print(f"ROC-AUC  : {roc_auc:.4f}")
print(f"PR-AUC   : {pr_auc:.4f}")


# ------------------------------------------------------------
# 4. Attrition detection summary
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("ATTRITION DETECTION SUMMARY")
print("=" * 60)

print("Actual attrition cases :", int((y_test == 1).sum()))
print("Detected attrition     :", int(tp))
print("Missed attrition       :", int(fn))

print(
    f"\nAttrition detection rate: {(tp / (tp + fn)) * 100:.2f}%"
)


# ------------------------------------------------------------
# 5. Store metrics
# ------------------------------------------------------------

evaluation_metrics = {
    "Accuracy": accuracy,
    "Precision": precision,
    "Recall": recall,
    "F1 Score": f1,
    "ROC-AUC": roc_auc,
    "PR-AUC": pr_auc
}


print("\n" + "=" * 60)
print("STEP 44 SUCCESS")
print("=" * 60)

============================================================
STEP 44: RANDOM FOREST MODEL EVALUATION
============================================================

============================================================
CONFUSION MATRIX
============================================================
[[4038   11]
 [  24   21]]

True Negatives : 4038
False Positives: 11
False Negatives: 24
True Positives : 21

============================================================
CLASSIFICATION REPORT
============================================================
              precision    recall  f1-score   support

           0     0.9941    0.9973    0.9957      4049
           1     0.6562    0.4667    0.5455        45

    accuracy                         0.9915      4094
   macro avg     0.8252    0.7320    0.7706      4094
weighted avg     0.9904    0.9915    0.9907      4094


============================================================
MODEL METRICS
============================================================
Accuracy : 0.9915
Precision: 0.6562
Recall   : 0.4667
F1 Score : 0.5455
ROC-AUC  : 0.9465
PR-AUC   : 0.5344

============================================================
ATTRITION DETECTION SUMMARY
============================================================
Actual attrition cases : 45
Detected attrition     : 21
Missed attrition       : 24

Attrition detection rate: 46.67%

============================================================
STEP 44 SUCCESS
============================================================

In [ ]:
# ============================================================
# STEP 45: ATTRITION PROBABILITY THRESHOLD ANALYSIS
# ============================================================

from sklearn.metrics import (
    precision_score,
    recall_score,
    f1_score
)

print("=" * 60)
print("STEP 45: ATTRITION PROBABILITY THRESHOLD ANALYSIS")
print("=" * 60)

thresholds = [
    0.50,
    0.40,
    0.30,
    0.25,
    0.20,
    0.15,
    0.10,
    0.05
]

threshold_results = []

for threshold in thresholds:

    y_pred_threshold = (
        y_pred_proba >= threshold
    ).astype(int)

    precision = precision_score(
        y_test,
        y_pred_threshold,
        zero_division=0
    )

    recall = recall_score(
        y_test,
        y_pred_threshold,
        zero_division=0
    )

    f1 = f1_score(
        y_test,
        y_pred_threshold,
        zero_division=0
    )

    predicted_attrition = int(
        y_pred_threshold.sum()
    )

    threshold_results.append({
        "Threshold": threshold,
        "Predicted_Attrition": predicted_attrition,
        "Precision": precision,
        "Recall": recall,
        "F1_Score": f1
    })


threshold_results_df = pd.DataFrame(
    threshold_results
)


print("\n" + "=" * 60)
print("THRESHOLD COMPARISON")
print("=" * 60)

print(
    threshold_results_df.to_string(
        index=False,
        formatters={
            "Precision": "{:.4f}".format,
            "Recall": "{:.4f}".format,
            "F1_Score": "{:.4f}".format
        }
    )
)


# ------------------------------------------------------------
# Best F1 threshold
# ------------------------------------------------------------

best_f1_row = threshold_results_df.loc[
    threshold_results_df["F1_Score"].idxmax()
]

print("\n" + "=" * 60)
print("BEST F1 THRESHOLD")
print("=" * 60)

print(
    f"Threshold           : "
    f"{best_f1_row['Threshold']:.2f}"
)

print(
    f"Predicted Attrition : "
    f"{int(best_f1_row['Predicted_Attrition'])}"
)

print(
    f"Precision           : "
    f"{best_f1_row['Precision']:.4f}"
)

print(
    f"Recall              : "
    f"{best_f1_row['Recall']:.4f}"
)

print(
    f"F1 Score            : "
    f"{best_f1_row['F1_Score']:.4f}"
)


print("\n" + "=" * 60)
print("STEP 45 SUCCESS")
print("=" * 60)

============================================================
STEP 45: ATTRITION PROBABILITY THRESHOLD ANALYSIS
============================================================

============================================================
THRESHOLD COMPARISON
============================================================
 Threshold  Predicted_Attrition Precision Recall F1_Score
      0.50                   32    0.6562 0.4667   0.5455
      0.40                   53    0.4151 0.4889   0.4490
      0.30                  126    0.2143 0.6000   0.3158
      0.25                  180    0.1667 0.6667   0.2667
      0.20                  305    0.1115 0.7556   0.1943
      0.15                  498    0.0803 0.8889   0.1473
      0.10                  741    0.0553 0.9111   0.1043
      0.05                 1254    0.0351 0.9778   0.0677

============================================================
BEST F1 THRESHOLD
============================================================
Threshold           : 0.50
Predicted Attrition : 32
Precision           : 0.6562
Recall              : 0.4667
F1 Score            : 0.5455

============================================================
STEP 45 SUCCESS
============================================================

In [ ]:
# ============================================================
# STEP 46: RANDOM FOREST FEATURE IMPORTANCE
# ============================================================

print("=" * 60)
print("STEP 46: RANDOM FOREST FEATURE IMPORTANCE")
print("=" * 60)

# ------------------------------------------------------------
# 1. Get feature names from preprocessing pipeline
# ------------------------------------------------------------

feature_names = preprocessor.get_feature_names_out()

print(f"\nNumber of processed feature names: {len(feature_names)}")
print(f"Number of model features: {len(rf_model.feature_importances_)}")


# ------------------------------------------------------------
# 2. Create feature importance dataframe
# ------------------------------------------------------------

feature_importance_df = pd.DataFrame({
    "Feature": feature_names,
    "Importance": rf_model.feature_importances_
})


# ------------------------------------------------------------
# 3. Sort by importance
# ------------------------------------------------------------

feature_importance_df = (
    feature_importance_df
    .sort_values(
        by="Importance",
        ascending=False
    )
    .reset_index(drop=True)
)


# ------------------------------------------------------------
# 4. Display top 30 features
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("TOP 30 MOST IMPORTANT FEATURES")
print("=" * 60)

print(
    feature_importance_df.head(30).to_string(
        index=False
    )
)


# ------------------------------------------------------------
# 5. Total importance check
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("FEATURE IMPORTANCE VALIDATION")
print("=" * 60)

print(
    f"Total importance: "
    f"{feature_importance_df['Importance'].sum():.6f}"
)


# ------------------------------------------------------------
# 6. Save complete feature importance
# ------------------------------------------------------------

feature_importance_df.to_csv(
    "random_forest_feature_importance.csv",
    index=False
)

print(
    "\nFeature importance saved as:"
    " random_forest_feature_importance.csv"
)


print("\n" + "=" * 60)
print("STEP 46 SUCCESS")
print("=" * 60)

============================================================
STEP 46: RANDOM FOREST FEATURE IMPORTANCE
============================================================

Number of processed feature names: 4354
Number of model features: 4354

============================================================
TOP 30 MOST IMPORTANT FEATURES
============================================================
                                      Feature  Importance
               num__Effective Start Date_Days    0.077947
                           num__Leave_Balance    0.040158
                     num__Leave_Carry_Forward    0.038203
              num__Leave_Balance_After_Future    0.037906
                           num__Leave_Accrued    0.034089
                 num__Calculated_Tenure_Years    0.020726
                   num__Actual Join Date_Days    0.020220
                    num__Group Join Date_Days    0.019631
                         num__Birth Date_Days    0.013060
                               num__Age_Years    0.013049
                     num__Date Of Joined_Days    0.012643
                       num__Created Date_Days    0.011537
                             num__Tenure_Days    0.011478
                            num__Tenure_Years    0.010859
             num__Year of Service (Group DOJ)    0.009924
                             num__Profit Code    0.008993
            cat__Client Vertical_North Region    0.008927
           num__Year Of Service (Current DOJ)    0.008924
         cat__Skip Level Manager Code_'283962    0.008138
                       cat__Site Branch_NOIDA    0.007728
                     num__Annual_Gross_Salary    0.007597
                 cat__Client Verticle_Unknown    0.007339
                         cat__City Name_Noida    0.007219
                        cat__Location_Unknown    0.006715
                   num__Salary_Data_Available    0.006650
                cat__State Name_Uttar Pradesh    0.006581
cat__Skip Level Manager_Bhagwan Singh Dhanwal    0.006531
                     cat__Region Name_Unknown    0.006255
                            cat__Branch_NOIDA    0.006204
                    num__Monthly Gross Salary    0.006071

============================================================
FEATURE IMPORTANCE VALIDATION
============================================================
Total importance: 1.000000

Feature importance saved as: random_forest_feature_importance.csv

============================================================
STEP 46 SUCCESS
============================================================

In [ ]:
# ============================================================
# STEP 47: AGGREGATED ORIGINAL FEATURE IMPORTANCE
# ============================================================

print("=" * 60)
print("STEP 47: AGGREGATED ORIGINAL FEATURE IMPORTANCE")
print("=" * 60)


# ------------------------------------------------------------
# 1. Copy feature importance
# ------------------------------------------------------------

agg_importance = feature_importance_df.copy()


# ------------------------------------------------------------
# 2. Extract original feature name
# ------------------------------------------------------------

def get_original_feature(feature_name):

    # Remove preprocessing prefix
    if "__" in feature_name:
        feature_name = feature_name.split("__", 1)[1]

    # For one-hot encoded categorical features,
    # remove the category after the first "_"
    #
    # Example:
    # Branch_NOIDA -> Branch
    # City Name_Noida -> City Name
    #
    # Numeric features remain unchanged.

    if feature_name.startswith("cat_"):
        feature_name = feature_name.replace("cat_", "", 1)

    return feature_name


# ------------------------------------------------------------
# IMPORTANT:
# Better method: use transformer output names
# and map based on the preprocessing transformers.
# ------------------------------------------------------------

numeric_features = list(
    preprocessor
    .named_transformers_["num"]
    .feature_names_in_
)

categorical_features = list(
    preprocessor
    .named_transformers_["cat"]
    .feature_names_in_
)


# ------------------------------------------------------------
# 3. Build mapping from processed feature -> original feature
# ------------------------------------------------------------

original_feature_mapping = {}

for feature in numeric_features:

    processed_name = f"num__{feature}"

    original_feature_mapping[processed_name] = feature


# Get encoded categorical feature names
ohe = (
    preprocessor
    .named_transformers_["cat"]
    .named_steps["onehot"]
)

encoded_names = ohe.get_feature_names_out(
    categorical_features
)

for encoded_name, original_feature in zip(
    encoded_names,
    [
        feature
        for feature in categorical_features
        for _ in range(
            len(
                ohe.categories_[
                    categorical_features.index(feature)
                ]
            )
        )
    ]
):

    processed_name = f"cat__{encoded_name}"

    original_feature_mapping[
        processed_name
    ] = original_feature


# ------------------------------------------------------------
# 4. Map every processed feature to original column
# ------------------------------------------------------------

agg_importance["Original_Feature"] = (
    agg_importance["Feature"]
    .map(original_feature_mapping)
)


# ------------------------------------------------------------
# 5. Check for unmapped features
# ------------------------------------------------------------

unmapped = agg_importance[
    agg_importance["Original_Feature"].isna()
]

print(
    f"\nUnmapped processed features: "
    f"{len(unmapped)}"
)


# ------------------------------------------------------------
# 6. Aggregate importance
# ------------------------------------------------------------

original_importance = (
    agg_importance
    .dropna(subset=["Original_Feature"])
    .groupby("Original_Feature")["Importance"]
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)


# ------------------------------------------------------------
# 7. Add percentage
# ------------------------------------------------------------

original_importance["Importance_Percentage"] = (
    original_importance["Importance"] * 100
)


# ------------------------------------------------------------
# 8. Display top 30 original features
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("TOP 30 ORIGINAL FEATURES")
print("=" * 60)

print(
    original_importance
    .head(30)
    .to_string(
        index=False,
        formatters={
            "Importance": "{:.6f}".format,
            "Importance_Percentage": "{:.2f}%".format
        }
    )
)


# ------------------------------------------------------------
# 9. Validation
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("AGGREGATED IMPORTANCE VALIDATION")
print("=" * 60)

print(
    f"Total aggregated importance: "
    f"{original_importance['Importance'].sum():.6f}"
)


# ------------------------------------------------------------
# 10. Save results
# ------------------------------------------------------------

original_importance.to_csv(
    "random_forest_original_feature_importance.csv",
    index=False
)

print(
    "\nSaved as:"
    " random_forest_original_feature_importance.csv"
)


print("\n" + "=" * 60)
print("STEP 47 SUCCESS")
print("=" * 60)

============================================================
STEP 47: AGGREGATED ORIGINAL FEATURE IMPORTANCE
============================================================

Unmapped processed features: 0

============================================================
TOP 30 ORIGINAL FEATURES
============================================================
          Original_Feature Importance Importance_Percentage
 Effective Start Date_Days   0.077947                 7.79%
             Leave_Balance   0.040158                 4.02%
       Leave_Carry_Forward   0.038203                 3.82%
Leave_Balance_After_Future   0.037906                 3.79%
               Cost Center   0.036110                 3.61%
                 Cost Code   0.035091                 3.51%
             Leave_Accrued   0.034089                 3.41%
          Site Cost Center   0.033873                 3.39%
                 Site Name   0.032859                 3.29%
    Reporting Manager Name   0.032179                 3.22%
   Skip Level Manager Code   0.030341                 3.03%
        Skip Level Manager   0.030186                 3.02%
    Reporting Manager Code   0.029750                 2.98%
           Client Vertical   0.021379                 2.14%
   Calculated_Tenure_Years   0.020726                 2.07%
     Actual Join Date_Days   0.020220                 2.02%
      Group Join Date_Days   0.019631                 1.96%
               Site Branch   0.019323                 1.93%
               Designation   0.017609                 1.76%
                    Branch   0.017523                 1.75%
                 City Name   0.017366                 1.74%
                State Name   0.015715                 1.57%
                 Bank Name   0.013678                 1.37%
               Region Name   0.013531                 1.35%
                  Location   0.013351                 1.34%
           Birth Date_Days   0.013060                 1.31%
                 Age_Years   0.013049                 1.30%
           Client Verticle   0.012875                 1.29%
       Date Of Joined_Days   0.012643                 1.26%
         Created Date_Days   0.011537                 1.15%

============================================================
AGGREGATED IMPORTANCE VALIDATION
============================================================
Total aggregated importance: 1.000000

Saved as: random_forest_original_feature_importance.csv

============================================================
STEP 47 SUCCESS
============================================================

In [ ]:
# ============================================================
# STEP 48: TOP FEATURE ATTRITION-WISE VALIDATION
# ============================================================

print("=" * 60)
print("STEP 48: TOP FEATURE ATTRITION-WISE VALIDATION")
print("=" * 60)


# ------------------------------------------------------------
# 1. Select top original features
# ------------------------------------------------------------

top_features = (
    original_importance
    .head(20)["Original_Feature"]
    .tolist()
)

print("\nTop 20 features selected for validation:")
for i, feature in enumerate(top_features, 1):
    print(f"{i:02d}. {feature}")


# ------------------------------------------------------------
# 2. Identify which features exist in model_data
# ------------------------------------------------------------

available_features = [
    feature
    for feature in top_features
    if feature in model_data.columns
]

print(
    f"\nAvailable in model_data: "
    f"{len(available_features)}"
)


# ------------------------------------------------------------
# 3. Numerical feature comparison
# ------------------------------------------------------------

numeric_top_features = [
    feature
    for feature in available_features
    if pd.api.types.is_numeric_dtype(
        model_data[feature]
    )
]


print("\n" + "=" * 60)
print("NUMERICAL FEATURES: ATTRITION-WISE COMPARISON")
print("=" * 60)


numeric_comparison = []

for feature in numeric_top_features:

    attrition_0 = model_data.loc[
        model_data["Attrition"] == 0,
        feature
    ].dropna()

    attrition_1 = model_data.loc[
        model_data["Attrition"] == 1,
        feature
    ].dropna()

    if len(attrition_0) == 0 or len(attrition_1) == 0:
        continue

    numeric_comparison.append({
        "Feature": feature,
        "Non_Attrition_Mean": attrition_0.mean(),
        "Attrition_Mean": attrition_1.mean(),
        "Non_Attrition_Median": attrition_0.median(),
        "Attrition_Median": attrition_1.median(),
        "Non_Attrition_Count": len(attrition_0),
        "Attrition_Count": len(attrition_1)
    })


numeric_comparison_df = pd.DataFrame(
    numeric_comparison
)


if len(numeric_comparison_df) > 0:

    print(
        numeric_comparison_df.to_string(
            index=False
        )
    )

else:

    print(
        "No numerical top features available "
        "for comparison."
    )


# ------------------------------------------------------------
# 4. Save numerical comparison
# ------------------------------------------------------------

numeric_comparison_df.to_csv(
    "top_features_attrition_numeric_comparison.csv",
    index=False
)


print("\n" + "=" * 60)
print("STEP 48 SUCCESS")
print("=" * 60)

============================================================
STEP 48: TOP FEATURE ATTRITION-WISE VALIDATION
============================================================

Top 20 features selected for validation:
01. Effective Start Date_Days
02. Leave_Balance
03. Leave_Carry_Forward
04. Leave_Balance_After_Future
05. Cost Center
06. Cost Code
07. Leave_Accrued
08. Site Cost Center
09. Site Name
10. Reporting Manager Name
11. Skip Level Manager Code
12. Skip Level Manager
13. Reporting Manager Code
14. Client Vertical
15. Calculated_Tenure_Years
16. Actual Join Date_Days
17. Group Join Date_Days
18. Site Branch
19. Designation
20. Branch

Available in model_data: 17

============================================================
NUMERICAL FEATURES: ATTRITION-WISE COMPARISON
============================================================
                   Feature  Non_Attrition_Mean  Attrition_Mean  Non_Attrition_Median  Attrition_Median  Non_Attrition_Count  Attrition_Count
             Leave_Balance            5.927340        3.641076              6.760000          3.040000                20245              223
       Leave_Carry_Forward            5.926426        3.641076              6.760000          3.040000                20245              223
Leave_Balance_After_Future            5.926426        3.641076              6.760000          3.040000                20245              223
             Leave_Accrued            5.693985        3.335561              6.850000          3.350000                20245              223
   Calculated_Tenure_Years            2.210999        1.481803              1.215606          0.681725                20245              223

============================================================
STEP 48 SUCCESS
============================================================

In [ ]:
# ============================================================
# STEP 49: CATEGORICAL FEATURE ATTRITION-RATE ANALYSIS
# ============================================================

print("=" * 60)
print("STEP 49: CATEGORICAL FEATURE ATTRITION-RATE ANALYSIS")
print("=" * 60)


# ------------------------------------------------------------
# 1. Top features from Step 47
# ------------------------------------------------------------

top_features = (
    original_importance
    .head(20)["Original_Feature"]
    .tolist()
)


# ------------------------------------------------------------
# 2. Identify categorical features
# ------------------------------------------------------------

categorical_features = [
    feature
    for feature in top_features
    if feature in model_data.columns
    and not pd.api.types.is_numeric_dtype(model_data[feature])
]


print("\nCategorical features selected:")
for i, feature in enumerate(categorical_features, 1):
    print(f"{i:02d}. {feature}")


# ------------------------------------------------------------
# 3. Minimum group size
# ------------------------------------------------------------

MIN_GROUP_SIZE = 20

print(
    f"\nMinimum employees required per category: "
    f"{MIN_GROUP_SIZE}"
)


# ------------------------------------------------------------
# 4. Calculate attrition rate by category
# ------------------------------------------------------------

all_category_results = []


for feature in categorical_features:

    temp = model_data[[feature, "Attrition"]].copy()

    # Handle missing values
    temp[feature] = temp[feature].fillna("Unknown")
    temp[feature] = temp[feature].astype(str)

    grouped = (
        temp
        .groupby(feature)["Attrition"]
        .agg(
            Employee_Count="count",
            Attrition_Count="sum",
            Attrition_Rate="mean"
        )
        .reset_index()
    )

    # Minimum group size
    grouped = grouped[
        grouped["Employee_Count"] >= MIN_GROUP_SIZE
    ].copy()

    if grouped.empty:
        continue

    grouped["Attrition_Rate"] = (
        grouped["Attrition_Rate"] * 100
    )

    grouped["Feature"] = feature

    grouped = grouped.rename(
        columns={feature: "Category"}
    )

    all_category_results.append(
        grouped[
            [
                "Feature",
                "Category",
                "Employee_Count",
                "Attrition_Count",
                "Attrition_Rate"
            ]
        ]
    )


# ------------------------------------------------------------
# 5. Combine results
# ------------------------------------------------------------

if all_category_results:

    categorical_attrition_analysis = pd.concat(
        all_category_results,
        ignore_index=True
    )

else:

    categorical_attrition_analysis = pd.DataFrame(
        columns=[
            "Feature",
            "Category",
            "Employee_Count",
            "Attrition_Count",
            "Attrition_Rate"
        ]
    )


# ------------------------------------------------------------
# 6. Sort by attrition rate
# ------------------------------------------------------------

categorical_attrition_analysis = (
    categorical_attrition_analysis
    .sort_values(
        by="Attrition_Rate",
        ascending=False
    )
    .reset_index(drop=True)
)


# ------------------------------------------------------------
# 7. Display top categories
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("TOP CATEGORIES BY ATTRITION RATE")
print("=" * 60)

if not categorical_attrition_analysis.empty:

    display(
        categorical_attrition_analysis.head(30)
    )

else:

    print("No categorical results available.")


# ------------------------------------------------------------
# 8. Overall attrition rate
# ------------------------------------------------------------

overall_attrition_rate = (
    model_data["Attrition"].mean() * 100
)

print("\n" + "=" * 60)
print("OVERALL ATTRITION RATE")
print("=" * 60)

print(
    f"Overall attrition rate: "
    f"{overall_attrition_rate:.2f}%"
)


# ------------------------------------------------------------
# 9. Save results
# ------------------------------------------------------------

categorical_attrition_analysis.to_csv(
    "categorical_feature_attrition_analysis.csv",
    index=False
)


print("\nSaved as:")
print("categorical_feature_attrition_analysis.csv")


print("\n" + "=" * 60)
print("STEP 49 SUCCESS")
print("=" * 60)

============================================================
STEP 49: CATEGORICAL FEATURE ATTRITION-RATE ANALYSIS
============================================================

Categorical features selected:
01. Cost Center
02. Cost Code
03. Site Cost Center
04. Site Name
05. Reporting Manager Name
06. Skip Level Manager Code
07. Skip Level Manager
08. Reporting Manager Code
09. Client Vertical
10. Site Branch
11. Designation
12. Branch

Minimum employees required per category: 20

============================================================
TOP CATEGORIES BY ATTRITION RATE
============================================================

,Feature,Category,Employee_Count,Attrition_Count,Attrition_Rate
0,Reporting Manager Code,'PS0000,32,10,31.250000
1,Reporting Manager Name,Psipl Admin,32,10,31.250000
2,Reporting Manager Name,Praveen Narayanan,27,4,14.814815
3,Reporting Manager Code,'580901,27,4,14.814815
4,Cost Code,PSI-RAD25MUM,28,4,14.285714
5,Cost Center,RADHAKISHAN DAMANI MUMBAI,28,4,14.285714
6,Site Cost Center,RADHAKISHAN DAMANI MUMBAI,28,4,14.285714
7,Site Name,RADHAKISHAN DAMANI MUMBAI,28,4,14.285714
8,Site Name,TELEPERFORMANCE GLOBAL HARYANA,117,16,13.675214
9,Site Cost Center,TELEPERFORMANCE GLOBAL BUSINESS PVT LTD HARYANA,117,16,13.675214
10,Cost Center,TELEPERFORMANCE GLOBAL BUSINESS PVT LTD HARYANA,117,16,13.675214
11,Cost Code,PSI-TEL25HAR,117,16,13.675214
12,Reporting Manager Name,Ramveer Bhagod,125,16,12.800000
13,Reporting Manager Code,'537434,125,16,12.800000
14,Site Cost Center,FLENDER DRIVE SYS WALAJABAD TAMIL NADU,78,9,11.538462
15,Site Name,FLENDER DRIVE CHENNAI,78,9,11.538462
16,Cost Code,PSI-FLE24TAM,78,9,11.538462
17,Cost Center,FLENDER DRIVE SYS WALAJABAD TAMIL NADU,78,9,11.538462
18,Cost Code,PSI-STU24HAR,27,3,11.111111
19,Site Cost Center,STUDYIQ EDUCATION PVT LTD HARYANA,27,3,11.111111
20,Site Name,STUDYIQ EDUCATION STUDYIQ UNITECH CYBER PARK G...,27,3,11.111111
21,Cost Center,STUDYIQ EDUCATION PVT LTD HARYANA,27,3,11.111111
22,Designation,Engineer,55,6,10.909091
23,Skip Level Manager Code,'66131,30,3,10.000000
24,Skip Level Manager,Rajendra Subhash Ghatode,30,3,10.000000
25,Site Name,IFMS BASE OPS KALPATARU SQUARE ANDHERI,22,2,9.090909
26,Designation,Property Manager,22,2,9.090909
27,Reporting Manager Name,Yogesh Dilip Patil,25,2,8.000000
28,Reporting Manager Code,'551474,25,2,8.000000
29,Cost Code,PSI-SHF25HAR,126,10,7.936508

============================================================
OVERALL ATTRITION RATE
============================================================
Overall attrition rate: 1.09%

Saved as:
categorical_feature_attrition_analysis.csv

============================================================
STEP 49 SUCCESS
============================================================

In [ ]:
# ============================================================
# STEP 50: FINAL MODEL VALIDATION & BUSINESS FACTOR SUMMARY
# ============================================================

print("=" * 60)
print("STEP 50: FINAL MODEL VALIDATION")
print("=" * 60)

# ------------------------------------------------------------
# 1. MODEL CHECK
# ------------------------------------------------------------

print("\nMODEL INFORMATION")
print("-" * 60)

print("Model type:", type(rf_model).__name__)
print("Number of trees:", rf_model.n_estimators)
print("Training rows:", X_train_processed.shape[0])
print("Test rows:", X_test_processed.shape[0])
print("Processed features:", X_train_processed.shape[1])


# ------------------------------------------------------------
# 2. PREDICTION CHECK
# ------------------------------------------------------------

print("\nPREDICTION CHECK")
print("-" * 60)

print("Actual attrition cases:", int(y_test.sum()))
print("Predicted attrition cases:", int(y_pred.sum()))
print("Prediction probabilities:", len(y_pred_proba))


# ------------------------------------------------------------
# 3. MODEL METRICS
# ------------------------------------------------------------

print("\nFINAL MODEL METRICS")
print("-" * 60)

print(f"Accuracy  : {accuracy:.4f}")
print(f"Precision : {precision:.4f}")
print(f"Recall    : {recall:.4f}")
print(f"F1 Score  : {f1:.4f}")
print(f"ROC-AUC   : {roc_auc:.4f}")
print(f"PR-AUC    : {pr_auc:.4f}")


# ------------------------------------------------------------
# 4. ATTRITION DETECTION
# ------------------------------------------------------------

actual_attrition = int((y_test == 1).sum())

detected_attrition = int(
    ((y_test == 1) & (y_pred == 1)).sum()
)

missed_attrition = int(
    ((y_test == 1) & (y_pred == 0)).sum()
)

detection_rate = (
    detected_attrition / actual_attrition * 100
    if actual_attrition > 0 else 0
)

print("\nATTRITION DETECTION")
print("-" * 60)

print("Actual attrition cases :", actual_attrition)
print("Detected attrition    :", detected_attrition)
print("Missed attrition      :", missed_attrition)
print(f"Detection rate        : {detection_rate:.2f}%")


# ------------------------------------------------------------
# 5. LOAD ORIGINAL FEATURE IMPORTANCE FROM STEP 47
# ------------------------------------------------------------

print("\nTOP PREDICTIVE FACTORS")
print("-" * 60)

original_feature_importance = pd.read_csv(
    "random_forest_original_feature_importance.csv"
)

top_business_features = (
    original_feature_importance
    .sort_values("Importance", ascending=False)
    .head(15)
    .copy()
)

top_business_features["Importance_%"] = (
    top_business_features["Importance"] * 100
).round(2)

print(
    top_business_features[
        ["Original_Feature", "Importance", "Importance_%"]
    ].to_string(index=False)
)


# ------------------------------------------------------------
# 6. BUSINESS SUMMARY
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("BUSINESS VALIDATION SUMMARY")
print("=" * 60)

print(
    "Random Forest successfully learned employee attrition patterns."
)

print(
    "The model generates attrition probabilities for employees."
)

print(
    "Feature importance identifies the strongest predictive factors."
)

print(
    "These probabilities will be used to classify future resignation risk."
)

print("\n" + "=" * 60)
print("STEP 50 SUCCESS")
print("=" * 60)

============================================================
STEP 50: FINAL MODEL VALIDATION
============================================================

MODEL INFORMATION
------------------------------------------------------------
Model type: RandomForestClassifier
Number of trees: 300
Training rows: 16374
Test rows: 4094
Processed features: 4354

PREDICTION CHECK
------------------------------------------------------------
Actual attrition cases: 45
Predicted attrition cases: 32
Prediction probabilities: 4094

FINAL MODEL METRICS
------------------------------------------------------------
Accuracy  : 0.9915
Precision : 0.0351
Recall    : 0.9778
F1 Score  : 0.0677
ROC-AUC   : 0.9465
PR-AUC    : 0.5344

ATTRITION DETECTION
------------------------------------------------------------
Actual attrition cases : 45
Detected attrition    : 21
Missed attrition      : 24
Detection rate        : 46.67%

TOP PREDICTIVE FACTORS
------------------------------------------------------------
          Original_Feature  Importance  Importance_%
 Effective Start Date_Days    0.077947          7.79
             Leave_Balance    0.040158          4.02
       Leave_Carry_Forward    0.038203          3.82
Leave_Balance_After_Future    0.037906          3.79
               Cost Center    0.036110          3.61
                 Cost Code    0.035091          3.51
             Leave_Accrued    0.034089          3.41
          Site Cost Center    0.033873          3.39
                 Site Name    0.032859          3.29
    Reporting Manager Name    0.032179          3.22
   Skip Level Manager Code    0.030341          3.03
        Skip Level Manager    0.030186          3.02
    Reporting Manager Code    0.029750          2.98
           Client Vertical    0.021379          2.14
   Calculated_Tenure_Years    0.020726          2.07

============================================================
BUSINESS VALIDATION SUMMARY
============================================================
Random Forest successfully learned employee attrition patterns.
The model generates attrition probabilities for employees.
Feature importance identifies the strongest predictive factors.
These probabilities will be used to classify future resignation risk.

============================================================
STEP 50 SUCCESS
============================================================

In [ ]:
# ============================================================
# STEP 51: FINAL PREDICTION DATA - PIPELINE COMPATIBILITY CHECK
# ============================================================

print("=" * 60)
print("STEP 51: PREDICTION PIPELINE COMPATIBILITY CHECK")
print("=" * 60)

print("\nMODEL DATA")
print("-" * 60)
print("Shape:", model_data.shape)

print("\nTraining feature count:", len(X_train_clean.columns))
print("Training feature count:", X_train_clean.shape[1])

print("\nMissing training features in model_data:")
missing_features = [
    col for col in X_train_clean.columns
    if col not in model_data.columns
]

print("Count:", len(missing_features))

for i, col in enumerate(missing_features, 1):
    print(f"{i:02d}. {col}")


print("\n" + "=" * 60)
print("RAW COLUMNS AVAILABLE IN MODEL_DATA")
print("=" * 60)

for i, col in enumerate(model_data.columns, 1):
    print(f"{i:02d}. {col}")


print("\n" + "=" * 60)
print("TRAINING FEATURES")
print("=" * 60)

for i, col in enumerate(X_train_clean.columns, 1):
    print(f"{i:02d}. {col}")


print("\n" + "=" * 60)
print("STEP 51 DIAGNOSTIC COMPLETE")
print("=" * 60)

============================================================
STEP 51: PREDICTION PIPELINE COMPATIBILITY CHECK
============================================================

MODEL DATA
------------------------------------------------------------
Shape: (20468, 87)

Training feature count: 92
Training feature count: 92

Missing training features in model_data:
Count: 16
01. Point of Hire
02. Point of Repatriation
03. Actual Join Date_Days
04. Actual Join Date_Missing
05. Group Join Date_Days
06. Group Join Date_Missing
07. Confirmation Date_Missing
08. Effective Start Date_Days
09. Effective Start Date_Missing
10. Conf. Date (Period Master)_Missing
11. Birth Date_Days
12. Birth Date_Missing
13. Date Of Joined_Days
14. Date Of Joined_Missing
15. Created Date_Days
16. Created Date_Missing

============================================================
RAW COLUMNS AVAILABLE IN MODEL_DATA
============================================================
01. Title
02. City Name
03. State Name
04. Branch
05. Site Branch
06. Designation
07. Department
08. Cost Center
09. Site Cost Center
10. Site Name
11. Grade
12. Band
13. Reason for Requirement
14. Employee Category
15. Reporting Manager Code
16. Reporting Manager Name
17. Skip Level Manager Code
18. Skip Level Manager
19. Actual Join Date
20. Group Join Date
21. Year Of Service (Current DOJ)
22. Year of Service (Group DOJ)
23. ESIC Flag
24. PF Applicable
25. PF Type
26. Probation Status
27. Confirmation Date
28. Source of Hire
29. Effective Start Date
30. Conf. Date (Period Master)
31. Employer Notice Period
32. Bank Name
33. Movement Type
34. Birth Date
35. Cost Code
36. Profit Code
37. Client Vertical
38. Resident
39. Wage Type
40. TAX Regime
41. Uniform Deduction
42. Location
43. Region Name
44. Client Verticle
45. Date Of Joined
46. Created Date
47. Monthly Gross Salary
48. Annual_Gross_Salary
49. Tenure_Days
50. Tenure_Years
51. OT1_Chargeable_OT
52. OT1_NonChargeable_OT
53. OT1_Total_OT
54. OT1_OT_Days
55. OT1_Avg_Daily_OT
56. OT1_Max_Daily_OT
57. OT2_Chargeable_OT
58. OT2_NonChargeable_OT
59. OT2_Total_OT
60. OT3_Chargeable_OT
61. OT3_NonChargeable_OT
62. OT3_Total_OT
63. OT4_Chargeable_OT
64. OT4_NonChargeable_OT
65. OT4_Total_OT
66. OT4_OT_Days
67. OT4_Avg_Daily_OT
68. OT4_Max_Daily_OT
69. Leave_Opening_Balance
70. Leave_Accrued
71. Leave_Consumed
72. Leave_Balance
73. Leave_Future_Approved
74. Leave_Balance_After_Future
75. Leave_Carry_Forward
76. Leave_Record_Count
77. Leave_Type_Count
78. Attrition
79. Age_Years
80. Calculated_Tenure_Years
81. Is_Confirmed
82. OT1_Data_Available
83. OT2_Data_Available
84. OT3_Data_Available
85. OT4_Data_Available
86. Salary_Data_Available
87. Leave_Data_Available

============================================================
TRAINING FEATURES
============================================================
01. Title
02. City Name
03. State Name
04. Branch
05. Site Branch
06. Designation
07. Department
08. Cost Center
09. Site Cost Center
10. Site Name
11. Grade
12. Band
13. Reason for Requirement
14. Employee Category
15. Reporting Manager Code
16. Reporting Manager Name
17. Skip Level Manager Code
18. Skip Level Manager
19. Year Of Service (Current DOJ)
20. Year of Service (Group DOJ)
21. Point of Hire
22. Point of Repatriation
23. ESIC Flag
24. PF Applicable
25. PF Type
26. Probation Status
27. Employer Notice Period
28. Bank Name
29. Cost Code
30. Profit Code
31. Client Vertical
32. Resident
33. Wage Type
34. TAX Regime
35. Uniform Deduction
36. Location
37. Region Name
38. Client Verticle
39. Monthly Gross Salary
40. Annual_Gross_Salary
41. Tenure_Days
42. Tenure_Years
43. OT1_Chargeable_OT
44. OT1_NonChargeable_OT
45. OT1_Total_OT
46. OT1_OT_Days
47. OT1_Avg_Daily_OT
48. OT1_Max_Daily_OT
49. OT2_Chargeable_OT
50. OT2_NonChargeable_OT
51. OT2_Total_OT
52. OT3_Chargeable_OT
53. OT3_NonChargeable_OT
54. OT3_Total_OT
55. OT4_Chargeable_OT
56. OT4_NonChargeable_OT
57. OT4_Total_OT
58. OT4_OT_Days
59. OT4_Avg_Daily_OT
60. OT4_Max_Daily_OT
61. Leave_Opening_Balance
62. Leave_Accrued
63. Leave_Consumed
64. Leave_Balance
65. Leave_Future_Approved
66. Leave_Balance_After_Future
67. Leave_Carry_Forward
68. Leave_Record_Count
69. Leave_Type_Count
70. Age_Years
71. Calculated_Tenure_Years
72. Is_Confirmed
73. OT1_Data_Available
74. OT2_Data_Available
75. OT3_Data_Available
76. OT4_Data_Available
77. Salary_Data_Available
78. Leave_Data_Available
79. Actual Join Date_Days
80. Actual Join Date_Missing
81. Group Join Date_Days
82. Group Join Date_Missing
83. Confirmation Date_Missing
84. Effective Start Date_Days
85. Effective Start Date_Missing
86. Conf. Date (Period Master)_Missing
87. Birth Date_Days
88. Birth Date_Missing
89. Date Of Joined_Days
90. Date Of Joined_Missing
91. Created Date_Days
92. Created Date_Missing

============================================================
STEP 51 DIAGNOSTIC COMPLETE
============================================================

In [ ]:

# ============================================================
# STEP 52: IDENTIFY DATE FEATURE ENGINEERING USED IN TRAINING
# ============================================================

print("=" * 60)
print("STEP 52: DATE FEATURE ENGINEERING VALIDATION")
print("=" * 60)

date_feature_pairs = {
    "Actual Join Date": [
        "Actual Join Date_Days",
        "Actual Join Date_Missing"
    ],
    "Group Join Date": [
        "Group Join Date_Days",
        "Group Join Date_Missing"
    ],
    "Confirmation Date": [
        "Confirmation Date_Missing"
    ],
    "Effective Start Date": [
        "Effective Start Date_Days",
        "Effective Start Date_Missing"
    ],
    "Conf. Date (Period Master)": [
        "Conf. Date (Period Master)_Missing"
    ],
    "Birth Date": [
        "Birth Date_Days",
        "Birth Date_Missing"
    ],
    "Date Of Joined": [
        "Date Of Joined_Days",
        "Date Of Joined_Missing"
    ],
    "Created Date": [
        "Created Date_Days",
        "Created Date_Missing"
    ]
}

print("\nTraining engineered date features:")
print("-" * 60)

for raw_col, engineered_cols in date_feature_pairs.items():

    print(f"\nRAW COLUMN: {raw_col}")

    if raw_col in model_data.columns:
        print("Raw column exists in model_data")

        raw_values = pd.to_datetime(
            model_data[raw_col],
            errors="coerce"
        )

        print("Non-null dates:", raw_values.notna().sum())
        print("Min date:", raw_values.min())
        print("Max date:", raw_values.max())

    else:
        print("Raw column NOT available in model_data")

    for feature in engineered_cols:

        if feature in X_train_clean.columns:

            values = X_train_clean[feature]

            print(f"\n  {feature}")
            print("  dtype:", values.dtype)
            print("  min:", values.min())
            print("  max:", values.max())
            print("  unique sample:",
                  values.dropna().unique()[:10])

        else:
            print(f"  {feature} NOT FOUND in X_train_clean")


print("\n" + "=" * 60)
print("POINT OF HIRE / REPATRIATION")
print("=" * 60)

for col in ["Point of Hire", "Point of Repatriation"]:

    print(f"\n{col}")

    if col in X_train_clean.columns:
        print("Present in training data")
        print("dtype:", X_train_clean[col].dtype)
        print("Unique values:")
        print(X_train_clean[col].value_counts(dropna=False).head(20))

    else:
        print("NOT FOUND")


print("\n" + "=" * 60)
print("STEP 52 COMPLETE")
print("=" * 60)

============================================================
STEP 52: DATE FEATURE ENGINEERING VALIDATION
============================================================

Training engineered date features:
------------------------------------------------------------

RAW COLUMN: Actual Join Date
Raw column exists in model_data
Non-null dates: 20468
Min date: 2004-06-01 00:00:00
Max date: 2026-08-31 00:00:00

  Actual Join Date_Days
  dtype: int64
  min: 12570
  max: 20696
  unique sample: [20629 20430 20485 18233 20605 20640 20497 20563 19266 20544]

  Actual Join Date_Missing
  dtype: int64
  min: 0
  max: 0
  unique sample: [0]

RAW COLUMN: Group Join Date
Raw column exists in model_data
Non-null dates: 20468
Min date: 2004-06-01 00:00:00
Max date: 2026-08-31 00:00:00

  Group Join Date_Days
  dtype: int64
  min: 12570
  max: 20696
  unique sample: [20629 20430 20485 18233 20605 20640 20497 20563 19266 20544]

  Group Join Date_Missing
  dtype: int64
  min: 0
  max: 0
  unique sample: [0]

RAW COLUMN: Confirmation Date
Raw column exists in model_data
Non-null dates: 16592
Min date: 2004-06-01 00:00:00
Max date: 2027-01-23 00:00:00

  Confirmation Date_Missing
  dtype: int64
  min: 0
  max: 1
  unique sample: [0 1]

RAW COLUMN: Effective Start Date
Raw column exists in model_data
Non-null dates: 20468
Min date: 0025-12-01 00:00:00
Max date: 2026-08-31 00:00:00

  Effective Start Date_Days
  dtype: int64
  min: 16366
  max: 20696
  unique sample: [20629 20430 20485 18358 20605 20640 20497 20563 19604 20544]

  Effective Start Date_Missing
  dtype: int64
  min: 0
  max: 0
  unique sample: [0]

RAW COLUMN: Conf. Date (Period Master)
Raw column exists in model_data
Non-null dates: 16592
Min date: 2004-06-01 00:00:00
Max date: 2027-01-23 00:00:00

  Conf. Date (Period Master)_Missing
  dtype: int64
  min: 0
  max: 1
  unique sample: [0 1]

RAW COLUMN: Birth Date
Raw column exists in model_data
Non-null dates: 20468
Min date: 1960-01-01 00:00:00
Max date: 2009-03-22 00:00:00

  Birth Date_Days
  dtype: int64
  min: -3653
  max: 14325
  unique sample: [ 7202  -214  6940  6062  2712  9510  8766  2215 11018 11546]

  Birth Date_Missing
  dtype: int64
  min: 0
  max: 0
  unique sample: [0]

RAW COLUMN: Date Of Joined
Raw column exists in model_data
Non-null dates: 6645
Min date: 2025-12-22 00:00:00
Max date: 2026-08-31 00:00:00

  Date Of Joined_Days
  dtype: float64
  min: 20449.0
  max: 20696.0
  unique sample: [20629. 20485. 20605. 20640. 20497. 20563. 20635. 20502. 20593. 20613.]

  Date Of Joined_Missing
  dtype: int64
  min: 0
  max: 1
  unique sample: [0 1]

RAW COLUMN: Created Date
Raw column exists in model_data
Non-null dates: 6645
Min date: 2026-01-14 00:00:00
Max date: 2026-08-07 00:00:00

  Created Date_Days
  dtype: float64
  min: 20467.0
  max: 20672.0
  unique sample: [20633. 20489. 20598. 20640. 20507. 20568. 20635. 20508. 20592. 20603.]

  Created Date_Missing
  dtype: int64
  min: 0
  max: 1
  unique sample: [0 1]

============================================================
POINT OF HIRE / REPATRIATION
============================================================

Point of Hire
Present in training data
dtype: str
Unique values:
Point of Hire
NaN                   14651
Mumbai                  481
Noida                   209
Puri                    193
Bhubaneswar             143
Pune                    123
Ahmedabad                85
Haryana                  85
Jaipur                   80
Chennai                  64
Cuttack                  57
Hyderabad                26
Delhi                    21
Bangalore                19
Thiruvananthapuram       16
Nagpur                   14
Surat                    13
Aurangabad               11
Uttar Pradesh            11
Indore                    9
Name: count, dtype: int64

Point of Repatriation
Present in training data
dtype: str
Unique values:
Point of Repatriation
NaN                   14649
Mumbai                  481
Noida                   209
Puri                    193
Bhubaneswar             143
Pune                    124
Ahmedabad                85
Haryana                  81
Jaipur                   80
Chennai                  64
Cuttack                  57
Hyderabad                26
Delhi                    20
Bangalore                19
Thiruvananthapuram       16
Nagpur                   14
Surat                    13
Aurangabad               11
Uttar Pradesh            11
Indore                    9
Name: count, dtype: int64

============================================================
STEP 52 COMPLETE
============================================================

In [ ]:

# ============================================================
# STEP 53: BUILD MISSING TRAINING FEATURES FOR PREDICTION
# ============================================================

print("=" * 60)
print("STEP 53: BUILDING MISSING TRAINING FEATURES")
print("=" * 60)

prediction_data = model_data.copy()

# ------------------------------------------------------------
# 1. ADD MISSING CATEGORICAL FEATURES
# ------------------------------------------------------------

missing_categorical = [
    "Point of Hire",
    "Point of Repatriation"
]

for col in missing_categorical:
    if col not in prediction_data.columns:
        prediction_data[col] = pd.NA
        print(f"Added missing categorical feature: {col}")


# ------------------------------------------------------------
# 2. DATE FEATURE ENGINEERING
# ------------------------------------------------------------

DATE_FEATURES = {
    "Actual Join Date": [
        "Actual Join Date_Days",
        "Actual Join Date_Missing"
    ],
    "Group Join Date": [
        "Group Join Date_Days",
        "Group Join Date_Missing"
    ],
    "Confirmation Date": [
        "Confirmation Date_Missing"
    ],
    "Effective Start Date": [
        "Effective Start Date_Days",
        "Effective Start Date_Missing"
    ],
    "Conf. Date (Period Master)": [
        "Conf. Date (Period Master)_Missing"
    ],
    "Birth Date": [
        "Birth Date_Days",
        "Birth Date_Missing"
    ],
    "Date Of Joined": [
        "Date Of Joined_Days",
        "Date Of Joined_Missing"
    ],
    "Created Date": [
        "Created Date_Days",
        "Created Date_Missing"
    ]
}


# ------------------------------------------------------------
# 3. FUNCTION TO CREATE DATE FEATURES
# ------------------------------------------------------------

def create_prediction_date_features(df, raw_column):

    # Convert to datetime
    dates = pd.to_datetime(
        df[raw_column],
        errors="coerce"
    )

    # --------------------------------------------------------
    # Treat clearly invalid employee dates as missing.
    # Effective Start Date contains year 0025 in the data.
    # --------------------------------------------------------
    invalid_dates = dates.notna() & (
        (dates.dt.year < 1900) |
        (dates.dt.year > 2100)
    )

    dates.loc[invalid_dates] = pd.NaT

    # Missing flag
    missing_flag = dates.isna().astype(int)

    # Days since Unix epoch
    days = (
        dates - pd.Timestamp("1970-01-01")
    ).dt.days

    return days, missing_flag


# ------------------------------------------------------------
# 4. CREATE ENGINEERED DATE FEATURES
# ------------------------------------------------------------

for raw_column, engineered_columns in DATE_FEATURES.items():

    print(f"\nProcessing: {raw_column}")

    days, missing_flag = create_prediction_date_features(
        prediction_data,
        raw_column
    )

    # Features ending in _Days
    for feature in engineered_columns:

        if feature.endswith("_Days"):
            prediction_data[feature] = days

        elif feature.endswith("_Missing"):
            prediction_data[feature] = missing_flag


# ------------------------------------------------------------
# 5. CHECK REQUIRED TRAINING FEATURES
# ------------------------------------------------------------

missing_after_engineering = [
    col
    for col in training_columns
    if col not in prediction_data.columns
]

extra_prediction_columns = [
    col
    for col in prediction_data.columns
    if col not in training_columns
]

print("\n" + "=" * 60)
print("FEATURE ALIGNMENT CHECK")
print("=" * 60)

print("Training feature count:", len(training_columns))
print("Prediction feature count:", len(prediction_data.columns))

print("\nMissing training features:")
print(len(missing_after_engineering))

if missing_after_engineering:
    for i, col in enumerate(missing_after_engineering, 1):
        print(f"{i:02d}. {col}")

print("\nExtra prediction columns:")
print(len(extra_prediction_columns))

if extra_prediction_columns:
    print(extra_prediction_columns)


# ------------------------------------------------------------
# 6. STOP IF ANY TRAINING FEATURES ARE STILL MISSING
# ------------------------------------------------------------

if missing_after_engineering:
    raise ValueError(
        "Prediction data is still missing training features. "
        "Do not continue."
    )


# ------------------------------------------------------------
# 7. ALIGN EXACTLY TO TRAINING ORDER
# ------------------------------------------------------------

prediction_data = prediction_data[
    training_columns
].copy()


# ------------------------------------------------------------
# 8. FINAL VALIDATION
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("FINAL PREDICTION FEATURE DATA")
print("=" * 60)

print("Shape:", prediction_data.shape)

print(
    "Expected shape:",
    (len(model_data), len(training_columns))
)

print("\nFirst 10 columns:")
print(prediction_data.columns[:10].tolist())

print("\nLast 10 columns:")
print(prediction_data.columns[-10:].tolist())

print("\nMissing values:")
print(prediction_data.isna().sum().sum())

print("\n" + "=" * 60)
print("STEP 53 SUCCESS")
print("=" * 60)

============================================================
STEP 53: BUILDING MISSING TRAINING FEATURES
============================================================
Added missing categorical feature: Point of Hire
Added missing categorical feature: Point of Repatriation

Processing: Actual Join Date

Processing: Group Join Date

Processing: Confirmation Date

Processing: Effective Start Date

Processing: Conf. Date (Period Master)

Processing: Birth Date

Processing: Date Of Joined

Processing: Created Date

============================================================
FEATURE ALIGNMENT CHECK
============================================================
Training feature count: 92
Prediction feature count: 103

Missing training features:
0

Extra prediction columns:
11
['Actual Join Date', 'Group Join Date', 'Confirmation Date', 'Source of Hire', 'Effective Start Date', 'Conf. Date (Period Master)', 'Movement Type', 'Birth Date', 'Date Of Joined', 'Created Date', 'Attrition']

============================================================
FINAL PREDICTION FEATURE DATA
============================================================
Shape: (20468, 92)
Expected shape: (20468, 92)

First 10 columns:
['Title', 'City Name', 'State Name', 'Branch', 'Site Branch', 'Designation', 'Department', 'Cost Center', 'Site Cost Center', 'Site Name']

Last 10 columns:
['Confirmation Date_Missing', 'Effective Start Date_Days', 'Effective Start Date_Missing', 'Conf. Date (Period Master)_Missing', 'Birth Date_Days', 'Birth Date_Missing', 'Date Of Joined_Days', 'Date Of Joined_Missing', 'Created Date_Days', 'Created Date_Missing']

Missing values:
173981

============================================================
STEP 53 SUCCESS
============================================================

In [ ]:

# ============================================================
# STEP 54: FIND FITTED PREPROCESSOR
# ============================================================

print("=" * 60)
print("STEP 54: FINDING FITTED PREPROCESSOR")
print("=" * 60)

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

preprocessor_candidates = []

# IMPORTANT:
# Convert globals() to a list first so the dictionary
# cannot change while we iterate through it.

for name, obj in list(globals().items()):

    try:

        if isinstance(obj, ColumnTransformer):
            preprocessor_candidates.append(
                (name, type(obj).__name__)
            )

        elif isinstance(obj, Pipeline):
            preprocessor_candidates.append(
                (name, type(obj).__name__)
            )

    except Exception:
        pass


print("\nPreprocessing candidates found:")
print("-" * 60)

if not preprocessor_candidates:

    print("NO PREPROCESSOR FOUND")

else:

    for name, obj_type in preprocessor_candidates:

        print(f"Variable: {name}")
        print(f"Type:     {obj_type}")
        print("-" * 40)


print("\n" + "=" * 60)
print("STEP 54 COMPLETE")
print("=" * 60)

============================================================
STEP 54: FINDING FITTED PREPROCESSOR
============================================================

Preprocessing candidates found:
------------------------------------------------------------
Variable: numeric_pipeline
Type:     Pipeline
----------------------------------------
Variable: categorical_pipeline
Type:     Pipeline
----------------------------------------
Variable: preprocessor
Type:     ColumnTransformer
----------------------------------------

============================================================
STEP 54 COMPLETE
============================================================

In [ ]:

# ============================================================
# STEP 55: TRANSFORM CURRENT EMPLOYEE DATA
# ============================================================

print("=" * 60)
print("STEP 55: TRANSFORMING PREDICTION DATA")
print("=" * 60)

# ------------------------------------------------------------
# 1. Make a fresh copy
# ------------------------------------------------------------

prediction_data_for_model = prediction_data.copy()

print("\nInput prediction data:")
print("Shape:", prediction_data_for_model.shape)


# ------------------------------------------------------------
# 2. Replace pandas pd.NA with numpy NaN
# ------------------------------------------------------------
# The fitted sklearn preprocessor can handle np.nan,
# but pd.NA can cause:
# "boolean value of NA is ambiguous"

prediction_data_for_model = prediction_data_for_model.replace(
    {pd.NA: np.nan}
)


# ------------------------------------------------------------
# 3. Make sure categorical columns use object/string-compatible
#    missing values rather than pd.NA
# ------------------------------------------------------------

if "categorical_features" in globals():

    for col in categorical_features:

        if col in prediction_data_for_model.columns:

            prediction_data_for_model[col] = (
                prediction_data_for_model[col]
                .astype(object)
                .where(
                    prediction_data_for_model[col].notna(),
                    np.nan
                )
            )

    print(
        "\nCategorical columns standardized:",
        len(categorical_features)
    )

else:

    print(
        "\nWarning: categorical_features variable not found."
    )


# ------------------------------------------------------------
# 4. Verify exact training feature order
# ------------------------------------------------------------

if list(prediction_data_for_model.columns) != list(training_columns):

    raise ValueError(
        "Prediction columns do not match training feature order."
    )

print("Feature order: VERIFIED")


# ------------------------------------------------------------
# 5. Check for pandas NA specifically
# ------------------------------------------------------------

pd_na_count = 0

for col in prediction_data_for_model.columns:

    try:
        pd_na_count += prediction_data_for_model[col].map(
            lambda x: x is pd.NA
        ).sum()

    except Exception:
        pass


print("Remaining pd.NA values:", pd_na_count)


if pd_na_count != 0:

    raise ValueError(
        "pd.NA values still exist in prediction data."
    )


# ------------------------------------------------------------
# 6. Apply the SAME fitted preprocessing pipeline
# ------------------------------------------------------------

print("\nApplying fitted preprocessor...")

X_prediction_processed = preprocessor.transform(
    prediction_data_for_model
)


# ------------------------------------------------------------
# 7. Check transformed shape
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("TRANSFORMATION RESULTS")
print("=" * 60)

print(
    "Processed prediction shape:",
    X_prediction_processed.shape
)

print(
    "Expected:",
    (len(prediction_data_for_model), 4354)
)


# ------------------------------------------------------------
# 8. Validate processed feature count
# ------------------------------------------------------------

if X_prediction_processed.shape[1] != 4354:

    raise ValueError(
        f"Expected 4354 processed features, "
        f"but got {X_prediction_processed.shape[1]}."
    )


# ------------------------------------------------------------
# 9. Check processed missing values
# ------------------------------------------------------------

if hasattr(X_prediction_processed, "toarray"):

    processed_array = X_prediction_processed.toarray()

else:

    processed_array = np.asarray(
        X_prediction_processed
    )


processed_missing = np.isnan(
    processed_array
).sum()


print(
    "Missing values after preprocessing:",
    processed_missing
)


# ------------------------------------------------------------
# 10. Final validation
# ------------------------------------------------------------

if processed_missing != 0:

    raise ValueError(
        "Processed prediction data still contains missing values."
    )


print("\n" + "=" * 60)
print("STEP 55 SUCCESS")
print("=" * 60)

============================================================
STEP 55: TRANSFORMING PREDICTION DATA
============================================================

Input prediction data:
Shape: (20468, 92)

Categorical columns standardized: 12
Feature order: VERIFIED
Remaining pd.NA values: 0

Applying fitted preprocessor...

============================================================
TRANSFORMATION RESULTS
============================================================
Processed prediction shape: (20468, 4354)
Expected: (20468, 4354)
Missing values after preprocessing: 0

============================================================
STEP 55 SUCCESS
============================================================

In [ ]:
# Find the Step 55 transformed prediction variable

print("Variables with shape (20468, 4354):")
print("=" * 60)

for name, obj in list(globals().items()):
    try:
        if hasattr(obj, "shape") and obj.shape == (20468, 4354):
            print(name, "->", type(obj).__name__, obj.shape)
    except Exception:
        pass

Variables with shape (20468, 4354):
============================================================
X_prediction_processed -> ndarray (20468, 4354)
processed_array -> ndarray (20468, 4354)

In [ ]:

# ============================================================
# STEP 56: FUTURE RESIGNATION PREDICTION
# ============================================================

import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

print("\n" + "=" * 60)
print("STEP 56: FUTURE RESIGNATION PREDICTION")
print("=" * 60)

# ------------------------------------------------------------
# 1. PREDICTION INPUT
# ------------------------------------------------------------

print("\nPREDICTION INPUT")
print("-" * 60)

print("Processed prediction shape:", X_prediction_processed.shape)
print("Expected shape: (20468, 4354)")

if X_prediction_processed.shape != (20468, 4354):
    raise ValueError(
        f"Unexpected prediction shape: "
        f"{X_prediction_processed.shape}"
    )

print("Prediction data shape: VERIFIED")

# ------------------------------------------------------------
# 2. FIND TRAINED RANDOM FOREST
# ------------------------------------------------------------

print("\nMODEL CHECK")
print("-" * 60)

rf_candidates = []

for name, obj in list(globals().items()):
    try:
        if isinstance(obj, RandomForestClassifier):
            rf_candidates.append((name, obj))
    except Exception:
        pass

print("Random Forest models found:")

for name, obj in rf_candidates:
    print(
        f"  {name} -> "
        f"{type(obj).__name__}, "
        f"trees={obj.n_estimators}, "
        f"features={obj.n_features_in_}"
    )

if len(rf_candidates) == 0:
    raise RuntimeError(
        "No RandomForestClassifier found. "
        "The trained model is not available."
    )

# If exactly one RF exists, use it.
# If multiple exist, prefer the one expecting 4354 features.

matching_models = [
    (name, obj)
    for name, obj in rf_candidates
    if getattr(obj, "n_features_in_", None) == 4354
]

if len(matching_models) == 1:
    model_name, rf_model = matching_models[0]

elif len(matching_models) > 1:
    raise RuntimeError(
        "Multiple Random Forest models expect 4354 features. "
        "Please identify the correct trained model."
    )

else:
    raise RuntimeError(
        "No Random Forest model found that expects "
        "4354 processed features."
    )

print("\nSelected trained model:", model_name)
print("Number of trees:", rf_model.n_estimators)
print("Model features:", rf_model.n_features_in_)

# ------------------------------------------------------------
# 3. VERIFY FEATURE COUNT
# ------------------------------------------------------------

if X_prediction_processed.shape[1] != rf_model.n_features_in_:
    raise ValueError(
        f"Feature mismatch: prediction has "
        f"{X_prediction_processed.shape[1]} features, "
        f"model expects {rf_model.n_features_in_}."
    )

print("\nFeature count: VERIFIED")

# ------------------------------------------------------------
# 4. GENERATE FUTURE RESIGNATION PROBABILITY
# ------------------------------------------------------------

print("\nGENERATING FUTURE RESIGNATION PROBABILITIES")
print("-" * 60)

prediction_probabilities = rf_model.predict_proba(
    X_prediction_processed
)[:, 1]

print(
    "Prediction probabilities generated:",
    len(prediction_probabilities)
)

print(
    "Minimum probability:",
    round(prediction_probabilities.min(), 4)
)

print(
    "Maximum probability:",
    round(prediction_probabilities.max(), 4)
)

print(
    "Mean probability:",
    round(prediction_probabilities.mean(), 4)
)

# ------------------------------------------------------------
# 5. APPLY BUSINESS THRESHOLD
# ------------------------------------------------------------

prediction_threshold = 0.50

predicted_attrition = (
    prediction_probabilities >= prediction_threshold
).astype(int)

print("\nPREDICTION THRESHOLD")
print("-" * 60)

print("Threshold:", prediction_threshold)

print(
    "Predicted future resignation cases:",
    int(predicted_attrition.sum())
)

print(
    "Predicted non-resignation cases:",
    int((predicted_attrition == 0).sum())
)

# ------------------------------------------------------------
# 6. CREATE RISK CATEGORY
# ------------------------------------------------------------

def get_risk_category(probability):

    if probability >= 0.50:
        return "High Risk"

    elif probability >= 0.20:
        return "Medium Risk"

    else:
        return "Low Risk"


risk_categories = [
    get_risk_category(p)
    for p in prediction_probabilities
]

# ------------------------------------------------------------
# 7. CREATE FINAL PREDICTION DATA
# ------------------------------------------------------------

prediction_results = model_data.copy()

# IMPORTANT:
# Historical Attrition is the target variable.
# It must NOT be presented as the future prediction.

if "Attrition" in prediction_results.columns:
    prediction_results = prediction_results.drop(
        columns=["Attrition"]
    )

prediction_results["Attrition_Probability"] = (
    prediction_probabilities
)

prediction_results["Attrition_Probability_%"] = (
    prediction_probabilities * 100
).round(2)

prediction_results["Predicted_Attrition"] = np.where(
    predicted_attrition == 1,
    "Yes",
    "No"
)

prediction_results["Risk_Category"] = risk_categories

# ------------------------------------------------------------
# 8. VERIFY RESULT
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("FUTURE RESIGNATION PREDICTION SUMMARY")
print("=" * 60)

print(
    "\nTotal employees evaluated:",
    len(prediction_results)
)

print(
    "Predicted future resignation:",
    int(predicted_attrition.sum())
)

print(
    "Predicted non-resignation:",
    int((predicted_attrition == 0).sum())
)

print("\nRISK DISTRIBUTION")
print("-" * 60)

print(
    prediction_results["Risk_Category"]
    .value_counts()
    .to_string()
)

# ------------------------------------------------------------
# 9. TOP 20 HIGH-RISK EMPLOYEES
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("TOP 20 EMPLOYEES BY FUTURE RESIGNATION RISK")
print("=" * 60)

top_risk_employees = (
    prediction_results
    .sort_values(
        "Attrition_Probability",
        ascending=False
    )
    .head(20)
)

# Find useful employee/business columns automatically
display_columns = []

possible_columns = [
    "Employee Code",
    "Employee ID",
    "Employee Name",
    "Name",
    "Title",
    "Designation",
    "Department",
    "Reporting Manager Name",
    "Site Name",
    "Cost Center",
    "Site Cost Center",
    "Client Vertical",
    "Monthly Gross Salary",
    "Annual_Gross_Salary",
    "Tenure_Years",
    "Age_Years",
    "Leave_Balance",
    "Attrition_Probability_%",
    "Predicted_Attrition",
    "Risk_Category"
]

for col in possible_columns:

    if col in top_risk_employees.columns:
        display_columns.append(col)

display(
    top_risk_employees[display_columns]
)

# ------------------------------------------------------------
# 10. SAVE FINAL PREDICTIONS
# ------------------------------------------------------------

prediction_results = prediction_results.sort_values(
    "Attrition_Probability",
    ascending=False
)

prediction_results.to_csv(
    "future_resignation_predictions.csv",
    index=False
)

print("\nSaved as:")
print("future_resignation_predictions.csv")

print("\n" + "=" * 60)
print("STEP 56 SUCCESS")
print("=" * 60)

============================================================
STEP 56: FUTURE RESIGNATION PREDICTION
============================================================

PREDICTION INPUT
------------------------------------------------------------
Processed prediction shape: (20468, 4354)
Expected shape: (20468, 4354)
Prediction data shape: VERIFIED

MODEL CHECK
------------------------------------------------------------
Random Forest models found:
  rf_model -> RandomForestClassifier, trees=300, features=4354

Selected trained model: rf_model
Number of trees: 300
Model features: 4354

Feature count: VERIFIED

GENERATING FUTURE RESIGNATION PROBABILITIES
------------------------------------------------------------

c:\Users\veena.sharma\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

Prediction probabilities generated: 20468
Minimum probability: 0.0
Maximum probability: 0.8688
Mean probability: 0.061

PREDICTION THRESHOLD
------------------------------------------------------------
Threshold: 0.5
Predicted future resignation cases: 192
Predicted non-resignation cases: 20276

============================================================
FUTURE RESIGNATION PREDICTION SUMMARY
============================================================

Total employees evaluated: 20468
Predicted future resignation: 192
Predicted non-resignation: 20276

RISK DISTRIBUTION
------------------------------------------------------------
Risk_Category
Low Risk       19065
Medium Risk     1211
High Risk        192

============================================================
TOP 20 EMPLOYEES BY FUTURE RESIGNATION RISK
============================================================

,Title,Designation,Department,Reporting Manager Name,Site Name,Cost Center,Site Cost Center,Client Vertical,Monthly Gross Salary,Annual_Gross_Salary,Tenure_Years,Age_Years,Leave_Balance,Attrition_Probability_%,Predicted_Attrition,Risk_Category
6598,Mr.,Housekeeper,Operations,Ramveer Bhagod,TELEPERFORMANCE GLOBAL HARYANA,TELEPERFORMANCE GLOBAL BUSINESS PVT LTD HARYANA,TELEPERFORMANCE GLOBAL BUSINESS PVT LTD HARYANA,North Region,NaN,NaN,NaN,44.369610,4.45,86.88,Yes,High Risk
9991,Mr.,Executive - Operations,Operations,Psipl Admin,A DIET EXPRESS HOSPITALITY CHENNAI MUMBAI,A DIET EXPRESS HOSPITALITY CHENNAI,A DIET EXPRESS HOSPITALITY CHENNAI,South - Chennai,NaN,NaN,NaN,37.708419,0.00,85.34,Yes,High Risk
12550,Mr.,Executive - Operations,Operations,Psipl Admin,A DIET EXPRESS HOSPITALITY CHENNAI MUMBAI,A DIET EXPRESS HOSPITALITY CHENNAI,A DIET EXPRESS HOSPITALITY CHENNAI,South - Chennai,NaN,NaN,NaN,37.708419,0.00,85.34,Yes,High Risk
14274,Mr.,Housekeeper,Operations,Ramveer Bhagod,TELEPERFORMANCE GLOBAL HARYANA,TELEPERFORMANCE GLOBAL BUSINESS PVT LTD HARYANA,TELEPERFORMANCE GLOBAL BUSINESS PVT LTD HARYANA,North Region,NaN,NaN,NaN,35.597536,4.36,85.33,Yes,High Risk
1691,Mr.,Housekeeper,Operations,Ramveer Bhagod,TELEPERFORMANCE GLOBAL HARYANA,TELEPERFORMANCE GLOBAL BUSINESS PVT LTD HARYANA,TELEPERFORMANCE GLOBAL BUSINESS PVT LTD HARYANA,North Region,NaN,NaN,NaN,38.652977,3.35,85.16,Yes,High Risk
20105,Mr.,Senior Executive - Finance & Accounts,Finance & Accounts,Psipl Admin,A DIET EXPRESS HOSPITALITY CHENNAI MUMBAI,A DIET EXPRESS HOSPITALITY CHENNAI,A DIET EXPRESS HOSPITALITY CHENNAI,South - Chennai,NaN,NaN,NaN,39.159480,0.00,84.27,Yes,High Risk
20071,Mr.,Senior Executive - Finance & Accounts,Finance & Accounts,Psipl Admin,A DIET EXPRESS HOSPITALITY CHENNAI MUMBAI,A DIET EXPRESS HOSPITALITY CHENNAI,A DIET EXPRESS HOSPITALITY CHENNAI,South - Chennai,NaN,NaN,NaN,39.159480,0.00,83.93,Yes,High Risk
14870,Mr.,Executive - Operations,Operations,Psipl Admin,ACESTAR PROPERTIES P3/P4 CHENNAI,ACESTAR PROPERTIES P3/P4 CHENNAI,ACESTAR PROPERTIES P3/P4 CHENNAI,South - Chennai,NaN,NaN,NaN,37.708419,0.00,83.77,Yes,High Risk
20072,Mr.,Executive - Operations,Operations,Psipl Admin,ACESTAR PROPERTIES P1/P2 CHENNAI,ACESTAR PROPERTIES P1/P2 CHENNAI,ACESTAR PROPERTIES P1/P2 CHENNAI,South - Chennai,NaN,NaN,NaN,37.708419,0.00,83.44,Yes,High Risk
9187,Mr.,Housekeeper,Operations,Ramveer Bhagod,TELEPERFORMANCE GLOBAL HARYANA,TELEPERFORMANCE GLOBAL BUSINESS PVT LTD HARYANA,TELEPERFORMANCE GLOBAL BUSINESS PVT LTD HARYANA,North Region,NaN,NaN,NaN,55.597536,4.36,83.30,Yes,High Risk
17029,Mr.,Housekeeper,Operations,Ramveer Bhagod,TELEPERFORMANCE GLOBAL HARYANA,TELEPERFORMANCE GLOBAL BUSINESS PVT LTD HARYANA,TELEPERFORMANCE GLOBAL BUSINESS PVT LTD HARYANA,North Region,513.0,6156.0,0.476386,39.600274,4.45,83.25,Yes,High Risk
9528,Mr.,Housekeeper,Operations,Ramveer Bhagod,TELEPERFORMANCE GLOBAL HARYANA,TELEPERFORMANCE GLOBAL BUSINESS PVT LTD HARYANA,TELEPERFORMANCE GLOBAL BUSINESS PVT LTD HARYANA,North Region,513.0,6156.0,0.473648,34.258727,1.88,82.89,Yes,High Risk
4407,Mr.,Housekeeper,Operations,Ramveer Bhagod,TELEPERFORMANCE GLOBAL HARYANA,TELEPERFORMANCE GLOBAL BUSINESS PVT LTD HARYANA,TELEPERFORMANCE GLOBAL BUSINESS PVT LTD HARYANA,North Region,513.0,6156.0,0.476386,24.470910,3.82,82.79,Yes,High Risk
17028,Mr.,Housekeeping Supervisor,Operations,Ramveer Bhagod,TELEPERFORMANCE GLOBAL HARYANA,TELEPERFORMANCE GLOBAL BUSINESS PVT LTD HARYANA,TELEPERFORMANCE GLOBAL BUSINESS PVT LTD HARYANA,North Region,NaN,NaN,NaN,28.698152,3.41,82.44,Yes,High Risk
1678,Mr.,Housekeeper,Operations,Ramveer Bhagod,TELEPERFORMANCE GLOBAL HARYANA,TELEPERFORMANCE GLOBAL BUSINESS PVT LTD HARYANA,TELEPERFORMANCE GLOBAL BUSINESS PVT LTD HARYANA,North Region,NaN,NaN,NaN,28.596851,4.85,82.06,Yes,High Risk
14869,Mr.,Executive - Operations,Operations,Psipl Admin,ACESTAR PROPERTIES P5/P6 CHENNAI,ACESTAR PROPERTIES P5/P6 CHENNAI,ACESTAR PROPERTIES P5/P6 CHENNAI,South - Chennai,NaN,NaN,NaN,37.708419,1.00,81.36,Yes,High Risk
12445,Mr.,Housekeeper,Operations,Trupti Sunil Medhekar,KALPATARU 6 8 9 10 FLOOR MUMBAI,KALPATARU SYNERGY-6/8/9/10TH FLR,KALPATARU SYNERGY-6/8/9/10TH FLR,Residential,NaN,NaN,NaN,26.130048,0.03,80.38,Yes,High Risk
9281,Mr.,Housekeeper,Operations,Neeraj,PEPSICO UTTAR PRADESH,PEPSICO HOLDING UTTAR PRADES,PEPSICO HOLDING UTTAR PRADES,North Region,NaN,NaN,NaN,25.423682,8.82,79.79,Yes,High Risk
17556,Ms.,Housekeeper,Operations,Trupti Sunil Medhekar,KALPATARU 6 8 9 10 FLOOR MUMBAI,KALPATARU SYNERGY-6/8/9/10TH FLR,KALPATARU SYNERGY-6/8/9/10TH FLR,Residential,NaN,NaN,NaN,22.844627,-0.04,79.75,Yes,High Risk
6579,Mr.,Housekeeper,Operations,Ramveer Bhagod,TELEPERFORMANCE GLOBAL HARYANA,TELEPERFORMANCE GLOBAL BUSINESS PVT LTD HARYANA,TELEPERFORMANCE GLOBAL BUSINESS PVT LTD HARYANA,North Region,NaN,NaN,NaN,34.833676,1.92,79.53,Yes,High Risk

Saved as:
future_resignation_predictions.csv

============================================================
STEP 56 SUCCESS
============================================================

In [ ]:

# ============================================================
# STEP 57: FINAL BUSINESS OUTPUT
# ============================================================

import pandas as pd
import numpy as np
import os

print("\n" + "=" * 70)
print("STEP 57: FINAL FUTURE RESIGNATION BUSINESS OUTPUT")
print("=" * 70)

# ------------------------------------------------------------
# 1. LOAD THE PREDICTION FILE CREATED IN STEP 56
# ------------------------------------------------------------

prediction_file = "future_resignation_predictions.csv"

if not os.path.exists(prediction_file):
    raise FileNotFoundError(
        f"{prediction_file} was not found. "
        "Please run Step 56 first."
    )

final_predictions = pd.read_csv(prediction_file)

print("\nPrediction file loaded:")
print("Shape:", final_predictions.shape)

# ------------------------------------------------------------
# 2. DISPLAY AVAILABLE COLUMNS
# ------------------------------------------------------------

print("\nAvailable prediction columns:")
print(final_predictions.columns.tolist())

# ------------------------------------------------------------
# 3. IDENTIFY PROBABILITY COLUMN
# ------------------------------------------------------------

probability_candidates = [
    "Future_Resignation_Probability",
    "Resignation_Probability",
    "Future_Resignation_Prob",
    "Prediction_Probability",
    "Probability",
    "Attrition_Probability"
]

probability_column = None

for col in probability_candidates:
    if col in final_predictions.columns:
        probability_column = col
        break

if probability_column is None:
    raise ValueError(
        "Could not identify the resignation probability column. "
        "Check the column list printed above."
    )

print("\nProbability column:", probability_column)

# ------------------------------------------------------------
# 4. IDENTIFY / CREATE RISK CATEGORY
# ------------------------------------------------------------

risk_candidates = [
    "Risk_Category",
    "Future_Resignation_Risk",
    "Risk",
    "Attrition_Risk"
]

risk_column = None

for col in risk_candidates:
    if col in final_predictions.columns:
        risk_column = col
        break

if risk_column is None:

    # Create risk category from probability
    def assign_risk(probability):
        if probability >= 0.50:
            return "High Risk"
        elif probability >= 0.20:
            return "Medium Risk"
        else:
            return "Low Risk"

    final_predictions["Risk_Category"] = (
        final_predictions[probability_column]
        .apply(assign_risk)
    )

    risk_column = "Risk_Category"

# ------------------------------------------------------------
# 5. STANDARDIZE PROBABILITY
# ------------------------------------------------------------

final_predictions[probability_column] = pd.to_numeric(
    final_predictions[probability_column],
    errors="coerce"
)

# If probability is stored as percentage (e.g. 86.88)
# convert it to decimal (0.8688)
if final_predictions[probability_column].max() > 1:
    final_predictions[probability_column] = (
        final_predictions[probability_column] / 100
    )

final_predictions["Resignation_Probability_%"] = (
    final_predictions[probability_column] * 100
).round(2)

# ------------------------------------------------------------
# 6. CREATE RISK RANK
# ------------------------------------------------------------

final_predictions = final_predictions.sort_values(
    by=probability_column,
    ascending=False
).reset_index(drop=True)

final_predictions["Risk_Rank"] = (
    final_predictions.index + 1
)

# ------------------------------------------------------------
# 7. CREATE FINAL BUSINESS DATASET
# ------------------------------------------------------------

# Keep useful employee/business columns if they exist
preferred_columns = [
    "Employee ID",
    "Employee_ID",
    "Employee Code",
    "Employee_Code",
    "Title",
    "Designation",
    "Department",
    "Reporting Manager Name",
    "Site Name",
    "Cost Center",
    "Site Cost Center",
    "Client Vertical",
    "Monthly Gross Salary",
    "Annual_Gross_Salary",
    "Tenure_Years",
    "Calculated_Tenure_Years",
    "Leave_Balance",
    "Leave_Consumed",
    "Leave_Future_Approved",
    "OT1_Total_OT",
    "OT2_Total_OT",
    "OT3_Total_OT",
    "OT4_Total_OT",
    "Salary_Data_Available",
    "Leave_Data_Available",
    "Resignation_Probability_%",
    "Risk_Category",
    "Risk_Rank"
]

available_columns = [
    col for col in preferred_columns
    if col in final_predictions.columns
]

final_business_output = final_predictions[available_columns].copy()

# ------------------------------------------------------------
# 8. IF NO EMPLOYEE ID EXISTS, PRESERVE ORIGINAL ROW ID
# ------------------------------------------------------------

id_columns = [
    "Employee ID",
    "Employee_ID",
    "Employee Code",
    "Employee_Code"
]

if not any(col in final_business_output.columns for col in id_columns):

    # Use original prediction row number as reference
    final_business_output.insert(
        0,
        "Employee_Row_ID",
        np.arange(1, len(final_business_output) + 1)
    )

# ------------------------------------------------------------
# 9. FINAL SUMMARY
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("FINAL FUTURE RESIGNATION PREDICTION SUMMARY")
print("=" * 70)

print(
    "\nTotal employees evaluated:",
    len(final_business_output)
)

print(
    "Predicted High Risk:",
    (final_predictions[risk_column] == "High Risk").sum()
)

print(
    "Predicted Medium Risk:",
    (final_predictions[risk_column] == "Medium Risk").sum()
)

print(
    "Predicted Low Risk:",
    (final_predictions[risk_column] == "Low Risk").sum()
)

print(
    "\nAverage resignation probability:",
    round(
        final_predictions[probability_column].mean() * 100,
        2
    ),
    "%"
)

print(
    "Maximum resignation probability:",
    round(
        final_predictions[probability_column].max() * 100,
        2
    ),
    "%"
)

# ------------------------------------------------------------
# 10. RISK DISTRIBUTION
# ------------------------------------------------------------

print("\nRISK DISTRIBUTION")
print("-" * 50)

risk_distribution = (
    final_predictions[risk_column]
    .value_counts()
    .reindex(
        ["High Risk", "Medium Risk", "Low Risk"],
        fill_value=0
    )
)

print(risk_distribution)

# ------------------------------------------------------------
# 11. TOP 20 HIGH-RISK EMPLOYEES
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("TOP 20 EMPLOYEES BY FUTURE RESIGNATION RISK")
print("=" * 70)

display(
    final_business_output.head(20)
)

# ------------------------------------------------------------
# 12. SAVE FINAL BUSINESS OUTPUT
# ------------------------------------------------------------

output_file = "final_future_resignation_predictions.csv"

final_business_output.to_csv(
    output_file,
    index=False
)

print("\n" + "=" * 70)
print("FINAL OUTPUT FILE CREATED")
print("=" * 70)

print("\nFile:", output_file)
print("Rows:", len(final_business_output))
print("Columns:", len(final_business_output.columns))

print("\nSTEP 57 SUCCESS")
print("=" * 70)

======================================================================
STEP 57: FINAL FUTURE RESIGNATION BUSINESS OUTPUT
======================================================================

Prediction file loaded:
Shape: (20468, 90)

Available prediction columns:
['Title', 'City Name', 'State Name', 'Branch', 'Site Branch', 'Designation', 'Department', 'Cost Center', 'Site Cost Center', 'Site Name', 'Grade', 'Band', 'Reason for Requirement', 'Employee Category', 'Reporting Manager Code', 'Reporting Manager Name', 'Skip Level Manager Code', 'Skip Level Manager', 'Actual Join Date', 'Group Join Date', 'Year Of Service (Current DOJ)', 'Year of Service (Group DOJ)', 'ESIC Flag', 'PF Applicable', 'PF Type', 'Probation Status', 'Confirmation Date', 'Source of Hire', 'Effective Start Date', 'Conf. Date (Period Master)', 'Employer Notice Period', 'Bank Name', 'Movement Type', 'Birth Date', 'Cost Code', 'Profit Code', 'Client Vertical', 'Resident', 'Wage Type', 'TAX Regime', 'Uniform Deduction', 'Location', 'Region Name', 'Client Verticle', 'Date Of Joined', 'Created Date', 'Monthly Gross Salary', 'Annual_Gross_Salary', 'Tenure_Days', 'Tenure_Years', 'OT1_Chargeable_OT', 'OT1_NonChargeable_OT', 'OT1_Total_OT', 'OT1_OT_Days', 'OT1_Avg_Daily_OT', 'OT1_Max_Daily_OT', 'OT2_Chargeable_OT', 'OT2_NonChargeable_OT', 'OT2_Total_OT', 'OT3_Chargeable_OT', 'OT3_NonChargeable_OT', 'OT3_Total_OT', 'OT4_Chargeable_OT', 'OT4_NonChargeable_OT', 'OT4_Total_OT', 'OT4_OT_Days', 'OT4_Avg_Daily_OT', 'OT4_Max_Daily_OT', 'Leave_Opening_Balance', 'Leave_Accrued', 'Leave_Consumed', 'Leave_Balance', 'Leave_Future_Approved', 'Leave_Balance_After_Future', 'Leave_Carry_Forward', 'Leave_Record_Count', 'Leave_Type_Count', 'Age_Years', 'Calculated_Tenure_Years', 'Is_Confirmed', 'OT1_Data_Available', 'OT2_Data_Available', 'OT3_Data_Available', 'OT4_Data_Available', 'Salary_Data_Available', 'Leave_Data_Available', 'Attrition_Probability', 'Attrition_Probability_%', 'Predicted_Attrition', 'Risk_Category']

Probability column: Attrition_Probability

======================================================================
FINAL FUTURE RESIGNATION PREDICTION SUMMARY
======================================================================

Total employees evaluated: 20468
Predicted High Risk: 192
Predicted Medium Risk: 1211
Predicted Low Risk: 19065

Average resignation probability: 6.1 %
Maximum resignation probability: 86.88 %

RISK DISTRIBUTION
--------------------------------------------------
Risk_Category
High Risk        192
Medium Risk     1211
Low Risk       19065
Name: count, dtype: int64

======================================================================
TOP 20 EMPLOYEES BY FUTURE RESIGNATION RISK
======================================================================

,Employee_Row_ID,Title,Designation,Department,Reporting Manager Name,Site Name,Cost Center,Site Cost Center,Client Vertical,Monthly Gross Salary,...,Leave_Future_Approved,OT1_Total_OT,OT2_Total_OT,OT3_Total_OT,OT4_Total_OT,Salary_Data_Available,Leave_Data_Available,Resignation_Probability_%,Risk_Category,Risk_Rank
0,1,Mr.,Housekeeper,Operations,Ramveer Bhagod,TELEPERFORMANCE GLOBAL HARYANA,TELEPERFORMANCE GLOBAL BUSINESS PVT LTD HARYANA,TELEPERFORMANCE GLOBAL BUSINESS PVT LTD HARYANA,North Region,NaN,...,0.0,0.0,0.0,0.0,0.0,0,1,86.88,High Risk,1
1,2,Mr.,Executive - Operations,Operations,Psipl Admin,A DIET EXPRESS HOSPITALITY CHENNAI MUMBAI,A DIET EXPRESS HOSPITALITY CHENNAI,A DIET EXPRESS HOSPITALITY CHENNAI,South - Chennai,NaN,...,0.0,0.0,0.0,0.0,0.0,0,1,85.34,High Risk,2
2,3,Mr.,Executive - Operations,Operations,Psipl Admin,A DIET EXPRESS HOSPITALITY CHENNAI MUMBAI,A DIET EXPRESS HOSPITALITY CHENNAI,A DIET EXPRESS HOSPITALITY CHENNAI,South - Chennai,NaN,...,0.0,0.0,0.0,0.0,0.0,0,1,85.34,High Risk,3
3,4,Mr.,Housekeeper,Operations,Ramveer Bhagod,TELEPERFORMANCE GLOBAL HARYANA,TELEPERFORMANCE GLOBAL BUSINESS PVT LTD HARYANA,TELEPERFORMANCE GLOBAL BUSINESS PVT LTD HARYANA,North Region,NaN,...,0.0,0.0,0.0,0.0,0.0,0,1,85.33,High Risk,4
4,5,Mr.,Housekeeper,Operations,Ramveer Bhagod,TELEPERFORMANCE GLOBAL HARYANA,TELEPERFORMANCE GLOBAL BUSINESS PVT LTD HARYANA,TELEPERFORMANCE GLOBAL BUSINESS PVT LTD HARYANA,North Region,NaN,...,0.0,0.0,0.0,0.0,0.0,0,1,85.16,High Risk,5
5,6,Mr.,Senior Executive - Finance & Accounts,Finance & Accounts,Psipl Admin,A DIET EXPRESS HOSPITALITY CHENNAI MUMBAI,A DIET EXPRESS HOSPITALITY CHENNAI,A DIET EXPRESS HOSPITALITY CHENNAI,South - Chennai,NaN,...,0.0,0.0,0.0,0.0,0.0,0,1,84.27,High Risk,6
6,7,Mr.,Senior Executive - Finance & Accounts,Finance & Accounts,Psipl Admin,A DIET EXPRESS HOSPITALITY CHENNAI MUMBAI,A DIET EXPRESS HOSPITALITY CHENNAI,A DIET EXPRESS HOSPITALITY CHENNAI,South - Chennai,NaN,...,0.0,0.0,0.0,0.0,0.0,0,1,83.93,High Risk,7
7,8,Mr.,Executive - Operations,Operations,Psipl Admin,ACESTAR PROPERTIES P3/P4 CHENNAI,ACESTAR PROPERTIES P3/P4 CHENNAI,ACESTAR PROPERTIES P3/P4 CHENNAI,South - Chennai,NaN,...,0.0,0.0,0.0,0.0,0.0,0,1,83.77,High Risk,8
8,9,Mr.,Executive - Operations,Operations,Psipl Admin,ACESTAR PROPERTIES P1/P2 CHENNAI,ACESTAR PROPERTIES P1/P2 CHENNAI,ACESTAR PROPERTIES P1/P2 CHENNAI,South - Chennai,NaN,...,0.0,0.0,0.0,0.0,0.0,0,1,83.44,High Risk,9
9,10,Mr.,Housekeeper,Operations,Ramveer Bhagod,TELEPERFORMANCE GLOBAL HARYANA,TELEPERFORMANCE GLOBAL BUSINESS PVT LTD HARYANA,TELEPERFORMANCE GLOBAL BUSINESS PVT LTD HARYANA,North Region,NaN,...,0.0,0.0,0.0,0.0,0.0,0,1,83.30,High Risk,10
10,11,Mr.,Housekeeper,Operations,Ramveer Bhagod,TELEPERFORMANCE GLOBAL HARYANA,TELEPERFORMANCE GLOBAL BUSINESS PVT LTD HARYANA,TELEPERFORMANCE GLOBAL BUSINESS PVT LTD HARYANA,North Region,513.0,...,0.0,0.0,0.0,0.0,0.0,1,1,83.25,High Risk,11
11,12,Mr.,Housekeeper,Operations,Ramveer Bhagod,TELEPERFORMANCE GLOBAL HARYANA,TELEPERFORMANCE GLOBAL BUSINESS PVT LTD HARYANA,TELEPERFORMANCE GLOBAL BUSINESS PVT LTD HARYANA,North Region,513.0,...,0.0,0.0,0.0,0.0,0.0,1,1,82.89,High Risk,12
12,13,Mr.,Housekeeper,Operations,Ramveer Bhagod,TELEPERFORMANCE GLOBAL HARYANA,TELEPERFORMANCE GLOBAL BUSINESS PVT LTD HARYANA,TELEPERFORMANCE GLOBAL BUSINESS PVT LTD HARYANA,North Region,513.0,...,0.0,0.0,0.0,0.0,0.0,1,1,82.79,High Risk,13
13,14,Mr.,Housekeeping Supervisor,Operations,Ramveer Bhagod,TELEPERFORMANCE GLOBAL HARYANA,TELEPERFORMANCE GLOBAL BUSINESS PVT LTD HARYANA,TELEPERFORMANCE GLOBAL BUSINESS PVT LTD HARYANA,North Region,NaN,...,0.0,0.0,0.0,0.0,0.0,0,1,82.44,High Risk,14
14,15,Mr.,Housekeeper,Operations,Ramveer Bhagod,TELEPERFORMANCE GLOBAL HARYANA,TELEPERFORMANCE GLOBAL BUSINESS PVT LTD HARYANA,TELEPERFORMANCE GLOBAL BUSINESS PVT LTD HARYANA,North Region,NaN,...,0.0,0.0,0.0,0.0,0.0,0,1,82.06,High Risk,15
15,16,Mr.,Executive - Operations,Operations,Psipl Admin,ACESTAR PROPERTIES P5/P6 CHENNAI,ACESTAR PROPERTIES P5/P6 CHENNAI,ACESTAR PROPERTIES P5/P6 CHENNAI,South - Chennai,NaN,...,0.0,0.0,0.0,0.0,0.0,0,1,81.36,High Risk,16
16,17,Mr.,Housekeeper,Operations,Trupti Sunil Medhekar,KALPATARU 6 8 9 10 FLOOR MUMBAI,KALPATARU SYNERGY-6/8/9/10TH FLR,KALPATARU SYNERGY-6/8/9/10TH FLR,Residential,NaN,...,0.0,0.0,0.0,0.0,0.0,0,1,80.38,High Risk,17
17,18,Mr.,Housekeeper,Operations,Neeraj,PEPSICO UTTAR PRADESH,PEPSICO HOLDING UTTAR PRADES,PEPSICO HOLDING UTTAR PRADES,North Region,NaN,...,0.0,0.0,0.0,35.0,35.0,0,1,79.79,High Risk,18
18,19,Ms.,Housekeeper,Operations,Trupti Sunil Medhekar,KALPATARU 6 8 9 10 FLOOR MUMBAI,KALPATARU SYNERGY-6/8/9/10TH FLR,KALPATARU SYNERGY-6/8/9/10TH FLR,Residential,NaN,...,0.0,0.0,0.0,0.0,0.0,0,1,79.75,High Risk,19
19,20,Mr.,Housekeeper,Operations,Ramveer Bhagod,TELEPERFORMANCE GLOBAL HARYANA,TELEPERFORMANCE GLOBAL BUSINESS PVT LTD HARYANA,TELEPERFORMANCE GLOBAL BUSINESS PVT LTD HARYANA,North Region,NaN,...,0.0,0.0,0.0,0.0,0.0,0,1,79.53,High Risk,20

======================================================================
FINAL OUTPUT FILE CREATED
======================================================================

File: final_future_resignation_predictions.csv
Rows: 20468
Columns: 25

STEP 57 SUCCESS
======================================================================

In [56]:
# Find DataFrames containing the final prediction output

import pandas as pd

print("DataFrames currently available:")
print("=" * 60)

for name, obj in list(globals().items()):
    if isinstance(obj, pd.DataFrame):
        print(f"{name} -> {obj.shape}")

DataFrames currently available:
============================================================
employee_master -> (20486, 94)
resignation_data -> (7778, 46)
overtime_data1 -> (3228, 109)
overtime_data2 -> (3228, 19)
overtime_data3 -> (4783, 19)
overtime_data4 -> (4783, 112)
leave_data -> (31523, 28)
form_data -> (9762, 197)
resignation_matches -> (237, 44)
status_lwd -> (13, 2)
model_base -> (20468, 140)
attrition_rows -> (241, 95)
duplicate_records -> (35, 95)
duplicate_check -> (35, 11)
df -> (4781, 7)
ot1_features -> (3218, 7)
ot4_features -> (4781, 7)
leave -> (31523, 29)
leave_features -> (25952, 13)
form -> (9762, 198)
form_features -> (9762, 16)
form_features_clean -> (7889, 16)
form_merge -> (7889, 16)
ot2_features -> (3218, 4)
ot3_features -> (4781, 4)
feature_audit -> (109, 6)
high_cardinality -> (3, 6)
feature_audit_final -> (79, 6)
model_data -> (20468, 87)
rf_data -> (20468, 87)
X -> (20468, 94)
X_train -> (16374, 94)
X_test -> (4094, 94)

In [57]:

# Check employee-identification columns in the 20,468-row dataframes

for name, obj in list(globals().items()):
    if isinstance(obj, pd.DataFrame) and len(obj) == 20468:
        print("\n" + "=" * 70)
        print("DATAFRAME:", name)
        print("SHAPE:", obj.shape)

        id_cols = [
            c for c in obj.columns
            if any(x in c.lower() for x in [
                "employee", "emp_code", "emp id", "emp_id", "name"
            ])
        ]

        print("Employee-related columns:")
        print(id_cols)

        if id_cols:
            display(obj[id_cols].head())

======================================================================
DATAFRAME: model_base
SHAPE: (20468, 140)
Employee-related columns:
['Company Name', 'Employee Code', 'First Name', 'Middle Name', 'Last Name', 'Employee Name', 'City Name', 'State Name', 'Site Name', 'Employee Category', 'Employee Status', 'Reporting Manager Name', 'Preferred Name', 'Employee Air Ticket', 'Bank Name', 'Father Name', 'Process Name', 'Employee_Code_Clean', '_emp_code', 'Employee Status_form', 'Region Name', 'Site Name_form']

,Company Name,Employee Code,First Name,Middle Name,Last Name,Employee Name,City Name,State Name,Site Name,Employee Category,...,Preferred Name,Employee Air Ticket,Bank Name,Father Name,Process Name,Employee_Code_Clean,_emp_code,Employee Status_form,Region Name,Site Name_form
0,Property Solutions India Pvt Ltd,'566137,Kaustubh,Dattaram,Patil,Kaustubh Dattaram Patil,Mumbai,Maharashtra,BLINK COMMERCE MUMBAI,Permanent,...,Kaustubh,No,NEFT,Dattaram Patil,NaN,566137,566137,NaN,NaN,NaN
1,Property Solutions India Pvt Ltd,'534669,Dibakar,NaN,Pattanaik,Dibakar Pattanaik,Odisha,Odisha,SPORTS & ODISHA,Permanent,...,Dibakar,No,NEFT,SARBESWAR MOHANTY,NaN,534669,534669,NaN,NaN,NaN
2,Property Solutions India Pvt Ltd,'560618,Anil,Tanaji,Dubole,Anil Tanaji Dubole,Mumbai,Maharashtra,NEELKANT MUMBAI,Permanent,...,Anil,No,AXIS BANK LTD,S/O Tanaji Dubole,NaN,560618,560618,NaN,NaN,NaN
3,Property Solutions India Pvt Ltd,'48681,Sudhakar,Anand,Hankare,Sudhakar Anand Hankare,Mumbai,Maharashtra,PROJECT MUMBAI,Permanent,...,Sudhakar,No,NEFT,NaN,NaN,48681,48681,NaN,NaN,NaN
4,Property Solutions India Pvt Ltd,'62969,Shriram,Seetaram,Kanoje,Shriram Seetaram Kanoje,Mumbai,Maharashtra,KALPATARU BAYER MUMBAI,Permanent,...,Shriram,No,NEFT,SEETARAM,NaN,62969,62969,NaN,NaN,NaN

======================================================================
DATAFRAME: model_data
SHAPE: (20468, 87)
Employee-related columns:
['City Name', 'State Name', 'Site Name', 'Employee Category', 'Reporting Manager Name', 'Bank Name', 'Region Name']

,City Name,State Name,Site Name,Employee Category,Reporting Manager Name,Bank Name,Region Name
0,Mumbai,Maharashtra,BLINK COMMERCE MUMBAI,Permanent,Mahendra Vasant Ghulghule,NEFT,NaN
1,Odisha,Odisha,SPORTS & ODISHA,Permanent,Ajaya Kumar Rout,NEFT,NaN
2,Mumbai,Maharashtra,NEELKANT MUMBAI,Permanent,Sunita Ajay Mane,AXIS BANK LTD,NaN
3,Mumbai,Maharashtra,PROJECT MUMBAI,Permanent,Omkar Vitthal Parab,NEFT,NaN
4,Mumbai,Maharashtra,KALPATARU BAYER MUMBAI,Permanent,Rajesh Ramesh Vilankar,NEFT,NaN

======================================================================
DATAFRAME: rf_data
SHAPE: (20468, 87)
Employee-related columns:
['City Name', 'State Name', 'Site Name', 'Employee Category', 'Reporting Manager Name', 'Bank Name', 'Region Name']

,City Name,State Name,Site Name,Employee Category,Reporting Manager Name,Bank Name,Region Name
0,Mumbai,Maharashtra,BLINK COMMERCE MUMBAI,Permanent,Mahendra Vasant Ghulghule,NEFT,NaN
1,Odisha,Odisha,SPORTS & ODISHA,Permanent,Ajaya Kumar Rout,NEFT,NaN
2,Mumbai,Maharashtra,NEELKANT MUMBAI,Permanent,Sunita Ajay Mane,AXIS BANK LTD,NaN
3,Mumbai,Maharashtra,PROJECT MUMBAI,Permanent,Omkar Vitthal Parab,NEFT,NaN
4,Mumbai,Maharashtra,KALPATARU BAYER MUMBAI,Permanent,Rajesh Ramesh Vilankar,NEFT,NaN

======================================================================
DATAFRAME: X
SHAPE: (20468, 94)
Employee-related columns:
['City Name', 'State Name', 'Site Name', 'Employee Category', 'Reporting Manager Name', 'Bank Name', 'Region Name']

,City Name,State Name,Site Name,Employee Category,Reporting Manager Name,Bank Name,Region Name
0,Mumbai,Maharashtra,BLINK COMMERCE MUMBAI,Permanent,Mahendra Vasant Ghulghule,NEFT,NaN
1,Odisha,Odisha,SPORTS & ODISHA,Permanent,Ajaya Kumar Rout,NEFT,NaN
2,Mumbai,Maharashtra,NEELKANT MUMBAI,Permanent,Sunita Ajay Mane,AXIS BANK LTD,NaN
3,Mumbai,Maharashtra,PROJECT MUMBAI,Permanent,Omkar Vitthal Parab,NEFT,NaN
4,Mumbai,Maharashtra,KALPATARU BAYER MUMBAI,Permanent,Rajesh Ramesh Vilankar,NEFT,NaN

In [59]:
print("Prediction Dataframe columns:")
print(prediction_df.columns.tolist())

Prediction Dataframe columns:
['Employee_Row_ID', 'Title', 'Designation', 'Department', 'Reporting Manager Name', 'Site Name', 'Cost Center', 'Site Cost Center', 'Client Vertical', 'Monthly Gross Salary', 'Annual_Gross_Salary', 'Tenure_Years', 'Calculated_Tenure_Years', 'Leave_Balance', 'Leave_Consumed', 'Leave_Future_Approved', 'OT1_Total_OT', 'OT2_Total_OT', 'OT3_Total_OT', 'OT4_Total_OT', 'Salary_Data_Available', 'Leave_Data_Available', 'Resignation_Probability_%', 'Risk_Category', 'Risk_Rank', 'Employee Code', 'Employee Name']

In [60]:
# ============================================================
# EMPLOYEE NAME + CODE MAPPING
# ============================================================

# Employee mapping from model_base
employee_mapping = model_base[
    ["Employee Code", "Employee Name"]
].copy()

# Employee_Row_ID corresponds to original employee row
employee_mapping["Employee_Row_ID"] = range(1, len(employee_mapping) + 1)

# Remove existing employee columns if any
prediction_df = prediction_df.drop(
    columns=["Employee Code", "Employee Name"],
    errors="ignore"
)

# Map employee details
prediction_df = prediction_df.merge(
    employee_mapping,
    on="Employee_Row_ID",
    how="left"
)

print("Final prediction shape:", prediction_df.shape)

# Show available important columns
display(
    prediction_df[
        [
            "Employee_Row_ID",
            "Employee Code",
            "Employee Name",
            "Resignation_Probability_%",
            "Risk_Category"
        ]
    ].head(20)
)

print("\nMissing Employee Codes:",
      prediction_df["Employee Code"].isna().sum())

print("Missing Employee Names:",
      prediction_df["Employee Name"].isna().sum())

Final prediction shape: (20468, 27)

,Employee_Row_ID,Employee Code,Employee Name,Resignation_Probability_%,Risk_Category
0,1,'566137,Kaustubh Dattaram Patil,86.88,High Risk
1,2,'534669,Dibakar Pattanaik,85.34,High Risk
2,3,'560618,Anil Tanaji Dubole,85.34,High Risk
3,4,'48681,Sudhakar Anand Hankare,85.33,High Risk
4,5,'62969,Shriram Seetaram Kanoje,85.16,High Risk
5,6,'62053,Girish Motiram Jadhav,84.27,High Risk
6,7,'522934,Rahul Ramchandra Dhavade,83.93,High Risk
7,8,'550389,SACHIN PANDURANG WAINGADE,83.77,High Risk
8,9,'558924,Sonu Narottam Goud,83.44,High Risk
9,10,'541817,Amol Vitthal Raut,83.30,High Risk
10,11,'531572,Rajesh Majhi,83.25,High Risk
11,12,'536531,Shashikanta Jena,82.89,High Risk
12,13,'541183,Naba Kishor Mohanty,82.79,High Risk
13,14,'547365,DATTA SAHEBRAO CHAURE,82.44,High Risk
14,15,'548593,Santosh Kumar Nayak,82.06,High Risk
15,16,'516654,Suhas Balu Pote,81.36,High Risk
16,17,'565337,Ashfak Maqbul Shaikh,80.38,High Risk
17,18,'547153,Mithun Biswal,79.79,High Risk
18,19,'540321,Smruti Ranjan Das,79.75,High Risk
19,20,'550204,BIRENDRA KUMAR BARAL,79.53,High Risk

Missing Employee Codes: 0
Missing Employee Names: 0

In [61]:
print("TOTAL EMPLOYEES:", len(prediction_df))
print("\nRisk distribution:")
print(prediction_df["Risk_Category"].value_counts())
print("\nLast 5 employees:")
display(
    prediction_df[
        [
            "Employee_Row_ID",
            "Employee Code",
            "Employee Name",
            "Resignation_Probability_%",
            "Risk_Category"
        ]
    ].tail()
)

TOTAL EMPLOYEES: 20468

Risk distribution:
Risk_Category
Low Risk       19065
Medium Risk     1211
High Risk        192
Name: count, dtype: int64

Last 5 employees:

,Employee_Row_ID,Employee Code,Employee Name,Resignation_Probability_%,Risk_Category
20463,20464,'586474,SUDHIR DIGAL,0.0,Low Risk
20464,20465,'586477,AKASH PAWAR,0.0,Low Risk
20465,20466,'586479,YOB ALLWIN ABHISHEK,0.0,Low Risk
20466,20467,'586499,Ajinkya Ashok Sakpal,0.0,Low Risk
20467,20468,'586504,RAVINDRA DHONDU GAYKWAD,0.0,Low Risk

In [62]:
# ============================================================
# STEP 58: FINAL EMPLOYEE-LEVEL RESIGNATION OUTPUT
# ============================================================

# Select the important employee-level prediction columns
final_columns = [
    "Employee_Row_ID",
    "Employee Code",
    "Employee Name",
    "Designation",
    "Department",
    "Reporting Manager Name",
    "Site Name",
    "Cost Center",
    "Client Vertical",
    "Monthly Gross Salary",
    "Annual_Gross_Salary",
    "Tenure_Years",
    "Age_Years",
    "OT1_Total_OT",
    "OT2_Total_OT",
    "OT3_Total_OT",
    "OT4_Total_OT",
    "Leave_Balance",
    "Leave_Consumed",
    "Leave_Future_Approved",
    "Salary_Data_Available",
    "Leave_Data_Available",
    "Resignation_Probability_%",
    "Risk_Category"
]

# Keep only columns that actually exist
final_columns = [
    col for col in final_columns
    if col in prediction_df.columns
]

final_resignation_output = prediction_df[final_columns].copy()

# Sort highest resignation risk first
final_resignation_output = final_resignation_output.sort_values(
    by="Resignation_Probability_%",
    ascending=False
).reset_index(drop=True)

# Add final risk rank
final_resignation_output["Risk_Rank"] = (
    final_resignation_output["Resignation_Probability_%"]
    .rank(method="first", ascending=False)
    .astype(int)
)

# Save final CSV
final_file = "FINAL_EMPLOYEE_LEVEL_RESIGNATION_PREDICTION.csv"

final_resignation_output.to_csv(
    final_file,
    index=False
)

# Final verification
print("=" * 70)
print("FINAL EMPLOYEE-LEVEL RESIGNATION OUTPUT")
print("=" * 70)

print("Total employees:", len(final_resignation_output))
print("Total columns:", len(final_resignation_output.columns))

print("\nRisk distribution:")
print(final_resignation_output["Risk_Category"].value_counts())

print("\nMissing Employee Codes:",
      final_resignation_output["Employee Code"].isna().sum())

print("Missing Employee Names:",
      final_resignation_output["Employee Name"].isna().sum())

print("\nFile created:")
print(final_file)

print("\nTop 10 highest-risk employees:")
display(final_resignation_output.head(10))

======================================================================
FINAL EMPLOYEE-LEVEL RESIGNATION OUTPUT
======================================================================
Total employees: 20468
Total columns: 24

Risk distribution:
Risk_Category
Low Risk       19065
Medium Risk     1211
High Risk        192
Name: count, dtype: int64

Missing Employee Codes: 0
Missing Employee Names: 0

File created:
FINAL_EMPLOYEE_LEVEL_RESIGNATION_PREDICTION.csv

Top 10 highest-risk employees:

,Employee_Row_ID,Employee Code,Employee Name,Designation,Department,Reporting Manager Name,Site Name,Cost Center,Client Vertical,Monthly Gross Salary,...,OT3_Total_OT,OT4_Total_OT,Leave_Balance,Leave_Consumed,Leave_Future_Approved,Salary_Data_Available,Leave_Data_Available,Resignation_Probability_%,Risk_Category,Risk_Rank
0,1,'566137,Kaustubh Dattaram Patil,Housekeeper,Operations,Ramveer Bhagod,TELEPERFORMANCE GLOBAL HARYANA,TELEPERFORMANCE GLOBAL BUSINESS PVT LTD HARYANA,North Region,NaN,...,0.0,0.0,4.45,0.0,0.0,0,1,86.88,High Risk,1
1,2,'534669,Dibakar Pattanaik,Executive - Operations,Operations,Psipl Admin,A DIET EXPRESS HOSPITALITY CHENNAI MUMBAI,A DIET EXPRESS HOSPITALITY CHENNAI,South - Chennai,NaN,...,0.0,0.0,0.00,0.0,0.0,0,1,85.34,High Risk,2
2,3,'560618,Anil Tanaji Dubole,Executive - Operations,Operations,Psipl Admin,A DIET EXPRESS HOSPITALITY CHENNAI MUMBAI,A DIET EXPRESS HOSPITALITY CHENNAI,South - Chennai,NaN,...,0.0,0.0,0.00,0.0,0.0,0,1,85.34,High Risk,3
3,4,'48681,Sudhakar Anand Hankare,Housekeeper,Operations,Ramveer Bhagod,TELEPERFORMANCE GLOBAL HARYANA,TELEPERFORMANCE GLOBAL BUSINESS PVT LTD HARYANA,North Region,NaN,...,0.0,0.0,4.36,0.0,0.0,0,1,85.33,High Risk,4
4,5,'62969,Shriram Seetaram Kanoje,Housekeeper,Operations,Ramveer Bhagod,TELEPERFORMANCE GLOBAL HARYANA,TELEPERFORMANCE GLOBAL BUSINESS PVT LTD HARYANA,North Region,NaN,...,0.0,0.0,3.35,0.0,0.0,0,1,85.16,High Risk,5
5,6,'62053,Girish Motiram Jadhav,Senior Executive - Finance & Accounts,Finance & Accounts,Psipl Admin,A DIET EXPRESS HOSPITALITY CHENNAI MUMBAI,A DIET EXPRESS HOSPITALITY CHENNAI,South - Chennai,NaN,...,0.0,0.0,0.00,0.0,0.0,0,1,84.27,High Risk,6
6,7,'522934,Rahul Ramchandra Dhavade,Senior Executive - Finance & Accounts,Finance & Accounts,Psipl Admin,A DIET EXPRESS HOSPITALITY CHENNAI MUMBAI,A DIET EXPRESS HOSPITALITY CHENNAI,South - Chennai,NaN,...,0.0,0.0,0.00,0.0,0.0,0,1,83.93,High Risk,7
7,8,'550389,SACHIN PANDURANG WAINGADE,Executive - Operations,Operations,Psipl Admin,ACESTAR PROPERTIES P3/P4 CHENNAI,ACESTAR PROPERTIES P3/P4 CHENNAI,South - Chennai,NaN,...,0.0,0.0,0.00,0.0,0.0,0,1,83.77,High Risk,8
8,9,'558924,Sonu Narottam Goud,Executive - Operations,Operations,Psipl Admin,ACESTAR PROPERTIES P1/P2 CHENNAI,ACESTAR PROPERTIES P1/P2 CHENNAI,South - Chennai,NaN,...,0.0,0.0,0.00,0.0,0.0,0,1,83.44,High Risk,9
9,10,'541817,Amol Vitthal Raut,Housekeeper,Operations,Ramveer Bhagod,TELEPERFORMANCE GLOBAL HARYANA,TELEPERFORMANCE GLOBAL BUSINESS PVT LTD HARYANA,North Region,NaN,...,0.0,0.0,4.36,0.0,0.0,0,1,83.30,High Risk,10